(() => {
  "use strict";
  const course=window.LLM_COURSE;
  const chapter=course.chapters.find(c=>c.file==="01_ResNet18_CIFAR10.ipynb");
  if(!chapter)return;
  chapter.notebook_goal="CIFAR-10의 학습·평가 transform을 구분하고 ResNet18을 32×32 입력에 맞춘 뒤 AMP 학습, 추론, metric, Grad-CAM까지 구현한다.";
  chapter.capability="[B,3,32,32] 입력과 [B,10] logits의 흐름을 추적하며 데이터 변형·모델 변경·학습·평가 코드를 독립적으로 완성할 수 있다.";
  chapter.summary="학습 이미지는 crop·flip으로 증강하고 train/test 모두 Tensor 변환과 정규화를 거칩니다. CIFAR용 ResNet stem과 10-class head를 학습한 뒤 accuracy·confusion matrix·Grad-CAM으로 결과를 해석합니다.";
  chapter.overview={title:"CIFAR-10 이미지가 분류와 해석 결과가 되는 과정",subtitle:"학습용 증강과 평가용 전처리를 구분하고, 작은 이미지에 맞춘 ResNet18의 logits를 label과 연결한다.",steps:[
    {label:"Transform",code:"Crop/Flip → Tensor → Normalize",flow:"PIL → [3,32,32] float"},
    {label:"DataLoader",code:"train shuffle / test fixed",flow:"samples → [B,3,32,32]"},
    {label:"ResNet18",code:"3×3 stem + 10-class fc",flow:"[B,3,32,32] → [B,10]"},
    {label:"Train",code:"CE + AMP backward/step",flow:"logits + [B] labels → weights"},
    {label:"Evaluate",code:"argmax / confusion / Grad-CAM",flow:"logits → class·evidence"}
  ],rules:["무작위 crop·flip은 train transform에만 넣는다.","ToTensor가 PIL을 float CHW로 바꾼 뒤 Normalize를 호출한다.","CrossEntropyLoss에는 softmax가 아닌 raw logits [B,C]와 long label [B]를 전달한다.","ResNet18 첫 Conv는 CIFAR 해상도에 맞춰 3×3 stride 1로 바꾸고 maxpool을 제거한다.","평가 함수는 eval·no_grad를 쓰며 backward와 optimizer step을 호출하지 않는다."]};
  chapter.key_points=[
    {title:"Train·Test transform",purpose:"학습에는 일반화를 위한 무작위 증강을, 평가에는 결정적인 변환만 적용합니다.",code:"train: RandomCrop → Flip → ToTensor → Normalize\ntest: ToTensor → Normalize",flow:"PIL → float [C,H,W]",watch:"Normalize가 ToTensor보다 먼저 오면 입력 형식이 맞지 않습니다."},
    {title:"CIFAR용 ResNet",purpose:"ImageNet용 큰 stem을 32×32 이미지에 맞추고 class head를 10개 출력으로 바꿉니다.",code:"Conv2d(3,64,3,1,1)\nmaxpool=Identity()\nfc=Linear(in_features,10)",flow:"[B,3,32,32] → [B,10]",watch:"fc 입력 차원은 기존 model.fc.in_features를 보존합니다."},
    {title:"AMP 학습",purpose:"mixed precision으로 forward·loss를 계산하고 scaler가 작은 gradient의 underflow를 줄입니다.",code:"autocast → scale(loss).backward → step → update",flow:"logits [B,10]+labels [B] → scalar → gradients",watch:"scaler.step과 scaler.update를 일반 optimizer.step 대신 사용합니다."},
    {title:"평가 Metric",purpose:"class 축의 최대 logit index를 정답과 비교해 전체·클래스별 정확도를 계산합니다.",code:"pred=logits.argmax(dim=1)\ncm[target,pred]+=1",flow:"[B,10] → [B] → confusion [10,10]",watch:"confusion matrix 행은 GT, 열은 prediction입니다."},
    {title:"Grad-CAM",purpose:"선택 class score가 마지막 convolution activation에 미치는 gradient로 주목 영역을 만듭니다.",code:"w=grad.mean((2,3))\ncam=relu((w*activ).sum(dim=1))",flow:"activ/grad [B,C,H,W] → cam [B,1,H,W]",watch:"softmax 확률이 아니라 선택 class logit을 backward합니다."}
  ];
  chapter.theory_guide=[
    {title:"증강과 정규화",concept:"증강은 입력 다양성을 늘리고, 정규화는 채널별 (x-mean)/std로 학습 수치 범위를 맞춥니다.",flow:"PIL → stochastic geometry → [0,1] Tensor → normalized Tensor",code_signal:"Random으로 시작하는 함수는 train_tfms에만 있습니다.",exam_clue:"이번 기출인 RandomCrop·RandomHorizontalFlip·ToTensor·Normalize 순서를 통째로 복원하세요."},
    {title:"Logits와 label",concept:"logits는 정규화되지 않은 class 점수이며 CrossEntropyLoss 내부에서 log-softmax를 처리합니다.",flow:"[B,10] float + [B] long → scalar loss",code_signal:"criterion(logits, labels) 앞에 별도 softmax가 없습니다.",exam_clue:"확률은 추론 표시용 predict_batch에서만 만듭니다."},
    {title:"Train·Eval mode",concept:"train은 BatchNorm 통계와 parameter gradient를 갱신하고 eval은 이를 고정해 일관된 예측을 만듭니다.",flow:"train: forward→backward→step; eval: forward only",code_signal:"@torch.no_grad와 model.eval이 함께 보입니다.",exam_clue:"평가 빈칸에는 zero_grad/backward/step이 없습니다."},
    {title:"Grad-CAM 가중치",concept:"class score의 spatial gradient를 평균해 channel 중요도를 만들고 activation을 가중합합니다.",flow:"score backward → grad mean → weighted activ → ReLU",code_signal:"mean dim=(2,3)은 높이·너비만 제거해 [B,C,1,1]을 유지합니다.",exam_clue:"channel dim=1을 sum한 뒤 cam shape는 [B,1,H,W]입니다."}
  ];
  const cells={
    "exam-v1-transform":`T.RandomCrop(32, padding=4),\nT.RandomHorizontalFlip(),\nT.ToTensor(),\nT.Normalize(CIFAR10_MEAN, CIFAR10_STD),`,
    "exam-v1-loader":`train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)\ntest_loader  = DataLoader(test_set, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True)`,
    "exam-v1-denorm":`mean = torch.tensor(CIFAR10_MEAN).view(1,3,1,1)\nstd  = torch.tensor(CIFAR10_STD).view(1,3,1,1)\nreturn x * std + mean`,
    "exam-v1-model":`model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)\nmodel.maxpool = nn.Identity()\nmodel.fc = nn.Linear(model.fc.in_features, num_classes)`,
    "exam-v1-accuracy":`preds = logits.argmax(dim=1)\nreturn (preds == targets).float().mean().item()`,
    "exam-v1-train":`logits = model(images)\nloss = criterion(logits, labels)\nscaler.scale(loss).backward()\nscaler.step(optimizer)\nscaler.update()`,
    "exam-v1-eval":`model.eval()\nlogits = model(images)\nloss = criterion(logits, labels)\ntotal_acc  += accuracy_top1(logits, labels) * bs`,
    "exam-v1-predict":`probs = F.softmax(logits, dim=1)\nconf, pred = probs.max(dim=1)\nreturn pred, conf, probs`,
    "exam-v1-confusion":`cm[int(t), int(p)] += 1\nper_class_acc = cm.diagonal().float() / torch.clamp(cm.sum(dim=1).float(), min=1.0)\nreturn cm, per_class_acc`,
    "exam-v1-gradcam":`score = logits[:, class_idx].sum()\nscore.backward(retain_graph=False)\nw = self.grad.mean(dim=(2,3), keepdim=True)\ncam = (w * self.activ).sum(dim=1, keepdim=True)\ncam = F.relu(cam)`
  };
  Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"};
  const make=d=>({...base,accepted_answers:[d.answer],...d});
  chapter.subjective=[
    make({id:"exam-v01-01",topic:"Train Transform",difficulty:"1 · 기출 확장",sourceId:"exam-v1-transform",prompt:"CIFAR-10 학습 이미지에 32×32 random crop·좌우 반전을 적용한 뒤 float CHW Tensor와 채널 정규화로 바꾸는 네 줄을 순서대로 작성하세요.",answer:cells["exam-v1-transform"],problem_context:`train_tfms = T.Compose([\n    ????\n    ????\n    ????\n    ????\n])`,explanation:"기하학적 증강은 PIL 상태에서 먼저 수행하고 ToTensor로 [C,H,W] float를 만든 뒤 Normalize가 채널별 표준화를 적용합니다.",tensor_flow:"PIL → augmented PIL → [3,32,32] float 0~1 → normalized float",code_signal:"train transform이라는 이름과 주석의 crop·flip·PIL→Tensor·정규화가 정확한 순서를 줍니다.",retry:"test_tfms에서 빠져야 하는 두 줄만 골라 보세요."}),
    make({id:"exam-v01-02",topic:"DataLoader 분리",difficulty:"2 · 데이터 구성",sourceId:"exam-v1-loader",prompt:"train은 매 epoch 순서를 섞고 test는 고정하며, 두 dataset을 같은 batch·worker·pinned memory 설정으로 로드하는 두 줄을 작성하세요.",answer:cells["exam-v1-loader"],problem_context:`train_loader = DataLoader(????)\ntest_loader  = DataLoader(????)`,explanation:"학습 순서는 섞어 mini-batch 편향을 줄이지만 평가는 재현 가능한 순서로 유지합니다. pin_memory는 GPU 전송 최적화에 사용됩니다.",tensor_flow:"Dataset samples → batches [B,3,32,32] and labels [B]",code_signal:"변수명 train/test와 바로 위 batch_size·num_workers가 모든 인자를 제공합니다.",retry:"두 줄에서 달라지는 dataset과 shuffle 값만 표시하세요."}),
    make({id:"exam-v01-03",topic:"역정규화",difficulty:"2 · Broadcasting",sourceId:"exam-v1-denorm",prompt:"정규화된 batch [B,3,H,W]를 표시 가능한 값으로 되돌리도록 mean/std를 broadcast shape로 만들고 역변환하는 세 줄을 작성하세요.",answer:cells["exam-v1-denorm"],problem_context:`def denorm(x):\n    mean = ????\n    std  = ????\n    return ????`,explanation:"Normalize의 역연산은 x*std+mean입니다. 채널 통계를 [1,3,1,1]로 만들어 batch와 공간축 전체에 broadcasting합니다.",tensor_flow:"[B,3,H,W] × [1,3,1,1] + [1,3,1,1]",code_signal:"주석 broadcast와 원래 Normalize(mean,std)가 역연산·shape를 결정합니다.",retry:"view(3)만 사용할 때와 [1,3,1,1]의 broadcasting 차이를 설명하세요."}),
    make({id:"exam-v01-04",topic:"CIFAR ResNet Stem",difficulty:"3 · 모델 구성",sourceId:"exam-v1-model",prompt:"ImageNet용 ResNet18을 RGB 32×32 CIFAR 입력과 num_classes 출력에 맞추도록 첫 convolution, pooling, classifier를 바꾸는 세 줄을 작성하세요.",answer:cells["exam-v1-model"],problem_context:`model = models.resnet18(weights=None)\nmodel.conv1 = ????\nmodel.maxpool = ????\nmodel.fc = ????`,explanation:"작은 이미지는 7×7 stride2와 maxpool로 너무 빨리 축소되므로 3×3 stride1 stem과 Identity를 사용합니다. fc의 기존 입력 차원을 보존하고 출력만 class 수로 바꿉니다.",tensor_flow:"[B,3,32,32] → stem [B,64,32,32] → stages → [B,num_classes]",code_signal:"입력 RGB=3, CIFAR 크기 32, 기존 fc.in_features와 num_classes가 constructor 인자를 제공합니다.",retry:"기존 ImageNet stem을 그대로 두면 초반 spatial size가 어떻게 줄어드는지 비교하세요."}),
    make({id:"exam-v01-05",topic:"Top-1 Accuracy",difficulty:"1 · Metric",sourceId:"exam-v1-accuracy",prompt:"logits [B,C]에서 class index [B]를 고르고 targets [B]와 비교한 평균 정확도를 Python scalar로 반환하는 두 줄을 작성하세요.",answer:cells["exam-v1-accuracy"],problem_context:`def accuracy_top1(logits, targets):\n    preds = ????\n    return ????`,explanation:"class 축 dim=1에서 최대 score의 index를 선택하고 boolean 비교를 float 0/1로 바꿔 평균낸 뒤 item으로 scalar를 얻습니다.",tensor_flow:"[B,C] → argmax [B] → bool [B] → scalar",code_signal:"logits shape의 두 번째 축이 class이고 함수 반환값이 누적 계산용 숫자입니다.",retry:"dim=0을 쓰면 결과 shape와 의미가 어떻게 달라지는지 확인하세요."}),
    make({id:"exam-v01-06",topic:"AMP 학습 Step",difficulty:"3 · 학습 연결",sourceId:"exam-v1-train",prompt:"autocast 문맥에서 logits와 분류 loss를 계산하고 GradScaler로 역전파·optimizer 갱신·scale 갱신을 수행하는 다섯 줄을 작성하세요.",answer:cells["exam-v1-train"],problem_context:`with torch.amp.autocast(device_type=device.type, enabled=torch.cuda.is_available()):\n    ????\n    ????\n????\n????\n????`,explanation:"forward와 loss는 autocast 안에서 계산합니다. scaler가 loss를 확대해 backward하고 optimizer step의 안전성을 확인한 뒤 다음 batch를 위해 scale을 조절합니다.",tensor_flow:"images [B,3,32,32] → logits [B,10] + labels [B] → loss → scaled gradients",code_signal:"이미 optimizer.zero_grad가 앞에 있으며 GradScaler 객체가 있으므로 일반 loss.backward/optimizer.step 대신 scaler 메서드를 씁니다.",retry:"일반 FP32 학습이라면 마지막 세 줄을 어떤 두 줄로 바꾸는지 작성하세요."}),
    make({id:"exam-v01-07",topic:"평가 Loop",difficulty:"2 · Train/Eval",sourceId:"exam-v1-eval",prompt:"gradient가 꺼진 evaluate 함수에서 모델 mode를 전환하고 logits·loss·batch accuracy 누적값을 계산하는 핵심 네 줄을 작성하세요.",answer:cells["exam-v1-eval"],problem_context:`@torch.no_grad()\ndef evaluate(model, loader, criterion):\n    ????\n    # inside batch loop\n    ????\n    ????\n    bs = images.size(0)\n    ????`,explanation:"eval mode로 BatchNorm 통계를 고정하고 forward와 metric만 수행합니다. batch 평균 accuracy에 bs를 곱해 샘플 수 가중 합을 만든 뒤 전체 n으로 나눕니다.",tensor_flow:"batch → logits [B,10] → loss/accuracy scalars → sample-weighted totals",code_signal:"decorator가 gradient를 막으므로 backward·step이 없고, 최종 total/n 때문에 bs 가중치가 필요합니다.",retry:"train_one_epoch와 비교해 평가에서 사라지는 세 연산을 적으세요."}),
    make({id:"exam-v01-08",topic:"확률·Confidence",difficulty:"2 · 추론",sourceId:"exam-v1-predict",prompt:"raw logits [B,C]를 class 확률로 바꾸고 각 sample의 최대 확률과 class index를 함께 반환하는 세 줄을 작성하세요.",answer:cells["exam-v1-predict"],problem_context:`logits = model(images)\n????\n????\n????`,explanation:"class 축에 softmax를 적용하면 각 행의 합이 1인 확률이 됩니다. max(dim=1)은 값 confidence와 index prediction을 함께 반환합니다.",tensor_flow:"[B,C] logits → [B,C] probs → conf [B], pred [B]",code_signal:"반환 변수 pred,conf,probs와 class 축 dim=1이 필요한 연산을 알려줍니다.",retry:"argmax만 쓰면 얻지 못하는 반환값이 무엇인지 설명하세요."}),
    make({id:"exam-v01-09",topic:"Confusion Matrix",difficulty:"3 · Metric 구현",sourceId:"exam-v1-confusion",prompt:"정답 t와 예측 p를 confusion matrix의 GT 행·Pred 열에 누적하고 class별 정확도를 계산해 반환하는 세 줄을 작성하세요.",answer:cells["exam-v1-confusion"],problem_context:`for t, p in zip(labels, preds):\n    ????\n????\n????`,explanation:"대각선은 정답과 예측이 같은 개수이고 각 행 합은 해당 실제 class 수입니다. 0개 class의 나눗셈을 막기 위해 분모를 최소 1로 clamp합니다.",tensor_flow:"labels,preds [N] → cm [C,C] → diagonal/row sums [C]",code_signal:"plot 축 label이 y=GT, x=Pred이고 per-class accuracy 정의가 diagonal/실제 class 수입니다.",retry:"행·열을 반대로 누적하면 어떤 metric 해석이 바뀌는지 설명하세요."}),
    make({id:"exam-v01-10",topic:"Grad-CAM",difficulty:"3 · 독립 구현",sourceId:"exam-v1-gradcam",prompt:"선택 class logit을 역전파하고 spatial gradient 평균을 channel 가중치로 사용해 양의 Grad-CAM [B,1,H,W]을 만드는 다섯 줄을 작성하세요.",answer:cells["exam-v1-gradcam"],problem_context:`????\n????\n????\n????\n????\ncam = cam - cam.min()`,explanation:"선택 class score의 gradient를 얻고 H,W 평균으로 channel별 중요도 [B,C,1,1]를 만듭니다. activation과 곱해 channel 합을 구한 뒤 ReLU로 양의 기여만 남깁니다.",tensor_flow:"logits [B,K] → score → grad/activ [B,C,H,W] → w [B,C,1,1] → cam [B,1,H,W]",code_signal:"forward/backward hook이 self.activ과 self.grad를 저장하며 주석 channel importance가 mean 축을 알려줍니다.",retry:"mean에서 dim=1을 사용하면 왜 channel 가중치가 사라지는지 확인하세요."})
  ];
  chapter.mcq=[
    {id:"exam-v01-m1",source_question_id:"exam-v01-01",topic:"Transform 순서",prompt:"학습용 CIFAR-10 transform의 올바른 순서는?",answer_index:2,explanation:"PIL 공간 증강 후 Tensor로 바꾸고 마지막에 채널 정규화합니다.",choices:[{text:"Normalize→ToTensor→Crop→Flip",why:"Normalize 입력 형식과 증강 순서가 틀립니다."},{text:"ToTensor→Normalize→Crop→Flip",why:"Tensor 이후 PIL용 공간 증강을 배치했습니다."},{text:"Crop→Flip→ToTensor→Normalize",why:"기출 코드의 올바른 순서입니다."},{text:"Flip→Normalize→ToTensor→Crop",why:"Normalize가 Tensor보다 앞입니다."},{text:"Crop→ToTensor→Normalize→Flip",why:"무작위 flip이 정규화 뒤에 있습니다."}]},
    {id:"exam-v01-m2",source_question_id:"exam-v01-04",topic:"CIFAR Stem",prompt:"32×32 CIFAR 입력에서 ImageNet ResNet stem을 바꾸는 핵심 이유는?",answer_index:0,explanation:"초기 downsampling을 줄여 작은 이미지의 공간 정보를 보존합니다.",choices:[{text:"초기 공간 해상도를 과도하게 줄이지 않기 위해",why:"3×3 stride1과 maxpool 제거 목적입니다."},{text:"RGB를 grayscale로 바꾸기 위해",why:"입력 채널은 여전히 3입니다."},{text:"클래스 수를 64로 늘리기 위해",why:"클래스 수는 fc가 담당합니다."},{text:"softmax를 추가하기 위해",why:"stem과 무관합니다."},{text:"label dtype을 바꾸기 위해",why:"데이터와 loss 설정입니다."}]},
    {id:"exam-v01-m3",source_question_id:"exam-v01-06",topic:"AMP 순서",prompt:"scaled loss 계산 후 올바른 AMP 갱신 순서는?",answer_index:4,explanation:"scale한 loss를 backward하고 scaler가 optimizer를 step한 뒤 scale을 갱신합니다.",choices:[{text:"update→step→backward",why:"역순입니다."},{text:"optimizer.step→loss.backward",why:"AMP scaler를 우회하고 순서도 틀립니다."},{text:"backward→update→step",why:"scale을 step 전에 바꿉니다."},{text:"step→zero_grad→update",why:"gradient 생성이 없습니다."},{text:"scale(loss).backward→scaler.step→scaler.update",why:"표준 GradScaler 순서입니다."}]},
    {id:"exam-v01-m4",source_question_id:"exam-v01-09",topic:"Class Accuracy",prompt:"confusion matrix가 cm[GT,Pred]일 때 class별 정확도의 분모는?",answer_index:1,explanation:"각 GT class의 전체 샘플 수는 해당 행 합입니다.",choices:[{text:"열 합 cm.sum(dim=0)",why:"예측된 class별 개수입니다."},{text:"행 합 cm.sum(dim=1)",why:"실제 class별 전체 개수입니다."},{text:"전체 합 cm.sum()",why:"전체 정확도 분모입니다."},{text:"대각선 합",why:"맞힌 수이며 분자입니다."},{text:"num_classes",why:"샘플 수가 아닙니다."}]},
    {id:"exam-v01-m5",source_question_id:"exam-v01-10",topic:"Grad-CAM 축",prompt:"gradient [B,C,H,W]에서 channel 가중치 [B,C,1,1]를 만드는 평균 축은?",answer_index:3,explanation:"공간 H,W만 평균내고 batch와 channel을 보존합니다.",choices:[{text:"dim=1",why:"channel을 제거합니다."},{text:"dim=(0,1)",why:"batch와 channel을 제거합니다."},{text:"dim=0",why:"batch만 평균냅니다."},{text:"dim=(2,3)",why:"공간축만 평균냅니다."},{text:"모든 축",why:"scalar 하나만 남습니다."}]}
  ];
  chapter.questionCount=chapter.subjective.length;
  chapter.exam_design={version:2,style:"원본 전체 코드 함수 문맥형",difficulty:["기출 호출 연결","Tensor·metric 연결","모델·Grad-CAM 독립 구현"],excluded:["URL·경로","고정 epoch·seed","시각화 제목 암기"]};
})();

(() => {
  "use strict";
  const course=window.LLM_COURSE,chapter=course.chapters.find(c=>c.file==="02_ViT_CIFAR10.ipynb");if(!chapter)return;
  chapter.notebook_goal="CIFAR-10 이미지를 patch token으로 바꾸고 Q·K·V self-attention, CLS·position embedding, residual encoder, 분류 학습까지 구현한다.";
  chapter.capability="이미지와 토큰의 shape를 추적하며 ViT patch embedding·multi-head attention·CLS pooling·loss 코드를 독립적으로 완성할 수 있다.";
  chapter.summary="32×32 이미지는 4×4 patch 64개와 CLS 1개로 구성된 token sequence가 되고, multi-head self-attention과 FFN을 거쳐 CLS 표현에서 10-class logits를 만듭니다.";
  chapter.overview={title:"이미지가 65개 토큰을 거쳐 분류 logits가 되는 과정",subtitle:"공간 패치를 sequence로 바꾸고 모든 토큰 사이의 관계를 attention으로 학습한다.",steps:[{label:"Patchify",code:"[B,C,H,W] → [B,N,patch_dim]",flow:"32×32 / 4×4 → N=64"},{label:"Embedding",code:"Linear + CLS + Position",flow:"[B,64,D] → [B,65,D]"},{label:"Attention",code:"QKᵀ/√d → softmax → AV",flow:"[B,H,65,d]"},{label:"Encoder",code:"Attention+residual, FFN+residual",flow:"[B,65,D] 유지"},{label:"Classifier",code:"CLS or mean → Linear",flow:"[B,D] → [B,10]"}],rules:["패치 수 N=(H/Ph)(W/Pw), patch_dim=C·Ph·Pw를 구분한다.","Q·K·V를 head별 [B,H,N,d]로 재배열한 뒤 attention score는 [B,H,N,N]이다.","softmax는 각 query가 참조할 key 축인 마지막 차원에 적용한다.","CLS를 붙인 뒤 position embedding 길이도 n+1만큼 사용한다.","CrossEntropy 조합은 raw logits, log_softmax+nll_loss 조합은 log-probability를 입력한다."]};
  chapter.key_points=[{title:"Patch token",purpose:"2차원 이미지를 Transformer가 처리할 sequence로 변환합니다.",code:"N=(H/Ph)*(W/Pw)\npatch_dim=C*Ph*Pw",flow:"[B,C,H,W] → [B,N,patch_dim] → [B,N,D]",watch:"token 수와 token feature 차원을 바꾸지 않습니다."},{title:"Multi-head Attention",purpose:"각 token이 다른 모든 token에서 필요한 정보를 가중합합니다.",code:"QKᵀ * d^-0.5 → Softmax → Attention·V",flow:"Q,K,V [B,H,N,d] → attn [B,H,N,N] → [B,N,D]",watch:"K의 token 축을 transpose하는 einsum index를 확인합니다."},{title:"CLS·Position",purpose:"CLS는 이미지 전체 표현을 모으고 position은 patch의 공간 순서를 알려줍니다.",code:"cat(CLS,x,dim=1)\nx += pos[:,:n+1]",flow:"[B,N,D] → [B,N+1,D]",watch:"CLS token은 batch만큼 repeat합니다."},{title:"Residual Encoder",purpose:"Attention과 FFN의 변화량을 원래 token에 더해 깊은 학습을 안정화합니다.",code:"x=attn(x)+x\nx=ff(x)+x",flow:"[B,N+1,D] shape 유지",watch:"두 sublayer 모두 별도의 residual이 있습니다."},{title:"분류·평가",purpose:"CLS 또는 token 평균을 class head에 넣고 정답 label과 loss를 계산합니다.",code:"x=x[:,0] or x.mean(1)\nlogits=head(x)",flow:"[B,65,D] → [B,D] → [B,10]",watch:"분류 head 전에 token 축을 제거합니다."}];
  chapter.theory_guide=[{title:"Scaled dot-product",concept:"Q와 K 내적은 d가 커질수록 값이 커지므로 1/√d를 곱해 softmax가 지나치게 포화되지 않게 합니다.",flow:"[B,H,N,d]×[B,H,N,d] → [B,H,N,N]",code_signal:"self.scale=dim_head ** -0.5입니다.",exam_clue:"** -0.5는 제곱근의 역수입니다."},{title:"einsum index",concept:"i는 query token, j는 key/value token, d는 head feature입니다.",flow:"q[i,d]·k[j,d] → score[i,j]; attn[i,j]·v[j,d] → out[i,d]",code_signal:"첫 식은 d를 줄이고 i,j를 남기며 두 번째는 j를 줄입니다.",exam_clue:"출력에 남아야 할 index를 먼저 적으세요."},{title:"CLS와 position",concept:"동일한 patch 변환만으로는 위치 순서를 알 수 없으므로 학습 가능한 position vector를 더합니다.",flow:"64 patch + 1 CLS = 65 token",code_signal:"pos_embedding의 두 번째 차원이 num_patches+1입니다.",exam_clue:"slice는 n이 아니라 n+1까지입니다."},{title:"학습 loss 조합",concept:"log_softmax는 log-probability를 만들고 NLL loss가 정답 class의 음의 log 값을 최소화합니다.",flow:"logits [B,C] → log_probs [B,C] + labels [B] → scalar",code_signal:"F.log_softmax와 F.nll_loss가 연속합니다.",exam_clue:"CrossEntropyLoss를 쓰면 log_softmax를 별도로 적용하지 않습니다."}];
  const cells={
    "exam-v2-patchcalc":`num_patches = (image_height // patch_height) * (image_width // patch_width)\npatch_dim = cfg.channels * patch_height * patch_width`,
    "exam-v2-qkv":`qkv = self.to_qkv(x).chunk(3, dim = -1)\nq, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h = h), qkv)`,
    "exam-v2-attn":`dots = einsum('b h i d, b h j d -> b h i j', q, k) * self.scale\nattn = self.attend(dots)\nout = einsum('b h i j, b h j d -> b h i d', attn, v)`,
    "exam-v2-residual":`x = attn(x) + x\nx = ff(x) + x`,
    "exam-v2-clspos":`x = self.to_patch_embedding(img)\ncls_tokens = repeat(self.cls_token, "1 1 d -> b 1 d", b=b)\nx = torch.cat((cls_tokens, x), dim=1)\nx = x + self.pos_embedding[:, : (n + 1)]`,
    "exam-v2-head":`x = x[:, 0] if self.pool == "cls" else x.mean(dim=1)\nreturn self.mlp_head(x)`,
    "exam-v2-train":`optimizer.zero_grad()\noutput = F.log_softmax(model(data), dim=1)\nloss = F.nll_loss(output, target)\nloss.backward()\noptimizer.step()`,
    "exam-v2-eval":`output = F.log_softmax(model(data), dim=1)\nloss = F.nll_loss(output, target, reduction='sum')\n_, pred = torch.max(output, dim=1)\ntotal_loss += float(loss.item())\ncorrect_samples += int(pred.eq(target).sum().item())`,
    "exam-v2-clsmap":`cls_attn = attn_bhNN.mean(dim=1)[0, 0, 1:]\nattn_2d = cls_attn_1d.reshape(grid_h, grid_w)\nattn_up = F.interpolate(attn_t, size=(out_h, out_w), mode="bilinear", align_corners=False)[0,0]`,
    "exam-v2-wrong":`logits = model(data)\npreds = logits.argmax(dim=1)\nwrong_mask = preds.ne(target)\nwrong_data = data[wrong_mask].detach().cpu()`
  };Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"},make=d=>({...base,accepted_answers:[d.answer],...d});
  chapter.subjective=[
    make({id:"exam-v02-01",topic:"Patch 수·차원",difficulty:"1 · Shape",sourceId:"exam-v2-patchcalc",prompt:"image·patch 크기와 channel 수로 patch token 개수와 펼친 patch feature 차원을 계산하는 두 줄을 작성하세요.",answer:cells["exam-v2-patchcalc"],problem_context:`image_height, image_width = pair(cfg.image_size)\npatch_height, patch_width = pair(cfg.patch_size)\n????\n????`,explanation:"patch 개수는 세로·가로 grid 수의 곱이고 한 patch vector는 channel×patch 높이×너비입니다.",tensor_flow:"[B,C,H,W] → N=(H/Ph)(W/Pw), patch_dim=CPhPw",code_signal:"Rearrange의 h,w와 p1,p2,c가 두 수식에 그대로 대응합니다.",retry:"32×32 RGB, 4×4 patch일 때 N과 patch_dim을 계산하세요."}),
    make({id:"exam-v02-02",topic:"Q·K·V Head 분리",difficulty:"2 · Tensor 재배열",sourceId:"exam-v2-qkv",prompt:"token [B,N,D]를 한 번에 Q·K·V로 투영·분할하고 각각 [B,H,N,d]로 재배열하는 두 줄을 작성하세요.",answer:cells["exam-v2-qkv"],problem_context:`b, n, _, h = *x.shape, self.heads\n????\n????`,explanation:"Linear 출력의 마지막 축 3·H·d를 세 Tensor로 나눈 뒤 결합된 H·d를 head와 head_dim으로 분리합니다.",tensor_flow:"[B,N,D] → [B,N,3Hd] → 3×[B,H,N,d]",code_signal:"to_qkv의 out_features=inner_dim*3과 self.heads가 chunk 수·rearrange pattern을 결정합니다.",retry:"chunk의 dim을 1로 쓰면 어떤 축이 잘못 나뉘는지 설명하세요."}),
    make({id:"exam-v02-03",topic:"Scaled Self-Attention",difficulty:"3 · 독립 구현",sourceId:"exam-v2-attn",prompt:"head별 Q·K로 scaled token score를 만들고 마지막 축 softmax 후 V를 가중합하는 세 줄을 작성하세요.",answer:cells["exam-v2-attn"],problem_context:`????\n????\nself.last_attn = attn.detach()\n????`,explanation:"Q의 i token과 K의 j token 내적으로 [i,j] score를 만들고 scale 후 softmax합니다. j축 attention으로 V[j]를 합쳐 query i의 새 표현을 얻습니다.",tensor_flow:"Q,K [B,H,N,d] → dots/attn [B,H,N,N] → out [B,H,N,d]",code_signal:"einsum 출력에 첫 계산은 i,j, 두 번째는 i,d가 남아야 합니다.",retry:"각 einsum에서 합산되어 사라지는 index를 표시하세요."}),
    make({id:"exam-v02-04",topic:"Encoder Residual",difficulty:"1 · Layer 연결",sourceId:"exam-v2-residual",prompt:"각 Transformer layer에서 Attention과 FFN 출력에 각각 residual을 적용하는 두 줄을 작성하세요.",answer:cells["exam-v2-residual"],problem_context:`for attn, ff in self.layers:\n    ????\n    ????`,explanation:"각 sublayer가 만든 변화량을 입력 x에 더해 원래 정보를 보존하고 gradient 흐름을 안정화합니다.",tensor_flow:"[B,N,D] → attention+identity → FFN+identity → [B,N,D]",code_signal:"PreNorm wrapper가 정규화를 내부 처리하므로 loop에는 두 함수 호출과 +x만 남습니다.",retry:"두 번째 줄이 ff(attn(x))+x가 아닌 이유를 설명하세요."}),
    make({id:"exam-v02-05",topic:"CLS·Position",difficulty:"3 · Sequence 구성",sourceId:"exam-v2-clspos",prompt:"이미지를 patch embedding으로 바꾸고 CLS를 batch만큼 복제해 앞에 붙인 뒤 n+1개 position embedding을 더하는 네 줄을 작성하세요.",answer:cells["exam-v2-clspos"],problem_context:`????\nb, n, _ = x.shape\n????\n????\n????`,explanation:"patch sequence 앞에 학습 가능한 CLS를 추가하므로 token 수가 n+1이 됩니다. 위치 embedding도 같은 길이로 slice되어 broadcasting됩니다.",tensor_flow:"[B,C,H,W] → [B,N,D] → [B,N+1,D] + [1,N+1,D]",code_signal:"cls_token shape [1,1,D], pos_embedding shape [1,num_patches+1,D]가 repeat·cat 축을 알려줍니다.",retry:"cat dim=-1을 쓰면 어떤 차원이 잘못 늘어나는지 확인하세요."}),
    make({id:"exam-v02-06",topic:"Pooling·Classifier",difficulty:"2 · 출력",sourceId:"exam-v2-head",prompt:"Encoder token에서 설정에 따라 CLS 또는 token 평균을 선택하고 class head로 logits를 반환하는 두 줄을 작성하세요.",answer:cells["exam-v2-head"],problem_context:`x = self.transformer(x)\n????\n????`,explanation:"CLS pooling은 index 0, mean pooling은 token 축 dim=1을 제거합니다. 둘 다 [B,D]가 되어 mlp_head에서 [B,C] logits로 바뀝니다.",tensor_flow:"[B,N+1,D] → [B,D] → [B,num_classes]",code_signal:"self.pool에 허용된 문자열 cls/mean과 head 첫 Linear 입력 D가 선택을 결정합니다.",retry:"mean(dim=-1)을 쓰면 head 입력 shape가 왜 틀리는지 설명하세요."}),
    make({id:"exam-v02-07",topic:"ViT 학습 Step",difficulty:"2 · Loss",sourceId:"exam-v2-train",prompt:"batch에서 gradient를 초기화하고 ViT logits를 log-probability로 바꿔 NLL loss를 계산·역전파·갱신하는 다섯 줄을 작성하세요.",answer:cells["exam-v2-train"],problem_context:`????\n????\n????\n????\n????`,explanation:"log_softmax와 NLL loss는 CrossEntropy와 동등한 조합입니다. 이전 gradient를 지운 후 loss gradient로 optimizer가 parameter를 갱신합니다.",tensor_flow:"data [B,3,32,32] → logits/log_probs [B,10] + target [B] → scalar",code_signal:"주석 Negative Log Likelihood와 optimizer가 표준 학습 순서를 알려줍니다.",retry:"CrossEntropyLoss를 사용한 대체 두 줄을 작성하세요."}),
    make({id:"exam-v02-08",topic:"평가 Loss·Accuracy",difficulty:"3 · Metric 연결",sourceId:"exam-v2-eval",prompt:"gradient 없는 평가에서 log-probability, 합산 loss, class 예측을 구해 전체 loss와 정답 개수를 누적하는 다섯 줄을 작성하세요.",answer:cells["exam-v2-eval"],problem_context:`with torch.no_grad():\n    # inside loop\n    ????\n    ????\n    ????\n    ????\n    ????`,explanation:"batch loss를 reduction=sum으로 계산해야 전체 sample 기준 평균을 마지막에 정확히 구할 수 있습니다. class 최대값 index를 target과 비교해 맞은 개수를 누적합니다.",tensor_flow:"[B,10] → batch loss sum + pred [B] → dataset totals",code_signal:"loop 밖 avg_loss=total_loss/total_samples와 acc=correct_samples/total_samples가 reduction과 누적 방식을 정합니다.",retry:"reduction 기본 mean을 사용하면 total_loss 누적에 무엇을 곱해야 하는지 말하세요."}),
    make({id:"exam-v02-09",topic:"CLS Attention Map",difficulty:"3 · 해석",sourceId:"exam-v2-clsmap",prompt:"attention [1,H,N+1,N+1]에서 head 평균 CLS→patch 값만 골라 patch grid로 바꾸고 이미지 크기로 보간하는 세 줄을 작성하세요.",answer:cells["exam-v2-clsmap"],problem_context:`# CLS index=0, patches=1:\n????\n????\n????`,explanation:"head를 평균낸 뒤 batch0의 query CLS 0에서 key patch 1:만 선택합니다. 1D patch 값을 grid로 reshape하고 bilinear interpolation으로 입력 해상도에 맞춥니다.",tensor_flow:"[1,H,N+1,N+1] → [N] → [Gh,Gw] → [H,W]",code_signal:"CLS와 patch index 주석, grid_h*grid_w=num_patches 조건이 slicing과 reshape를 결정합니다.",retry:"마지막 1:을 생략하면 grid reshape가 실패하는 이유를 설명하세요."}),
    make({id:"exam-v02-10",topic:"오분류 선택",difficulty:"2 · 분석",sourceId:"exam-v2-wrong",prompt:"평가 batch의 logits에서 예측 class를 만들고 target과 다른 mask로 오분류 이미지만 CPU Tensor로 선택하는 네 줄을 작성하세요.",answer:cells["exam-v2-wrong"],problem_context:`????\n????\n????\nif wrong_mask.any():\n    ????`,explanation:"class 축 argmax로 예측 [B]를 만들고 ne 비교 mask [B]를 image batch 첫 축에 적용합니다. 시각화를 위해 gradient를 분리해 CPU로 옮깁니다.",tensor_flow:"data [B,C,H,W] → logits [B,K] → mask [B] → wrong [M,C,H,W]",code_signal:"오분류 조건은 preds와 target의 not-equal이며 boolean mask는 batch 축을 선택합니다.",retry:"labels와 predictions까지 같은 mask로 선택하는 두 줄을 추가하세요."})
  ];
  chapter.mcq=[
    {id:"exam-v02-m1",source_question_id:"exam-v02-01",topic:"Patch shape",prompt:"32×32 RGB 이미지를 4×4 patch로 나눌 때 token 수와 patch_dim은?",answer_index:2,explanation:"8×8=64 patch, 3×4×4=48 feature입니다.",choices:[{text:"16,64",why:"grid와 embedding dim을 혼동했습니다."},{text:"48,64",why:"patch_dim과 token 수 순서가 바뀌었습니다."},{text:"64,48",why:"올바른 계산입니다."},{text:"65,48",why:"65는 CLS를 붙인 뒤 token 수입니다."},{text:"64,3",why:"patch 공간 크기를 반영하지 않았습니다."}]},
    {id:"exam-v02-m2",source_question_id:"exam-v02-03",topic:"Attention score",prompt:"Q,K가 [B,H,N,d]일 때 QKᵀ score shape는?",answer_index:4,explanation:"각 query token과 모든 key token 조합을 갖습니다.",choices:[{text:"[B,N,d]",why:"head와 key token 관계가 없습니다."},{text:"[B,H,d,d]",why:"token이 아니라 feature 관계입니다."},{text:"[N,N]",why:"batch와 head가 사라졌습니다."},{text:"[B,H,N,d]",why:"value 가중합 후 shape입니다."},{text:"[B,H,N,N]",why:"query와 key token 축이 남습니다."}]},
    {id:"exam-v02-m3",source_question_id:"exam-v02-05",topic:"CLS 연결",prompt:"CLS [B,1,D]를 patch [B,N,D] 앞에 붙일 축은?",answer_index:1,explanation:"token sequence 축 dim=1을 연결합니다.",choices:[{text:"dim=0",why:"batch 수가 늘어납니다."},{text:"dim=1",why:"token 수가 N+1이 됩니다."},{text:"dim=2",why:"embedding 차원이 늘어납니다."},{text:"stack dim=1",why:"새 축이 생겨 rank가 달라집니다."},{text:"연결하지 않고 더함",why:"token 수 1과 N이 맞지 않습니다."}]},
    {id:"exam-v02-m4",source_question_id:"exam-v02-07",topic:"Loss 조합",prompt:"F.log_softmax(model(data),dim=1)의 올바른 loss는?",answer_index:0,explanation:"log-probability는 NLL loss와 짝을 이룹니다.",choices:[{text:"F.nll_loss(output,target)",why:"올바른 조합입니다."},{text:"MSELoss(output,target)",why:"class index 회귀가 아닙니다."},{text:"CrossEntropyLoss(output,target)",why:"log_softmax를 중복 처리합니다."},{text:"BCEWithLogitsLoss(output,target)",why:"단일-label multiclass 설정과 target 형식이 다릅니다."},{text:"softmax(output)",why:"loss가 아닙니다."}]},
    {id:"exam-v02-m5",source_question_id:"exam-v02-09",topic:"Attention 해석",prompt:"CLS가 patch를 참고한 attention만 선택하는 index는?",answer_index:3,explanation:"query CLS=0, key patch=1:이며 head는 평균합니다.",choices:[{text:"attn[0,:,1:,0]",why:"patch query가 CLS key를 보는 반대 방향입니다."},{text:"attn.mean(1)[0,1:,1:]",why:"patch-to-patch matrix입니다."},{text:"attn[0,0,0,0]",why:"한 head의 CLS self 값 하나입니다."},{text:"attn.mean(1)[0,0,1:]",why:"head 평균 CLS→patch vector입니다."},{text:"attn.mean(0)",why:"batch만 평균하고 필요한 index를 고르지 않았습니다."}]}
  ];chapter.questionCount=chapter.subjective.length;chapter.exam_design={version:2,style:"전체 코드·Tensor 문맥형",difficulty:["shape 계산","연산 연결","attention 독립 구현"],excluded:["경로·패키지 설치","고정 epoch","시각화 제목"]};
})();
