(() => {
  "use strict";
  const course=window.LLM_COURSE;
  const chapter=course.chapters.find(c=>c.file==="01_ResNet18_CIFAR10.ipynb");
  if(!chapter)return;
  chapter.notebook_goal="CIFAR-10의 학습·평가 transform을 구분하고 ResNet18을 32×32 입력에 맞춘 뒤 AMP 학습, 추론, metric, Grad-CAM까지 구현한다.";
  chapter.capability="[B,3,32,32] 입력과 [B,10] logits의 흐름을 추적하며 데이터 변형·모델 변경·학습·평가 코드를 독립적으로 완성할 수 있다.";
  chapter.summary="학습 이미지는 crop·flip으로 증강하고 train/test 모두 Tensor 변환과 정규화를 거칩니다. CIFAR용 ResNet stem과 10-class head를 학습한 뒤 accuracy·confusion matrix·Grad-CAM으로 결과를 해석합니다.";
  chapter.overview={title:"CIFAR-10 이미지가 분류와 해석 결과가 되는 과정",subtitle:"학습용 증강과 평가용 전처리를 구분하고, 작은 이미지에 맞춘 ResNet18의 logits를 label과 연결한다.",steps:[
    {label:"Transform",code:"Crop/Flip → Tensor → Normalize",flow:"PIL → [3,32,32] float"},
    {label:"DataLoader",code:"train shuffle / test fixed",flow:"samples → [B,3,32,32]"},
    {label:"ResNet18",code:"3×3 stem + 10-class fc",flow:"[B,3,32,32] → [B,10]"},
    {label:"Train",code:"CE + AMP backward/step",flow:"logits + [B] labels → weights"},
    {label:"Evaluate",code:"argmax / confusion / Grad-CAM",flow:"logits → class·evidence"}
  ],rules:["무작위 crop·flip은 train transform에만 넣는다.","ToTensor가 PIL을 float CHW로 바꾼 뒤 Normalize를 호출한다.","CrossEntropyLoss에는 softmax가 아닌 raw logits [B,C]와 long label [B]를 전달한다.","ResNet18 첫 Conv는 CIFAR 해상도에 맞춰 3×3 stride 1로 바꾸고 maxpool을 제거한다.","평가 함수는 eval·no_grad를 쓰며 backward와 optimizer step을 호출하지 않는다."]};
  chapter.key_points=[
    {title:"Train·Test transform",purpose:"학습에는 일반화를 위한 무작위 증강을, 평가에는 결정적인 변환만 적용합니다.",code:"train: RandomCrop → Flip → ToTensor → Normalize\ntest: ToTensor → Normalize",flow:"PIL → float [C,H,W]",watch:"Normalize가 ToTensor보다 먼저 오면 입력 형식이 맞지 않습니다."},
    {title:"CIFAR용 ResNet",purpose:"ImageNet용 큰 stem을 32×32 이미지에 맞추고 class head를 10개 출력으로 바꿉니다.",code:"Conv2d(3,64,3,1,1)\nmaxpool=Identity()\nfc=Linear(in_features,10)",flow:"[B,3,32,32] → [B,10]",watch:"fc 입력 차원은 기존 model.fc.in_features를 보존합니다."},
    {title:"AMP 학습",purpose:"mixed precision으로 forward·loss를 계산하고 scaler가 작은 gradient의 underflow를 줄입니다.",code:"autocast → scale(loss).backward → step → update",flow:"logits [B,10]+labels [B] → scalar → gradients",watch:"scaler.step과 scaler.update를 일반 optimizer.step 대신 사용합니다."},
    {title:"평가 Metric",purpose:"class 축의 최대 logit index를 정답과 비교해 전체·클래스별 정확도를 계산합니다.",code:"pred=logits.argmax(dim=1)\ncm[target,pred]+=1",flow:"[B,10] → [B] → confusion [10,10]",watch:"confusion matrix 행은 GT, 열은 prediction입니다."},
    {title:"Grad-CAM",purpose:"선택 class score가 마지막 convolution activation에 미치는 gradient로 주목 영역을 만듭니다.",code:"w=grad.mean((2,3))\ncam=relu((w*activ).sum(dim=1))",flow:"activ/grad [B,C,H,W] → cam [B,1,H,W]",watch:"softmax 확률이 아니라 선택 class logit을 backward합니다."}
  ];
  chapter.theory_guide=[
    {title:"증강과 정규화",concept:"증강은 입력 다양성을 늘리고, 정규화는 채널별 (x-mean)/std로 학습 수치 범위를 맞춥니다.",flow:"PIL → stochastic geometry → [0,1] Tensor → normalized Tensor",code_signal:"Random으로 시작하는 함수는 train_tfms에만 있습니다.",exam_clue:"이번 기출인 RandomCrop·RandomHorizontalFlip·ToTensor·Normalize 순서를 통째로 복원하세요."},
    {title:"Logits와 label",concept:"logits는 정규화되지 않은 class 점수이며 CrossEntropyLoss 내부에서 log-softmax를 처리합니다.",flow:"[B,10] float + [B] long → scalar loss",code_signal:"criterion(logits, labels) 앞에 별도 softmax가 없습니다.",exam_clue:"확률은 추론 표시용 predict_batch에서만 만듭니다."},
    {title:"Train·Eval mode",concept:"train은 BatchNorm 통계와 parameter gradient를 갱신하고 eval은 이를 고정해 일관된 예측을 만듭니다.",flow:"train: forward→backward→step; eval: forward only",code_signal:"@torch.no_grad와 model.eval이 함께 보입니다.",exam_clue:"평가 빈칸에는 zero_grad/backward/step이 없습니다."},
    {title:"Grad-CAM 가중치",concept:"class score의 spatial gradient를 평균해 channel 중요도를 만들고 activation을 가중합합니다.",flow:"score backward → grad mean → weighted activ → ReLU",code_signal:"mean dim=(2,3)은 높이·너비만 제거해 [B,C,1,1]을 유지합니다.",exam_clue:"channel dim=1을 sum한 뒤 cam shape는 [B,1,H,W]입니다."}
  ];
  const cells={
    "exam-v1-transform":`T.RandomCrop(32, padding=4),\nT.RandomHorizontalFlip(),\nT.ToTensor(),\nT.Normalize(CIFAR10_MEAN, CIFAR10_STD),`,
    "exam-v1-loader":`train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)\ntest_loader  = DataLoader(test_set, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True)`,
    "exam-v1-denorm":`mean = torch.tensor(CIFAR10_MEAN).view(1,3,1,1)\nstd  = torch.tensor(CIFAR10_STD).view(1,3,1,1)\nreturn x * std + mean`,
    "exam-v1-model":`model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)\nmodel.maxpool = nn.Identity()\nmodel.fc = nn.Linear(model.fc.in_features, num_classes)`,
    "exam-v1-accuracy":`preds = logits.argmax(dim=1)\nreturn (preds == targets).float().mean().item()`,
    "exam-v1-train":`logits = model(images)\nloss = criterion(logits, labels)\nscaler.scale(loss).backward()\nscaler.step(optimizer)\nscaler.update()`,
    "exam-v1-eval":`model.eval()\nlogits = model(images)\nloss = criterion(logits, labels)\ntotal_acc  += accuracy_top1(logits, labels) * bs`,
    "exam-v1-predict":`probs = F.softmax(logits, dim=1)\nconf, pred = probs.max(dim=1)\nreturn pred, conf, probs`,
    "exam-v1-confusion":`cm[int(t), int(p)] += 1\nper_class_acc = cm.diagonal().float() / torch.clamp(cm.sum(dim=1).float(), min=1.0)\nreturn cm, per_class_acc`,
    "exam-v1-gradcam":`score = logits[:, class_idx].sum()\nscore.backward(retain_graph=False)\nw = self.grad.mean(dim=(2,3), keepdim=True)\ncam = (w * self.activ).sum(dim=1, keepdim=True)\ncam = F.relu(cam)`
  };
  Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"};
  const make=d=>({...base,accepted_answers:[d.answer],...d});
  chapter.subjective=[
    make({id:"exam-v01-01",topic:"Train Transform",difficulty:"1 · 기출 확장",sourceId:"exam-v1-transform",prompt:"CIFAR-10 학습 이미지에 32×32 random crop·좌우 반전을 적용한 뒤 float CHW Tensor와 채널 정규화로 바꾸는 네 줄을 순서대로 작성하세요.",answer:cells["exam-v1-transform"],problem_context:`train_tfms = T.Compose([\n    ????\n    ????\n    ????\n    ????\n])`,explanation:"기하학적 증강은 PIL 상태에서 먼저 수행하고 ToTensor로 [C,H,W] float를 만든 뒤 Normalize가 채널별 표준화를 적용합니다.",tensor_flow:"PIL → augmented PIL → [3,32,32] float 0~1 → normalized float",code_signal:"train transform이라는 이름과 주석의 crop·flip·PIL→Tensor·정규화가 정확한 순서를 줍니다.",retry:"test_tfms에서 빠져야 하는 두 줄만 골라 보세요."}),
    make({id:"exam-v01-02",topic:"DataLoader 분리",difficulty:"2 · 데이터 구성",sourceId:"exam-v1-loader",prompt:"train은 매 epoch 순서를 섞고 test는 고정하며, 두 dataset을 같은 batch·worker·pinned memory 설정으로 로드하는 두 줄을 작성하세요.",answer:cells["exam-v1-loader"],problem_context:`train_loader = DataLoader(????)\ntest_loader  = DataLoader(????)`,explanation:"학습 순서는 섞어 mini-batch 편향을 줄이지만 평가는 재현 가능한 순서로 유지합니다. pin_memory는 GPU 전송 최적화에 사용됩니다.",tensor_flow:"Dataset samples → batches [B,3,32,32] and labels [B]",code_signal:"변수명 train/test와 바로 위 batch_size·num_workers가 모든 인자를 제공합니다.",retry:"두 줄에서 달라지는 dataset과 shuffle 값만 표시하세요."}),
    make({id:"exam-v01-03",topic:"역정규화",difficulty:"2 · Broadcasting",sourceId:"exam-v1-denorm",prompt:"정규화된 batch [B,3,H,W]를 표시 가능한 값으로 되돌리도록 mean/std를 broadcast shape로 만들고 역변환하는 세 줄을 작성하세요.",answer:cells["exam-v1-denorm"],problem_context:`def denorm(x):\n    mean = ????\n    std  = ????\n    return ????`,explanation:"Normalize의 역연산은 x*std+mean입니다. 채널 통계를 [1,3,1,1]로 만들어 batch와 공간축 전체에 broadcasting합니다.",tensor_flow:"[B,3,H,W] × [1,3,1,1] + [1,3,1,1]",code_signal:"주석 broadcast와 원래 Normalize(mean,std)가 역연산·shape를 결정합니다.",retry:"view(3)만 사용할 때와 [1,3,1,1]의 broadcasting 차이를 설명하세요."}),
    make({id:"exam-v01-04",topic:"CIFAR ResNet Stem",difficulty:"3 · 모델 구성",sourceId:"exam-v1-model",prompt:"ImageNet용 ResNet18을 RGB 32×32 CIFAR 입력과 num_classes 출력에 맞추도록 첫 convolution, pooling, classifier를 바꾸는 세 줄을 작성하세요.",answer:cells["exam-v1-model"],problem_context:`model = models.resnet18(weights=None)\nmodel.conv1 = ????\nmodel.maxpool = ????\nmodel.fc = ????`,explanation:"작은 이미지는 7×7 stride2와 maxpool로 너무 빨리 축소되므로 3×3 stride1 stem과 Identity를 사용합니다. fc의 기존 입력 차원을 보존하고 출력만 class 수로 바꿉니다.",tensor_flow:"[B,3,32,32] → stem [B,64,32,32] → stages → [B,num_classes]",code_signal:"입력 RGB=3, CIFAR 크기 32, 기존 fc.in_features와 num_classes가 constructor 인자를 제공합니다.",retry:"기존 ImageNet stem을 그대로 두면 초반 spatial size가 어떻게 줄어드는지 비교하세요."}),
    make({id:"exam-v01-05",topic:"Top-1 Accuracy",difficulty:"1 · Metric",sourceId:"exam-v1-accuracy",prompt:"logits [B,C]에서 class index [B]를 고르고 targets [B]와 비교한 평균 정확도를 Python scalar로 반환하는 두 줄을 작성하세요.",answer:cells["exam-v1-accuracy"],problem_context:`def accuracy_top1(logits, targets):\n    preds = ????\n    return ????`,explanation:"class 축 dim=1에서 최대 score의 index를 선택하고 boolean 비교를 float 0/1로 바꿔 평균낸 뒤 item으로 scalar를 얻습니다.",tensor_flow:"[B,C] → argmax [B] → bool [B] → scalar",code_signal:"logits shape의 두 번째 축이 class이고 함수 반환값이 누적 계산용 숫자입니다.",retry:"dim=0을 쓰면 결과 shape와 의미가 어떻게 달라지는지 확인하세요."}),
    make({id:"exam-v01-06",topic:"AMP 학습 Step",difficulty:"3 · 학습 연결",sourceId:"exam-v1-train",prompt:"autocast 문맥에서 logits와 분류 loss를 계산하고 GradScaler로 역전파·optimizer 갱신·scale 갱신을 수행하는 다섯 줄을 작성하세요.",answer:cells["exam-v1-train"],problem_context:`with torch.amp.autocast(device_type=device.type, enabled=torch.cuda.is_available()):\n    ????\n    ????\n????\n????\n????`,explanation:"forward와 loss는 autocast 안에서 계산합니다. scaler가 loss를 확대해 backward하고 optimizer step의 안전성을 확인한 뒤 다음 batch를 위해 scale을 조절합니다.",tensor_flow:"images [B,3,32,32] → logits [B,10] + labels [B] → loss → scaled gradients",code_signal:"이미 optimizer.zero_grad가 앞에 있으며 GradScaler 객체가 있으므로 일반 loss.backward/optimizer.step 대신 scaler 메서드를 씁니다.",retry:"일반 FP32 학습이라면 마지막 세 줄을 어떤 두 줄로 바꾸는지 작성하세요."}),
    make({id:"exam-v01-07",topic:"평가 Loop",difficulty:"2 · Train/Eval",sourceId:"exam-v1-eval",prompt:"gradient가 꺼진 evaluate 함수에서 모델 mode를 전환하고 logits·loss·batch accuracy 누적값을 계산하는 핵심 네 줄을 작성하세요.",answer:cells["exam-v1-eval"],problem_context:`@torch.no_grad()\ndef evaluate(model, loader, criterion):\n    ????\n    # inside batch loop\n    ????\n    ????\n    bs = images.size(0)\n    ????`,explanation:"eval mode로 BatchNorm 통계를 고정하고 forward와 metric만 수행합니다. batch 평균 accuracy에 bs를 곱해 샘플 수 가중 합을 만든 뒤 전체 n으로 나눕니다.",tensor_flow:"batch → logits [B,10] → loss/accuracy scalars → sample-weighted totals",code_signal:"decorator가 gradient를 막으므로 backward·step이 없고, 최종 total/n 때문에 bs 가중치가 필요합니다.",retry:"train_one_epoch와 비교해 평가에서 사라지는 세 연산을 적으세요."}),
    make({id:"exam-v01-08",topic:"확률·Confidence",difficulty:"2 · 추론",sourceId:"exam-v1-predict",prompt:"raw logits [B,C]를 class 확률로 바꾸고 각 sample의 최대 확률과 class index를 함께 반환하는 세 줄을 작성하세요.",answer:cells["exam-v1-predict"],problem_context:`logits = model(images)\n????\n????\n????`,explanation:"class 축에 softmax를 적용하면 각 행의 합이 1인 확률이 됩니다. max(dim=1)은 값 confidence와 index prediction을 함께 반환합니다.",tensor_flow:"[B,C] logits → [B,C] probs → conf [B], pred [B]",code_signal:"반환 변수 pred,conf,probs와 class 축 dim=1이 필요한 연산을 알려줍니다.",retry:"argmax만 쓰면 얻지 못하는 반환값이 무엇인지 설명하세요."}),
    make({id:"exam-v01-09",topic:"Confusion Matrix",difficulty:"3 · Metric 구현",sourceId:"exam-v1-confusion",prompt:"정답 t와 예측 p를 confusion matrix의 GT 행·Pred 열에 누적하고 class별 정확도를 계산해 반환하는 세 줄을 작성하세요.",answer:cells["exam-v1-confusion"],problem_context:`for t, p in zip(labels, preds):\n    ????\n????\n????`,explanation:"대각선은 정답과 예측이 같은 개수이고 각 행 합은 해당 실제 class 수입니다. 0개 class의 나눗셈을 막기 위해 분모를 최소 1로 clamp합니다.",tensor_flow:"labels,preds [N] → cm [C,C] → diagonal/row sums [C]",code_signal:"plot 축 label이 y=GT, x=Pred이고 per-class accuracy 정의가 diagonal/실제 class 수입니다.",retry:"행·열을 반대로 누적하면 어떤 metric 해석이 바뀌는지 설명하세요."}),
    make({id:"exam-v01-10",topic:"Grad-CAM",difficulty:"3 · 독립 구현",sourceId:"exam-v1-gradcam",prompt:"선택 class logit을 역전파하고 spatial gradient 평균을 channel 가중치로 사용해 양의 Grad-CAM [B,1,H,W]을 만드는 다섯 줄을 작성하세요.",answer:cells["exam-v1-gradcam"],problem_context:`????\n????\n????\n????\n????\ncam = cam - cam.min()`,explanation:"선택 class score의 gradient를 얻고 H,W 평균으로 channel별 중요도 [B,C,1,1]를 만듭니다. activation과 곱해 channel 합을 구한 뒤 ReLU로 양의 기여만 남깁니다.",tensor_flow:"logits [B,K] → score → grad/activ [B,C,H,W] → w [B,C,1,1] → cam [B,1,H,W]",code_signal:"forward/backward hook이 self.activ과 self.grad를 저장하며 주석 channel importance가 mean 축을 알려줍니다.",retry:"mean에서 dim=1을 사용하면 왜 channel 가중치가 사라지는지 확인하세요."})
  ];
  chapter.mcq=[
    {id:"exam-v01-m1",source_question_id:"exam-v01-01",topic:"Transform 순서",prompt:"학습용 CIFAR-10 transform의 올바른 순서는?",answer_index:2,explanation:"PIL 공간 증강 후 Tensor로 바꾸고 마지막에 채널 정규화합니다.",choices:[{text:"Normalize→ToTensor→Crop→Flip",why:"Normalize 입력 형식과 증강 순서가 틀립니다."},{text:"ToTensor→Normalize→Crop→Flip",why:"Tensor 이후 PIL용 공간 증강을 배치했습니다."},{text:"Crop→Flip→ToTensor→Normalize",why:"기출 코드의 올바른 순서입니다."},{text:"Flip→Normalize→ToTensor→Crop",why:"Normalize가 Tensor보다 앞입니다."},{text:"Crop→ToTensor→Normalize→Flip",why:"무작위 flip이 정규화 뒤에 있습니다."}]},
    {id:"exam-v01-m2",source_question_id:"exam-v01-04",topic:"CIFAR Stem",prompt:"32×32 CIFAR 입력에서 ImageNet ResNet stem을 바꾸는 핵심 이유는?",answer_index:0,explanation:"초기 downsampling을 줄여 작은 이미지의 공간 정보를 보존합니다.",choices:[{text:"초기 공간 해상도를 과도하게 줄이지 않기 위해",why:"3×3 stride1과 maxpool 제거 목적입니다."},{text:"RGB를 grayscale로 바꾸기 위해",why:"입력 채널은 여전히 3입니다."},{text:"클래스 수를 64로 늘리기 위해",why:"클래스 수는 fc가 담당합니다."},{text:"softmax를 추가하기 위해",why:"stem과 무관합니다."},{text:"label dtype을 바꾸기 위해",why:"데이터와 loss 설정입니다."}]},
    {id:"exam-v01-m3",source_question_id:"exam-v01-06",topic:"AMP 순서",prompt:"scaled loss 계산 후 올바른 AMP 갱신 순서는?",answer_index:4,explanation:"scale한 loss를 backward하고 scaler가 optimizer를 step한 뒤 scale을 갱신합니다.",choices:[{text:"update→step→backward",why:"역순입니다."},{text:"optimizer.step→loss.backward",why:"AMP scaler를 우회하고 순서도 틀립니다."},{text:"backward→update→step",why:"scale을 step 전에 바꿉니다."},{text:"step→zero_grad→update",why:"gradient 생성이 없습니다."},{text:"scale(loss).backward→scaler.step→scaler.update",why:"표준 GradScaler 순서입니다."}]},
    {id:"exam-v01-m4",source_question_id:"exam-v01-09",topic:"Class Accuracy",prompt:"confusion matrix가 cm[GT,Pred]일 때 class별 정확도의 분모는?",answer_index:1,explanation:"각 GT class의 전체 샘플 수는 해당 행 합입니다.",choices:[{text:"열 합 cm.sum(dim=0)",why:"예측된 class별 개수입니다."},{text:"행 합 cm.sum(dim=1)",why:"실제 class별 전체 개수입니다."},{text:"전체 합 cm.sum()",why:"전체 정확도 분모입니다."},{text:"대각선 합",why:"맞힌 수이며 분자입니다."},{text:"num_classes",why:"샘플 수가 아닙니다."}]},
    {id:"exam-v01-m5",source_question_id:"exam-v01-10",topic:"Grad-CAM 축",prompt:"gradient [B,C,H,W]에서 channel 가중치 [B,C,1,1]를 만드는 평균 축은?",answer_index:3,explanation:"공간 H,W만 평균내고 batch와 channel을 보존합니다.",choices:[{text:"dim=1",why:"channel을 제거합니다."},{text:"dim=(0,1)",why:"batch와 channel을 제거합니다."},{text:"dim=0",why:"batch만 평균냅니다."},{text:"dim=(2,3)",why:"공간축만 평균냅니다."},{text:"모든 축",why:"scalar 하나만 남습니다."}]}
  ];
  chapter.questionCount=chapter.subjective.length;
  chapter.exam_design={version:2,style:"원본 전체 코드 함수 문맥형",difficulty:["기출 호출 연결","Tensor·metric 연결","모델·Grad-CAM 독립 구현"],excluded:["URL·경로","고정 epoch·seed","시각화 제목 암기"]};
})();
