(() => {
  "use strict";
  const course=window.LLM_COURSE;
  const chapter=course.chapters.find(c=>c.file==="01_ResNet18_CIFAR10.ipynb");
  if(!chapter)return;
  chapter.notebook_goal="CIFAR-10의 학습·평가 transform을 구분하고 ResNet18을 32×32 입력에 맞춘 뒤 AMP 학습, 추론, metric, Grad-CAM까지 구현한다.";
  chapter.capability="[B,3,32,32] 입력과 [B,10] logits의 흐름을 추적하며 데이터 변형·모델 변경·학습·평가 코드를 독립적으로 완성할 수 있다.";
  chapter.summary="학습 이미지는 crop·flip으로 증강하고 train/test 모두 Tensor 변환과 정규화를 거칩니다. CIFAR용 ResNet stem과 10-class head를 학습한 뒤 accuracy·confusion matrix·Grad-CAM으로 결과를 해석합니다.";
  chapter.overview={title:"CIFAR-10 이미지가 분류와 해석 결과가 되는 과정",subtitle:"학습용 증강과 평가용 전처리를 구분하고, 작은 이미지에 맞춘 ResNet18의 logits를 label과 연결한다.",steps:[
    {label:"Transform",code:"Crop/Flip → Tensor → Normalize",flow:"PIL → [3,32,32] float"},
    {label:"DataLoader",code:"train shuffle / test fixed",flow:"samples → [B,3,32,32]"},
    {label:"ResNet18",code:"3×3 stem + 10-class fc",flow:"[B,3,32,32] → [B,10]"},
    {label:"Train",code:"CE + AMP backward/step",flow:"logits + [B] labels → weights"},
    {label:"Evaluate",code:"argmax / confusion / Grad-CAM",flow:"logits → class·evidence"}
  ],rules:["무작위 crop·flip은 train transform에만 넣는다.","ToTensor가 PIL을 float CHW로 바꾼 뒤 Normalize를 호출한다.","CrossEntropyLoss에는 softmax가 아닌 raw logits [B,C]와 long label [B]를 전달한다.","ResNet18 첫 Conv는 CIFAR 해상도에 맞춰 3×3 stride 1로 바꾸고 maxpool을 제거한다.","평가 함수는 eval·no_grad를 쓰며 backward와 optimizer step을 호출하지 않는다."]};
  chapter.key_points=[
    {title:"Train·Test transform",purpose:"학습에는 일반화를 위한 무작위 증강을, 평가에는 결정적인 변환만 적용합니다.",code:"train: RandomCrop → Flip → ToTensor → Normalize\ntest: ToTensor → Normalize",flow:"PIL → float [C,H,W]",watch:"Normalize가 ToTensor보다 먼저 오면 입력 형식이 맞지 않습니다."},
    {title:"CIFAR용 ResNet",purpose:"ImageNet용 큰 stem을 32×32 이미지에 맞추고 class head를 10개 출력으로 바꿉니다.",code:"Conv2d(3,64,3,1,1)\nmaxpool=Identity()\nfc=Linear(in_features,10)",flow:"[B,3,32,32] → [B,10]",watch:"fc 입력 차원은 기존 model.fc.in_features를 보존합니다."},
    {title:"AMP 학습",purpose:"mixed precision으로 forward·loss를 계산하고 scaler가 작은 gradient의 underflow를 줄입니다.",code:"autocast → scale(loss).backward → step → update",flow:"logits [B,10]+labels [B] → scalar → gradients",watch:"scaler.step과 scaler.update를 일반 optimizer.step 대신 사용합니다."},
    {title:"평가 Metric",purpose:"class 축의 최대 logit index를 정답과 비교해 전체·클래스별 정확도를 계산합니다.",code:"pred=logits.argmax(dim=1)\ncm[target,pred]+=1",flow:"[B,10] → [B] → confusion [10,10]",watch:"confusion matrix 행은 GT, 열은 prediction입니다."},
    {title:"Grad-CAM",purpose:"선택 class score가 마지막 convolution activation에 미치는 gradient로 주목 영역을 만듭니다.",code:"w=grad.mean((2,3))\ncam=relu((w*activ).sum(dim=1))",flow:"activ/grad [B,C,H,W] → cam [B,1,H,W]",watch:"softmax 확률이 아니라 선택 class logit을 backward합니다."}
  ];
  chapter.theory_guide=[
    {title:"증강과 정규화",concept:"증강은 입력 다양성을 늘리고, 정규화는 채널별 (x-mean)/std로 학습 수치 범위를 맞춥니다.",flow:"PIL → stochastic geometry → [0,1] Tensor → normalized Tensor",code_signal:"Random으로 시작하는 함수는 train_tfms에만 있습니다.",exam_clue:"이번 기출인 RandomCrop·RandomHorizontalFlip·ToTensor·Normalize 순서를 통째로 복원하세요."},
    {title:"Logits와 label",concept:"logits는 정규화되지 않은 class 점수이며 CrossEntropyLoss 내부에서 log-softmax를 처리합니다.",flow:"[B,10] float + [B] long → scalar loss",code_signal:"criterion(logits, labels) 앞에 별도 softmax가 없습니다.",exam_clue:"확률은 추론 표시용 predict_batch에서만 만듭니다."},
    {title:"Train·Eval mode",concept:"train은 BatchNorm 통계와 parameter gradient를 갱신하고 eval은 이를 고정해 일관된 예측을 만듭니다.",flow:"train: forward→backward→step; eval: forward only",code_signal:"@torch.no_grad와 model.eval이 함께 보입니다.",exam_clue:"평가 빈칸에는 zero_grad/backward/step이 없습니다."},
    {title:"Grad-CAM 가중치",concept:"class score의 spatial gradient를 평균해 channel 중요도를 만들고 activation을 가중합합니다.",flow:"score backward → grad mean → weighted activ → ReLU",code_signal:"mean dim=(2,3)은 높이·너비만 제거해 [B,C,1,1]을 유지합니다.",exam_clue:"channel dim=1을 sum한 뒤 cam shape는 [B,1,H,W]입니다."}
  ];
  const cells={
    "exam-v1-transform":`T.RandomCrop(32, padding=4),\nT.RandomHorizontalFlip(),\nT.ToTensor(),\nT.Normalize(CIFAR10_MEAN, CIFAR10_STD),`,
    "exam-v1-loader":`train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)\ntest_loader  = DataLoader(test_set, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True)`,
    "exam-v1-denorm":`mean = torch.tensor(CIFAR10_MEAN).view(1,3,1,1)\nstd  = torch.tensor(CIFAR10_STD).view(1,3,1,1)\nreturn x * std + mean`,
    "exam-v1-model":`model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)\nmodel.maxpool = nn.Identity()\nmodel.fc = nn.Linear(model.fc.in_features, num_classes)`,
    "exam-v1-accuracy":`preds = logits.argmax(dim=1)\nreturn (preds == targets).float().mean().item()`,
    "exam-v1-train":`logits = model(images)\nloss = criterion(logits, labels)\nscaler.scale(loss).backward()\nscaler.step(optimizer)\nscaler.update()`,
    "exam-v1-eval":`model.eval()\nlogits = model(images)\nloss = criterion(logits, labels)\ntotal_acc  += accuracy_top1(logits, labels) * bs`,
    "exam-v1-predict":`probs = F.softmax(logits, dim=1)\nconf, pred = probs.max(dim=1)\nreturn pred, conf, probs`,
    "exam-v1-confusion":`cm[int(t), int(p)] += 1\nper_class_acc = cm.diagonal().float() / torch.clamp(cm.sum(dim=1).float(), min=1.0)\nreturn cm, per_class_acc`,
    "exam-v1-gradcam":`score = logits[:, class_idx].sum()\nscore.backward(retain_graph=False)\nw = self.grad.mean(dim=(2,3), keepdim=True)\ncam = (w * self.activ).sum(dim=1, keepdim=True)\ncam = F.relu(cam)`
  };
  Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"};
  const make=d=>({...base,accepted_answers:[d.answer],...d});
  chapter.subjective=[
    make({id:"exam-v01-01",topic:"Train Transform",difficulty:"1 · 기출 확장",sourceId:"exam-v1-transform",prompt:"CIFAR-10 학습 이미지에 32×32 random crop·좌우 반전을 적용한 뒤 float CHW Tensor와 채널 정규화로 바꾸는 네 줄을 순서대로 작성하세요.",answer:cells["exam-v1-transform"],problem_context:`train_tfms = T.Compose([\n    ????\n    ????\n    ????\n    ????\n])`,explanation:"기하학적 증강은 PIL 상태에서 먼저 수행하고 ToTensor로 [C,H,W] float를 만든 뒤 Normalize가 채널별 표준화를 적용합니다.",tensor_flow:"PIL → augmented PIL → [3,32,32] float 0~1 → normalized float",code_signal:"train transform이라는 이름과 주석의 crop·flip·PIL→Tensor·정규화가 정확한 순서를 줍니다.",retry:"test_tfms에서 빠져야 하는 두 줄만 골라 보세요."}),
    make({id:"exam-v01-02",topic:"DataLoader 분리",difficulty:"2 · 데이터 구성",sourceId:"exam-v1-loader",prompt:"train은 매 epoch 순서를 섞고 test는 고정하며, 두 dataset을 같은 batch·worker·pinned memory 설정으로 로드하는 두 줄을 작성하세요.",answer:cells["exam-v1-loader"],problem_context:`train_loader = DataLoader(????)\ntest_loader  = DataLoader(????)`,explanation:"학습 순서는 섞어 mini-batch 편향을 줄이지만 평가는 재현 가능한 순서로 유지합니다. pin_memory는 GPU 전송 최적화에 사용됩니다.",tensor_flow:"Dataset samples → batches [B,3,32,32] and labels [B]",code_signal:"변수명 train/test와 바로 위 batch_size·num_workers가 모든 인자를 제공합니다.",retry:"두 줄에서 달라지는 dataset과 shuffle 값만 표시하세요."}),
    make({id:"exam-v01-03",topic:"역정규화",difficulty:"2 · Broadcasting",sourceId:"exam-v1-denorm",prompt:"정규화된 batch [B,3,H,W]를 표시 가능한 값으로 되돌리도록 mean/std를 broadcast shape로 만들고 역변환하는 세 줄을 작성하세요.",answer:cells["exam-v1-denorm"],problem_context:`def denorm(x):\n    mean = ????\n    std  = ????\n    return ????`,explanation:"Normalize의 역연산은 x*std+mean입니다. 채널 통계를 [1,3,1,1]로 만들어 batch와 공간축 전체에 broadcasting합니다.",tensor_flow:"[B,3,H,W] × [1,3,1,1] + [1,3,1,1]",code_signal:"주석 broadcast와 원래 Normalize(mean,std)가 역연산·shape를 결정합니다.",retry:"view(3)만 사용할 때와 [1,3,1,1]의 broadcasting 차이를 설명하세요."}),
    make({id:"exam-v01-04",topic:"CIFAR ResNet Stem",difficulty:"3 · 모델 구성",sourceId:"exam-v1-model",prompt:"ImageNet용 ResNet18을 RGB 32×32 CIFAR 입력과 num_classes 출력에 맞추도록 첫 convolution, pooling, classifier를 바꾸는 세 줄을 작성하세요.",answer:cells["exam-v1-model"],problem_context:`model = models.resnet18(weights=None)\nmodel.conv1 = ????\nmodel.maxpool = ????\nmodel.fc = ????`,explanation:"작은 이미지는 7×7 stride2와 maxpool로 너무 빨리 축소되므로 3×3 stride1 stem과 Identity를 사용합니다. fc의 기존 입력 차원을 보존하고 출력만 class 수로 바꿉니다.",tensor_flow:"[B,3,32,32] → stem [B,64,32,32] → stages → [B,num_classes]",code_signal:"입력 RGB=3, CIFAR 크기 32, 기존 fc.in_features와 num_classes가 constructor 인자를 제공합니다.",retry:"기존 ImageNet stem을 그대로 두면 초반 spatial size가 어떻게 줄어드는지 비교하세요."}),
    make({id:"exam-v01-05",topic:"Top-1 Accuracy",difficulty:"1 · Metric",sourceId:"exam-v1-accuracy",prompt:"logits [B,C]에서 class index [B]를 고르고 targets [B]와 비교한 평균 정확도를 Python scalar로 반환하는 두 줄을 작성하세요.",answer:cells["exam-v1-accuracy"],problem_context:`def accuracy_top1(logits, targets):\n    preds = ????\n    return ????`,explanation:"class 축 dim=1에서 최대 score의 index를 선택하고 boolean 비교를 float 0/1로 바꿔 평균낸 뒤 item으로 scalar를 얻습니다.",tensor_flow:"[B,C] → argmax [B] → bool [B] → scalar",code_signal:"logits shape의 두 번째 축이 class이고 함수 반환값이 누적 계산용 숫자입니다.",retry:"dim=0을 쓰면 결과 shape와 의미가 어떻게 달라지는지 확인하세요."}),
    make({id:"exam-v01-06",topic:"AMP 학습 Step",difficulty:"3 · 학습 연결",sourceId:"exam-v1-train",prompt:"autocast 문맥에서 logits와 분류 loss를 계산하고 GradScaler로 역전파·optimizer 갱신·scale 갱신을 수행하는 다섯 줄을 작성하세요.",answer:cells["exam-v1-train"],problem_context:`with torch.amp.autocast(device_type=device.type, enabled=torch.cuda.is_available()):\n    ????\n    ????\n????\n????\n????`,explanation:"forward와 loss는 autocast 안에서 계산합니다. scaler가 loss를 확대해 backward하고 optimizer step의 안전성을 확인한 뒤 다음 batch를 위해 scale을 조절합니다.",tensor_flow:"images [B,3,32,32] → logits [B,10] + labels [B] → loss → scaled gradients",code_signal:"이미 optimizer.zero_grad가 앞에 있으며 GradScaler 객체가 있으므로 일반 loss.backward/optimizer.step 대신 scaler 메서드를 씁니다.",retry:"일반 FP32 학습이라면 마지막 세 줄을 어떤 두 줄로 바꾸는지 작성하세요."}),
    make({id:"exam-v01-07",topic:"평가 Loop",difficulty:"2 · Train/Eval",sourceId:"exam-v1-eval",prompt:"gradient가 꺼진 evaluate 함수에서 모델 mode를 전환하고 logits·loss·batch accuracy 누적값을 계산하는 핵심 네 줄을 작성하세요.",answer:cells["exam-v1-eval"],problem_context:`@torch.no_grad()\ndef evaluate(model, loader, criterion):\n    ????\n    # inside batch loop\n    ????\n    ????\n    bs = images.size(0)\n    ????`,explanation:"eval mode로 BatchNorm 통계를 고정하고 forward와 metric만 수행합니다. batch 평균 accuracy에 bs를 곱해 샘플 수 가중 합을 만든 뒤 전체 n으로 나눕니다.",tensor_flow:"batch → logits [B,10] → loss/accuracy scalars → sample-weighted totals",code_signal:"decorator가 gradient를 막으므로 backward·step이 없고, 최종 total/n 때문에 bs 가중치가 필요합니다.",retry:"train_one_epoch와 비교해 평가에서 사라지는 세 연산을 적으세요."}),
    make({id:"exam-v01-08",topic:"확률·Confidence",difficulty:"2 · 추론",sourceId:"exam-v1-predict",prompt:"raw logits [B,C]를 class 확률로 바꾸고 각 sample의 최대 확률과 class index를 함께 반환하는 세 줄을 작성하세요.",answer:cells["exam-v1-predict"],problem_context:`logits = model(images)\n????\n????\n????`,explanation:"class 축에 softmax를 적용하면 각 행의 합이 1인 확률이 됩니다. max(dim=1)은 값 confidence와 index prediction을 함께 반환합니다.",tensor_flow:"[B,C] logits → [B,C] probs → conf [B], pred [B]",code_signal:"반환 변수 pred,conf,probs와 class 축 dim=1이 필요한 연산을 알려줍니다.",retry:"argmax만 쓰면 얻지 못하는 반환값이 무엇인지 설명하세요."}),
    make({id:"exam-v01-09",topic:"Confusion Matrix",difficulty:"3 · Metric 구현",sourceId:"exam-v1-confusion",prompt:"정답 t와 예측 p를 confusion matrix의 GT 행·Pred 열에 누적하고 class별 정확도를 계산해 반환하는 세 줄을 작성하세요.",answer:cells["exam-v1-confusion"],problem_context:`for t, p in zip(labels, preds):\n    ????\n????\n????`,explanation:"대각선은 정답과 예측이 같은 개수이고 각 행 합은 해당 실제 class 수입니다. 0개 class의 나눗셈을 막기 위해 분모를 최소 1로 clamp합니다.",tensor_flow:"labels,preds [N] → cm [C,C] → diagonal/row sums [C]",code_signal:"plot 축 label이 y=GT, x=Pred이고 per-class accuracy 정의가 diagonal/실제 class 수입니다.",retry:"행·열을 반대로 누적하면 어떤 metric 해석이 바뀌는지 설명하세요."}),
    make({id:"exam-v01-10",topic:"Grad-CAM",difficulty:"3 · 독립 구현",sourceId:"exam-v1-gradcam",prompt:"선택 class logit을 역전파하고 spatial gradient 평균을 channel 가중치로 사용해 양의 Grad-CAM [B,1,H,W]을 만드는 다섯 줄을 작성하세요.",answer:cells["exam-v1-gradcam"],problem_context:`????\n????\n????\n????\n????\ncam = cam - cam.min()`,explanation:"선택 class score의 gradient를 얻고 H,W 평균으로 channel별 중요도 [B,C,1,1]를 만듭니다. activation과 곱해 channel 합을 구한 뒤 ReLU로 양의 기여만 남깁니다.",tensor_flow:"logits [B,K] → score → grad/activ [B,C,H,W] → w [B,C,1,1] → cam [B,1,H,W]",code_signal:"forward/backward hook이 self.activ과 self.grad를 저장하며 주석 channel importance가 mean 축을 알려줍니다.",retry:"mean에서 dim=1을 사용하면 왜 channel 가중치가 사라지는지 확인하세요."})
  ];
  chapter.mcq=[
    {id:"exam-v01-m1",source_question_id:"exam-v01-01",topic:"Transform 순서",prompt:"학습용 CIFAR-10 transform의 올바른 순서는?",answer_index:2,explanation:"PIL 공간 증강 후 Tensor로 바꾸고 마지막에 채널 정규화합니다.",choices:[{text:"Normalize→ToTensor→Crop→Flip",why:"Normalize 입력 형식과 증강 순서가 틀립니다."},{text:"ToTensor→Normalize→Crop→Flip",why:"Tensor 이후 PIL용 공간 증강을 배치했습니다."},{text:"Crop→Flip→ToTensor→Normalize",why:"기출 코드의 올바른 순서입니다."},{text:"Flip→Normalize→ToTensor→Crop",why:"Normalize가 Tensor보다 앞입니다."},{text:"Crop→ToTensor→Normalize→Flip",why:"무작위 flip이 정규화 뒤에 있습니다."}]},
    {id:"exam-v01-m2",source_question_id:"exam-v01-04",topic:"CIFAR Stem",prompt:"32×32 CIFAR 입력에서 ImageNet ResNet stem을 바꾸는 핵심 이유는?",answer_index:0,explanation:"초기 downsampling을 줄여 작은 이미지의 공간 정보를 보존합니다.",choices:[{text:"초기 공간 해상도를 과도하게 줄이지 않기 위해",why:"3×3 stride1과 maxpool 제거 목적입니다."},{text:"RGB를 grayscale로 바꾸기 위해",why:"입력 채널은 여전히 3입니다."},{text:"클래스 수를 64로 늘리기 위해",why:"클래스 수는 fc가 담당합니다."},{text:"softmax를 추가하기 위해",why:"stem과 무관합니다."},{text:"label dtype을 바꾸기 위해",why:"데이터와 loss 설정입니다."}]},
    {id:"exam-v01-m3",source_question_id:"exam-v01-06",topic:"AMP 순서",prompt:"scaled loss 계산 후 올바른 AMP 갱신 순서는?",answer_index:4,explanation:"scale한 loss를 backward하고 scaler가 optimizer를 step한 뒤 scale을 갱신합니다.",choices:[{text:"update→step→backward",why:"역순입니다."},{text:"optimizer.step→loss.backward",why:"AMP scaler를 우회하고 순서도 틀립니다."},{text:"backward→update→step",why:"scale을 step 전에 바꿉니다."},{text:"step→zero_grad→update",why:"gradient 생성이 없습니다."},{text:"scale(loss).backward→scaler.step→scaler.update",why:"표준 GradScaler 순서입니다."}]},
    {id:"exam-v01-m4",source_question_id:"exam-v01-09",topic:"Class Accuracy",prompt:"confusion matrix가 cm[GT,Pred]일 때 class별 정확도의 분모는?",answer_index:1,explanation:"각 GT class의 전체 샘플 수는 해당 행 합입니다.",choices:[{text:"열 합 cm.sum(dim=0)",why:"예측된 class별 개수입니다."},{text:"행 합 cm.sum(dim=1)",why:"실제 class별 전체 개수입니다."},{text:"전체 합 cm.sum()",why:"전체 정확도 분모입니다."},{text:"대각선 합",why:"맞힌 수이며 분자입니다."},{text:"num_classes",why:"샘플 수가 아닙니다."}]},
    {id:"exam-v01-m5",source_question_id:"exam-v01-10",topic:"Grad-CAM 축",prompt:"gradient [B,C,H,W]에서 channel 가중치 [B,C,1,1]를 만드는 평균 축은?",answer_index:3,explanation:"공간 H,W만 평균내고 batch와 channel을 보존합니다.",choices:[{text:"dim=1",why:"channel을 제거합니다."},{text:"dim=(0,1)",why:"batch와 channel을 제거합니다."},{text:"dim=0",why:"batch만 평균냅니다."},{text:"dim=(2,3)",why:"공간축만 평균냅니다."},{text:"모든 축",why:"scalar 하나만 남습니다."}]}
  ];
  chapter.questionCount=chapter.subjective.length;
  chapter.exam_design={version:2,style:"원본 전체 코드 함수 문맥형",difficulty:["기출 호출 연결","Tensor·metric 연결","모델·Grad-CAM 독립 구현"],excluded:["URL·경로","고정 epoch·seed","시각화 제목 암기"]};
})();

(() => {
  "use strict";
  const course=window.LLM_COURSE,chapter=course.chapters.find(c=>c.file==="06_Stable_Diffusion_v1_4.ipynb");if(!chapter)return;
  chapter.notebook_goal="Diffusers StableDiffusionPipeline을 half precision GPU에 구성하고 prompt·seed·CFG·negative prompt·steps·size 조건을 통제해 생성 결과를 비교한다.";
  chapter.capability="동일 seed의 통제 실험을 설계하고 Pipeline 호출 인자를 목적에 맞게 조합해 재현 가능한 이미지 생성을 구현할 수 있다.";
  chapter.summary="Stable Diffusion 구성 요소를 하나의 pipeline으로 불러오고 prompt를 latent diffusion에 조건으로 넣습니다. 비교 실험에서는 seed를 고정한 채 CFG, negative prompt, inference steps, 크기 중 하나만 바꿉니다.";
  chapter.overview={title:"텍스트와 생성 조건이 최종 이미지가 되는 과정",subtitle:"pipeline이 tokenizer·text encoder·U-Net·scheduler·VAE를 연결하고 호출 인자가 생성 경로를 제어한다.",steps:[{label:"Load",code:"from_pretrained(dtype)→GPU",flow:"components → pipeline"},{label:"Condition",code:"prompt / negative_prompt",flow:"text → embeddings"},{label:"Denoise",code:"steps + guidance_scale",flow:"latent noise → latent image"},{label:"Decode",code:"VAE decode",flow:"latent → PIL image"},{label:"Compare",code:"fixed generator seed",flow:"one variable at a time"}],rules:["pipeline 결과는 객체이며 첫 이미지는 .images[0]에서 꺼낸다.","공정한 조건 비교는 매 반복마다 같은 seed의 generator를 다시 만든다.","guidance_scale은 prompt 조건을 따르는 강도를 조절하며 무조건 높을수록 좋은 값이 아니다.","negative_prompt는 피하고 싶은 개념의 조건으로 같은 pipeline 호출에 전달한다.","width와 height는 모델이 처리 가능한 배수 조건과 VRAM 사용량을 함께 고려한다."]};
  chapter.key_points=[{title:"Pipeline 구성",purpose:"여러 Stable Diffusion component를 단일 추론 API로 연결합니다.",code:"StableDiffusionPipeline.from_pretrained(model_id,torch_dtype=float16).to('cuda')",flow:"model files → GPU pipeline",watch:"float16은 GPU 메모리를 줄입니다."},{title:"기본 생성",purpose:"텍스트 조건과 CFG를 사용해 첫 PIL 이미지를 얻습니다.",code:"pipe(prompt,guidance_scale=g).images[0]",flow:"str → PipelineOutput → PIL",watch:"반환 객체에서 images list를 꺼냅니다."},{title:"재현 가능한 비교",purpose:"조건 하나의 효과만 비교하도록 random noise 시작점을 동일하게 고정합니다.",code:"generator=Generator('cuda').manual_seed(seed)",flow:"same initial latent noise",watch:"반복 밖 generator 하나를 계속 쓰면 상태가 진행되어 noise가 달라집니다."},{title:"Negative·Steps",purpose:"제외 조건과 denoising 반복 수를 pipeline 인자로 제어합니다.",code:"negative_prompt=...\nnum_inference_steps=...",flow:"conditions + scheduler steps → image",watch:"steps는 품질·시간 tradeoff입니다."},{title:"해상도·메모리",purpose:"width/height로 출력 latent 공간을 바꾸고 불필요한 CUDA cache를 정리합니다.",code:"pipe(...,width=w,height=h)\ntorch.cuda.empty_cache()",flow:"larger spatial latent → more VRAM",watch:"cache 정리는 살아 있는 Tensor 참조를 삭제하지 않습니다."}];
  chapter.theory_guide=[{title:"Pipeline components",concept:"StableDiffusionPipeline은 tokenizer, text encoder, denoising U-Net, scheduler, VAE를 순서대로 연결한 추론 묶음입니다.",flow:"prompt→text embedding; noise→U-Net loop; latent→VAE image",code_signal:"pipe.components.items()에서 내부 module을 확인합니다.",exam_clue:"개별 component를 직접 호출하는 문제가 아니라면 pipe(...)가 전체 흐름입니다."},{title:"Classifier-Free Guidance",concept:"CFG는 조건부와 무조건부 noise prediction 차이를 확대해 prompt 일치도를 조절합니다.",flow:"uncond + scale*(cond-uncond)",code_signal:"guidance_scale 인자가 조건 영향 강도입니다.",exam_clue:"비교 시 seed와 prompt를 고정하고 scale만 바꿉니다."},{title:"Generator state",concept:"seed는 초기 latent noise를 재현하지만 generator를 사용하면 내부 상태가 다음 호출마다 진행됩니다.",flow:"seed→generator→initial noise",code_signal:"loop 안에서 generator를 다시 생성합니다.",exam_clue:"동일 조건 비교라면 매 반복 같은 seed로 초기화합니다."},{title:"Inference steps",concept:"scheduler가 latent를 갱신하는 횟수로 대체로 늘리면 시간이 증가하고 일정 구간 이후 품질 개선은 작아집니다.",flow:"N denoising transitions",code_signal:"num_inference_steps가 pipeline 호출에 들어갑니다.",exam_clue:"고정 숫자 암기가 아니라 quality/time 조건에 맞게 선택합니다."}];
  const cells={
    "exam-v6-load":`pipe = StableDiffusionPipeline.from_pretrained(\n    model_id,\n    torch_dtype=torch.float16\n).to("cuda")`,
    "exam-v6-generate":`image = pipe(prompt, guidance_scale=guidance_scale).images[0]`,
    "exam-v6-compare":`generator = torch.manual_seed(50)\nresult = pipe(prompt, guidance_scale=scale, generator=generator).images[0]\nimages.append((scale, result))`,
    "exam-v6-seed":`generator = torch.Generator("cuda").manual_seed(seed)\nimage = pipe(prompt, generator=generator).images[0]\nimages.append((seed, image))`,
    "exam-v6-negative":`negative_prompt=neg_prompt,\ngenerator=generator,\nnum_inference_steps=30,\nguidance_scale=7.5`,
    "exam-v6-steps":`generator = torch.manual_seed(1004)\nimage = pipe(prompt, num_inference_steps=steps, generator=generator).images[0]`,
    "exam-v6-style":`full_prompt = f"{base_prompt}, {style}"\ngenerator = torch.manual_seed(1234)\nimg = pipe(full_prompt, generator=generator).images[0]`,
    "exam-v6-size":`generator = torch.manual_seed(10)\nimg = pipe(prompt, width=w, height=h, generator=generator).images[0]`,
    "exam-v6-memory":`gc.collect()\ntorch.cuda.empty_cache()`
  };Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 Pipeline 코드 기반 예상문제"},make=d=>({...base,accepted_answers:[d.answer],...d}),M=(id,topic,difficulty,sid,prompt,ctx,exp,flow,signal,retry)=>make({id,topic,difficulty,sourceId:sid,prompt,answer:cells[sid],problem_context:ctx,explanation:exp,tensor_flow:flow,code_signal:signal,retry});
  chapter.subjective=[
    M("exam-v06-01","Pipeline Load","2 · 구성","exam-v6-load","기존 model_id를 사용해 pretrained Stable Diffusion을 float16으로 불러오고 CUDA로 이동하는 네 줄을 작성하세요.",`????\n    ????\n    ????\n????`,`from_pretrained가 모든 component와 weight를 구성하고 float16으로 메모리를 줄인 뒤 pipeline 전체를 GPU로 이동합니다.`,`model_id → pipeline components/FP16 CUDA`,`import된 StableDiffusionPipeline, torch.float16, GPU 추론 문맥이 호출을 결정합니다.`,`CPU만 있는 환경에서는 dtype·device를 어떻게 바꿀지 말하세요.`),
    M("exam-v06-02","Pipeline Output","1 · 기본 호출","exam-v6-generate","prompt와 이미 정의된 CFG 값을 pipeline에 전달해 첫 번째 생성 이미지를 꺼내는 한 줄을 작성하세요.",`????`,`pipeline은 StableDiffusionPipelineOutput을 반환하므로 images list의 첫 요소를 선택합니다.`,`prompt str → output.images list → PIL image`,`변수 image 단수와 이어지는 화면 표시가 [0] 선택을 알려줍니다.`,`images[0]을 생략했을 때 반환 타입 차이를 확인하세요.`),
    M("exam-v06-03","CFG 통제 비교","2 · 실험 설계","exam-v6-compare","scale마다 같은 seed로 시작해 guidance_scale만 바꾼 이미지를 생성하고 scale과 함께 저장하는 세 줄을 작성하세요.",`for scale in scales:\n    ????\n    ????\n    ????`,`매 loop에서 generator를 같은 seed로 재설정하면 초기 noise가 같아 CFG 변화의 효과만 비교할 수 있습니다.`,`same prompt+noise; scale variable → comparable images`,`주석 동일한 조건 비교와 images에 (scale,result)를 저장하는 시각화 loop가 답을 줍니다.`,`generator 생성을 loop 밖으로 옮기면 왜 각 호출 noise가 달라지는지 설명하세요.`),
    M("exam-v06-04","Seed Variation","2 · 재현성","exam-v6-seed","각 seed로 CUDA generator를 만들고 같은 prompt를 생성해 seed와 이미지를 저장하는 세 줄을 작성하세요.",`for seed in seeds:\n    ????\n    ????\n    ????`,`torch.Generator의 manual_seed가 GPU random sequence를 결정해 같은 seed·조건에서 같은 초기 latent를 재현합니다.`,`seed int → CUDA generator → image`,`seeds loop와 결과 title이 generator 생성·tuple 저장을 지시합니다.`,`같은 seed와 prompt인데 결과가 달라질 수 있는 환경 요인을 하나 말하세요.`),
    M("exam-v06-05","Negative Prompt","3 · 조건 조합","exam-v6-negative","이미 시작된 pipe(prompt, ...) 호출 안에서 negative prompt, 고정 generator, denoising step, CFG를 지정하는 네 개의 키워드 인자를 작성하세요.",`image = pipe(\n    prompt,\n    ????,\n    ????,\n    ????,\n    ????\n).images[0]`,`positive prompt는 원하는 방향, negative prompt는 피할 방향의 text condition이며 generator·steps·CFG가 동일 호출의 생성 경로를 제어합니다.`,`two text conditions + latent seed + schedule → PIL`,`직전 변수 neg_prompt,generator와 주석 이미지 생성이 네 keyword 인자를 제공합니다.`,`negative_prompt를 빈 문자열로 넣은 경우와 생략한 경우의 목적을 비교하세요.`),
    M("exam-v06-06","Inference Steps 비교","2 · Scheduler","exam-v6-steps","각 step 조건을 같은 seed로 비교하도록 generator를 초기화하고 해당 denoising 횟수를 pipeline에 전달하는 두 줄을 작성하세요.",`for steps in steps_list:\n    ????\n    ????`,`초기 noise와 prompt를 고정하고 num_inference_steps만 바꿔 품질·시간 tradeoff를 비교합니다.`,`same latent → variable reverse steps → image`,`steps_list loop 변수와 비교 주석이 keyword 이름을 알려줍니다.`,`steps를 늘릴 때 계산 시간이 증가하는 이유를 reverse loop 관점에서 말하세요.`),
    M("exam-v06-07","Prompt Composition","2 · 조건 설계","exam-v6-style","base subject prompt와 style 문자열을 결합하고 같은 seed로 pipeline을 호출하는 세 줄을 작성하세요.",`for style in styles:\n    ????\n    ????\n    ????`,`대상 내용과 스타일 조건을 하나의 prompt로 합치고 initial noise를 고정해 style text의 영향만 비교합니다.`,`base text + style text → same-noise images`,`styles loop와 결과 label이 full_prompt와 고정 generator를 요구합니다.`,`문자열 결합 순서가 text encoder token truncation에 영향을 줄 수 있는 이유를 말하세요.`),
    M("exam-v06-08","Output Size","2 · 공간 조건","exam-v6-size","각 width·height 조합을 같은 seed로 생성하도록 generator와 pipeline 호출 두 줄을 작성하세요.",`for w, h in sizes:\n    ????\n    ????`,`width와 height는 latent spatial size를 바꾸며 같은 seed 고정으로 aspect ratio 변화의 효과를 비교합니다.`,`(w,h)+noise seed → PIL size (w,h)`,`loop tuple 이름과 주석 width와 height 파라미터가 keyword mapping을 알려줍니다.`,`해상도가 커질수록 VRAM이 증가하는 Tensor 축 두 개를 말하세요.`),
    M("exam-v06-09","GPU Memory 정리","1 · 자원 관리","exam-v6-memory","참조가 해제된 Python 객체를 수집하고 PyTorch가 예약한 CUDA cache를 비우는 두 줄을 작성하세요.",`def clean_memory():\n    ????\n    ????`,`garbage collection이 참조 없는 객체를 정리한 뒤 empty_cache가 PyTorch allocator의 사용하지 않는 예약 메모리를 반환합니다.`,`dead objects/cache → available memory`,`import gc와 함수 주석 1·2 단계가 두 호출 순서를 알려줍니다.`,`살아 있는 pipe를 유지한 채 empty_cache만 호출해도 model weight가 사라지지 않는 이유를 설명하세요.`)
  ];
  chapter.mcq=[
    {id:"exam-v06-m1",source_question_id:"exam-v06-02",topic:"반환값",prompt:"pipe(prompt)의 첫 PIL 이미지를 얻는 표현은?",answer_index:2,explanation:"PipelineOutput의 images list 첫 요소입니다.",choices:[{text:"pipe.prompt[0]",why:"prompt 속성이 아닙니다."},{text:"pipe(prompt)[0]",why:"출력 객체를 list처럼 직접 가정합니다."},{text:"pipe(prompt).images[0]",why:"정답입니다."},{text:"pipe.images(prompt)",why:"호출 순서가 틀립니다."},{text:"pipe(prompt).logits",why:"이미지 pipeline 출력입니다."}]},
    {id:"exam-v06-m2",source_question_id:"exam-v06-03",topic:"공정한 비교",prompt:"CFG 값만 비교하기 위한 가장 중요한 통제는?",answer_index:4,explanation:"prompt와 초기 random latent를 같게 유지해야 합니다.",choices:[{text:"width를 매번 변경",why:"추가 변수가 생깁니다."},{text:"negative prompt도 변경",why:"추가 text 조건이 달라집니다."},{text:"모델을 매번 다시 학습",why:"추론 비교에 불필요합니다."},{text:"seed를 매번 다르게",why:"초기 noise 차이가 섞입니다."},{text:"prompt와 seed를 고정",why:"scale만 독립 변수로 남습니다."}]},
    {id:"exam-v06-m3",source_question_id:"exam-v06-05",topic:"Negative Prompt",prompt:"negative_prompt의 역할은?",answer_index:1,explanation:"생성에서 피하고 싶은 개념 방향을 조건으로 제공합니다.",choices:[{text:"이미지를 음수 pixel로 변환",why:"text condition입니다."},{text:"원하지 않는 개념의 생성을 억제",why:"정답입니다."},{text:"random seed를 반전",why:"generator와 무관합니다."},{text:"denoising step 감소",why:"scheduler 인자가 아닙니다."},{text:"VAE를 비활성화",why:"decode component와 무관합니다."}]},
    {id:"exam-v06-m4",source_question_id:"exam-v06-06",topic:"Steps",prompt:"num_inference_steps를 늘릴 때 직접 증가하는 것은?",answer_index:0,explanation:"U-Net과 scheduler를 사용하는 denoising 반복 횟수입니다.",choices:[{text:"reverse denoising 반복",why:"정답입니다."},{text:"training epoch",why:"추론 인자입니다."},{text:"class 수",why:"분류가 아닙니다."},{text:"prompt token 수",why:"text 길이는 그대로입니다."},{text:"batch size",why:"별도 인자입니다."}]},
    {id:"exam-v06-m5",source_question_id:"exam-v06-01",topic:"FP16",prompt:"torch_dtype=torch.float16의 주된 추론 효과는?",answer_index:3,explanation:"component parameter·activation 메모리를 줄이고 지원 GPU에서 연산을 빠르게 할 수 있습니다.",choices:[{text:"출력 해상도 두 배",why:"width/height가 담당합니다."},{text:"prompt 길이 증가",why:"tokenizer 설정이 아닙니다."},{text:"항상 품질 향상",why:"정밀도 tradeoff가 있습니다."},{text:"VRAM 사용 감소",why:"정답입니다."},{text:"CPU 전용 전환",why:"코드는 CUDA로 이동합니다."}]}
  ];chapter.questionCount=chapter.subjective.length;chapter.exam_design={version:2,style:"Pipeline 조건 통제 구현형",difficulty:["기본 호출","재현 비교","조건 조합"],excluded:["model_id 문자열 암기","prompt 문장 암기","고정 seed·수치"]};
})();

(() => {
  "use strict";
  const course=window.LLM_COURSE,chapter=course.chapters.find(c=>c.file==="05_DDPM.ipynb");if(!chapter)return;
  chapter.notebook_goal="Forward diffusion으로 임의 timestep의 noisy image를 만들고 timestep-conditioned U-Net이 noise를 예측하도록 학습한 뒤 reverse process로 이미지를 생성한다.";
  chapter.capability="DDPM 계수와 image Tensor shape를 근거로 q_sample·noise prediction loss·p_sample·reverse loop를 구현할 수 있다.";
  chapter.summary="원본 x0에 timestep별 alpha 계수와 Gaussian noise를 섞어 xt를 만들고 U-Net이 실제 noise를 맞히게 학습합니다. 생성 시 pure noise에서 시작해 T−1부터 0까지 예측 noise를 제거합니다.";
  chapter.overview={title:"원본 이미지가 노이즈가 되고 다시 생성 이미지가 되는 과정",subtitle:"같은 U-Net이 timestep을 조건으로 섞인 noise를 예측하며 forward 공식과 reverse 공식이 연결된다.",steps:[{label:"Schedule",code:"βt→αt→ᾱt",flow:"T scalar coefficients"},{label:"Forward",code:"xt=√ᾱt x0+√(1−ᾱt)ε",flow:"x0 + noise → xt"},{label:"Predict",code:"εθ(xt,t)",flow:"U-Net → predicted noise"},{label:"Learn",code:"loss(ε,εθ)",flow:"scalar → weights"},{label:"Reverse",code:"xT→...→x0",flow:"iterative denoising"}],rules:["t는 batch의 각 이미지마다 하나인 long Tensor [B]다.","1D schedule 계수는 extract로 [B,1,1,1]로 reshape해 image에 broadcast한다.","학습 target은 깨끗한 이미지가 아니라 실제로 섞은 Gaussian noise다.","t=0 reverse step에서는 posterior noise를 더하지 않고 model_mean을 반환한다.","샘플링은 timesteps−1부터 0까지 역순으로 반복한다."]};
  chapter.key_points=[{title:"Noise schedule",purpose:"t가 증가할수록 원본 신호를 줄이고 noise 비중을 늘리는 계수를 미리 계산합니다.",code:"alpha=1-beta\nalpha_bar=cumprod(alpha)",flow:"[T] β → [T] α,ᾱ",watch:"alpha_bar는 누적 곱입니다."},{title:"Forward sample",purpose:"반복 없이 x0에서 임의 xt를 직접 만듭니다.",code:"sqrt(alpha_bar_t)*x0 + sqrt(1-alpha_bar_t)*noise",flow:"three [B,C,H,W] → xt",watch:"두 계수의 제곱 합이 1이 되는 구조입니다."},{title:"Noise objective",purpose:"U-Net이 xt와 t에서 섞인 noise ε를 예측합니다.",code:"pred=unet(x_noisy,t)\nloss(noise,pred)",flow:"[B,C,H,W]+[B] → [B,C,H,W] → scalar",watch:"target으로 x0를 넣지 않습니다."},{title:"Reverse step",purpose:"예측 noise를 현재 xt에서 제거해 x(t-1)의 평균을 구합니다.",code:"1/√αt·(xt−βt εθ/√(1−ᾱt))",flow:"xt → model_mean → x(t-1)",watch:"t>0에서만 posterior 표준편차 noise를 더합니다."},{title:"Timestep U-Net",purpose:"같은 U-Net이 noise 수준별 denoising을 하도록 t embedding을 feature scale·shift에 주입합니다.",code:"time→sin/cos→MLP→scale,shift",flow:"[B] → [B,time_dim] → feature modulation",watch:"time embedding을 [B,C,1,1]로 바꿉니다."}];
  chapter.theory_guide=[{title:"α와 ᾱ",concept:"αt=1−βt는 한 step 신호 보존율, ᾱt는 0부터 t까지 누적 신호 보존율입니다.",flow:"β schedule → α → cumulative ᾱ",code_signal:"torch.cumprod(alphas,dim=0)가 핵심입니다.",exam_clue:"q_sample은 αt가 아니라 ᾱt의 제곱근을 사용합니다."},{title:"Noise prediction",concept:"모델이 ε를 예측하면 알려진 schedule 공식으로 xt에서 x(t−1)의 평균을 계산할 수 있습니다.",flow:"xt,t → εθ → model_mean",code_signal:"p_losses의 target noise와 p_sample의 model(x,t)가 같은 의미입니다.",exam_clue:"loss 인자 순서는 실제 noise, predicted_noise입니다."},{title:"Coefficient broadcasting",concept:"batch별 timestep에서 고른 scalar를 모든 channel·pixel에 적용하려고 뒤에 singleton 축을 붙입니다.",flow:"schedule [T]+t [B] → [B,1,1,1]",code_signal:"reshape에서 len(x_shape)-1개의 1을 만듭니다.",exam_clue:"gather는 CPU schedule에서 t.cpu()로 index합니다."},{title:"Reverse stochasticity",concept:"마지막 t=0에서는 최종 평균을 그대로 쓰고 이전 step에서는 posterior variance만큼 noise를 더해 분포를 샘플링합니다.",flow:"t>0: mean+σz; t=0: mean",code_signal:"if t_index==0 분기가 noise 생성보다 앞입니다.",exam_clue:"variance가 아니라 sqrt(variance)를 noise에 곱합니다."}];
  const cells={
    "exam-v5-time":`freq = math.log(10000) / (half_dim - 1)\nfreq = torch.exp(torch.arange(half_dim, device=device) * -freq)\nargs = time[:, None].float() * freq[None, :]\nemb = torch.cat([args.sin(), args.cos()], dim=-1)`,
    "exam-v5-film":`time_emb = self.mlp(time_emb)\ntime_emb = rearrange(time_emb, "b c -> b c 1 1")\nscale_shift = time_emb.chunk(2, dim=1)\nx = x * (scale + 1) + shift`,
    "exam-v5-linearattn":`q = q.softmax(dim=-2)\nk = k.softmax(dim=-1)\nq = q * self.scale\ncontext = torch.einsum("b h d n, b h e n -> b h d e", k, v)\nout = torch.einsum("b h d e, b h d n -> b h e n", context, q)`,
    "exam-v5-schedule":`alphas = 1.0 - betas\nalphas_cumprod = torch.cumprod(alphas, dim=0)\nalphas_cumprod_prev = F.pad(alphas_cumprod[:-1], (1, 0), value=1.0)\nsqrt_alphas_cumprod = torch.sqrt(alphas_cumprod)\nsqrt_one_minus_alphas_cumprod = torch.sqrt(1.0 - alphas_cumprod)`,
    "exam-v5-extract":`batch_size = t.shape[0]\nout = a.gather(-1, t.cpu())\nreturn out.reshape(batch_size, *((1,) * (len(x_shape) - 1))).to(t.device)`,
    "exam-v5-forward":`noise = torch.randn_like(x_start)\nsqrt_alphas_cumprod_t = extract(sqrt_alphas_cumprod, t, x_start.shape)\nsqrt_one_minus_alphas_cumprod_t = extract(sqrt_one_minus_alphas_cumprod, t, x_start.shape)\nreturn sqrt_alphas_cumprod_t * x_start + sqrt_one_minus_alphas_cumprod_t * noise`,
    "exam-v5-loss":`noise = torch.randn_like(x_start)\nx_noisy = q_sample(x_start=x_start, t=t, noise=noise)\npredicted_noise = denoise_model(x_noisy, t)\nloss = F.smooth_l1_loss(noise, predicted_noise)`,
    "exam-v5-reverse":`model_mean = sqrt_recip_alphas_t * (\n    x - betas_t * model(x, t) / sqrt_one_minus_alphas_cumprod_t\n)\nposterior_variance_t = extract(posterior_variance, t, x.shape)\nreturn model_mean + torch.sqrt(posterior_variance_t) * noise`,
    "exam-v5-loop":`img = torch.randn(shape, device=device)\nfor i in tqdm(reversed(range(0, timesteps)), desc="sampling loop time step", total=timesteps):\n    img = p_sample(model, img, torch.full((b,), i, device=device, dtype=torch.long), i)\n    imgs.append(img.cpu().numpy())\nreturn imgs`,
    "exam-v5-train":`optimizer.zero_grad()\nt = torch.randint(0, timesteps, (b,), device=device, dtype=torch.long)\nloss = p_losses(model, batch_imgs, t, loss_type="huber")\nloss.backward()\noptimizer.step()`
  };Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"},make=d=>({...base,accepted_answers:[d.answer],...d});
  const meta=(id,topic,difficulty,sourceId,prompt,problem_context,explanation,tensor_flow,code_signal,retry)=>make({id,topic,difficulty,sourceId,prompt,answer:cells[sourceId],problem_context,explanation,tensor_flow,code_signal,retry});
  chapter.subjective=[
    meta("exam-v05-01","Sinusoidal Time Embedding","2 · Conditioning","exam-v5-time","timestep [B]를 서로 다른 주기의 sin/cos vector [B,dim]로 만드는 핵심 네 줄을 작성하세요.",`half_dim = self.dim // 2\n????\n????\n????\n????\nreturn emb`,"서로 지수적으로 다른 frequency를 만들고 time과 outer-product처럼 broadcast한 뒤 sin·cos를 feature 축에 연결합니다.","time [B] × freq [D/2] → args [B,D/2] → embedding [B,D]","half_dim과 주석 (batch,1)*(1,half_dim)이 reshape와 concat 축을 알려줍니다.","time[:,None]과 freq[None,:] 각각의 shape를 먼저 쓰세요."),
    meta("exam-v05-02","Time Scale·Shift","3 · Feature modulation","exam-v5-film","time embedding을 channel별 scale·shift로 바꾸고 image feature [B,C,H,W]에 affine modulation하는 네 줄을 작성하세요.",`if exists(self.mlp) and exists(time_emb):\n    ????\n    ????\n    ????\n# inside Block after scale, shift unpack\n????`,"MLP가 2C 값을 만들고 공간 singleton 축을 붙인 뒤 channel로 반씩 나눕니다. scale은 identity를 보존하도록 1을 더하고 shift를 더합니다.","[B,timeD] → [B,2C] → two [B,C,1,1] → [B,C,H,W]","Linear out_features=dim_out*2와 scale_shift unpack가 chunk 축과 affine 식을 지시합니다.","scale=0,shift=0이면 출력이 x인지 확인하세요."),
    meta("exam-v05-03","Linear Attention","3 · 효율 연산","exam-v5-linearattn","Q는 feature축, K는 token축으로 정규화하고 K·V context를 먼저 계산한 뒤 Q에 적용하는 다섯 줄을 작성하세요.",`????\n????\n????\n????\n????`,"K와 V를 먼저 결합해 N×N 행렬 없이 d×d context를 만들고 이를 Q의 각 token에 적용합니다.","q,k,v [B,H,d,N] → context [B,H,d,d] → out [B,H,d,N]","주석의 feature dim=-2, pixel dim=-1과 두 einsum 출력 shape가 식을 결정합니다.","표준 attention과 달리 N×N Tensor가 생성되지 않는 위치를 표시하세요."),
    meta("exam-v05-04","Diffusion 계수","2 · Schedule","exam-v5-schedule","beta [T]에서 alpha·누적 alpha와 forward noise 계수 두 개를 계산하는 다섯 줄을 작성하세요.",`????\n????\n????\n????\n????`,"alpha는 한 step 보존율, alpha_cumprod는 x0에서 xt까지 누적 보존율입니다. forward 공식에 쓰는 두 계수는 ᾱ와 1−ᾱ의 제곱근입니다.","betas [T] → alphas/alpha_bar [T] → two sqrt schedules [T]","주석 alpha=1-beta, cumprod와 q_sample 공식이 필요한 schedule을 알려줍니다.","t=0 이전 누적값을 1로 두는 pad의 의미를 설명하세요."),
    meta("exam-v05-05","Schedule Extract","2 · Broadcasting","exam-v5-extract","schedule [T]에서 batch timestep [B] 값을 고르고 image rank에 맞는 [B,1,1,1]로 변환하는 세 줄을 작성하세요.",`def extract(a,t,x_shape):\n    ????\n    ????\n    ????`,"gather로 이미지별 t의 scalar를 고르고 image의 batch 이외 축 수만큼 1을 붙여 모든 channel·pixel에 broadcast합니다.","a [T]+t [B] → out [B] → [B,1,1,1]","반환 shape docstring과 len(x_shape)-1이 singleton 개수를 정합니다.","x_shape가 [B,C,H,W]일 때 생성되는 tuple을 적으세요."),
    meta("exam-v05-06","Forward Diffusion","3 · q_sample","exam-v5-forward","noise가 없으면 생성하고 t별 두 계수를 추출해 x0와 noise를 합성한 xt를 반환하는 네 줄을 작성하세요.",`if noise is None:\n    ????\n????\n????\n????`,"ᾱ가 원본 신호 비중, 1−ᾱ가 noise 비중이며 각각 제곱근을 곱해 같은 shape로 합칩니다.","x0/noise [B,C,H,W]+t [B] → coefficients [B,1,1,1] → xt","함수 docstring의 수식이 변수명과 사칙연산을 그대로 제공합니다.","t가 커질수록 두 계수 중 어느 것이 커지는지 말하세요."),
    meta("exam-v05-07","Noise Prediction Loss","3 · 학습 목표","exam-v5-loss","실제 noise로 xt를 만들고 U-Net의 noise 예측과 Huber loss를 계산하는 네 줄을 작성하세요.",`if noise is None:\n    ????\n????\n????\n# loss_type == huber\n????`,"동일한 noise를 forward corruption과 target에 사용해야 모델이 제거해야 할 ε를 정확히 학습합니다.","x0+noise+t → xt → predicted_noise same shape → scalar","p_losses 주석 Ground Truth Noise와 denoise_model 입력 x_noisy,t가 target을 알려줍니다.","target을 x_start로 바꾸면 학습 목표가 어떻게 달라지는지 설명하세요."),
    meta("exam-v05-08","Reverse DDPM Step","3 · p_sample","exam-v5-reverse","예측 noise로 x(t−1)의 평균을 만들고 t>0에서 posterior 표준편차 noise를 더하는 다섯 줄을 작성하세요.",`????\n    ????\n????\n# t_index > 0, noise already sampled\n????\n????`,"Equation 11 평균은 xt에서 예측 noise를 schedule 비율로 제거하고 1/√αt로 조정합니다. 확률적 샘플링에는 sqrt(posterior variance)·noise를 더합니다.","xt → model_mean [B,C,H,W] → x(t-1)","t_index==0 분기와 주석 평균+표준편차*noise가 마지막 식을 결정합니다.","variance 자체가 아니라 sqrt를 곱하는 이유를 표준편차 관점에서 말하세요."),
    meta("exam-v05-09","Reverse Loop","3 · Generation","exam-v5-loop","pure Gaussian noise에서 시작해 T−1부터 0까지 batch timestep Tensor로 p_sample을 호출하고 모든 단계를 저장하는 다섯 줄을 작성하세요.",`????\nimgs = []\n????\n    ????\n    ????\n????`,"생성은 가장 noisy한 xT에서 시작해 시간을 역순으로 진행합니다. 각 step의 모든 batch 원소에 동일한 i를 long Tensor로 전달합니다.","random [B,C,H,W] → T reverse states → list of NumPy batches","함수명 p_sample_loop와 reversed(range(...)), torch.full 주석이 loop 방향·t shape를 알려줍니다.","range를 정방향으로 쓰면 학습된 reverse transition과 맞지 않는 이유를 설명하세요."),
    meta("exam-v05-10","DDPM 학습 Step","2 · Optimization","exam-v5-train","batch에서 image마다 무작위 timestep을 뽑고 Huber noise loss로 parameter를 갱신하는 다섯 줄을 작성하세요.",`????\nbatch_imgs = batch["pixel_values"].to(device)\nb = batch_imgs.shape[0]\n????\n????\n????\n????`,"각 이미지가 서로 다른 noise 수준을 학습하도록 [B] timestep을 uniform sampling합니다. p_losses가 noise 생성·forward·prediction을 묶고 표준 optimizer 순서로 갱신합니다.","images [B,1,28,28]+t [B] → scalar → gradients","timesteps 범위와 batch size b, loss_type 주석이 randint와 호출을 결정합니다.","t Tensor dtype이 long이어야 schedule gather가 가능한 이유를 말하세요.")
  ];
  chapter.mcq=[
    {id:"exam-v05-m1",source_question_id:"exam-v05-06",topic:"Forward 공식",prompt:"xt를 직접 만드는 올바른 식은?",answer_index:1,explanation:"원본과 noise에 누적 alpha 계수의 제곱근을 곱합니다.",choices:[{text:"alpha_t*x0+beta_t*noise",why:"누적 계수와 제곱근이 없습니다."},{text:"sqrt(alpha_bar_t)*x0+sqrt(1-alpha_bar_t)*noise",why:"정답입니다."},{text:"x0-noise",why:"schedule이 없습니다."},{text:"sqrt(beta_t)*x0+alpha_t*noise",why:"계수 역할이 틀립니다."},{text:"softmax(x0+noise)",why:"diffusion 식이 아닙니다."}]},
    {id:"exam-v05-m2",source_question_id:"exam-v05-07",topic:"학습 target",prompt:"DDPM noise-prediction U-Net의 loss target은?",answer_index:3,explanation:"xt 생성에 실제 사용한 Gaussian noise입니다.",choices:[{text:"timestep t",why:"조건 입력입니다."},{text:"clean image x0",why:"이 구현의 직접 target이 아닙니다."},{text:"previous image x(t-1)",why:"학습 셀에서 만들지 않습니다."},{text:"sampled noise epsilon",why:"모델이 예측할 정답입니다."},{text:"beta schedule",why:"계수입니다."}]},
    {id:"exam-v05-m3",source_question_id:"exam-v05-05",topic:"Broadcast shape",prompt:"image [B,C,H,W]에 곱할 batch별 coefficient shape는?",answer_index:0,explanation:"batch만 다르고 모든 channel·pixel에 같은 값을 적용합니다.",choices:[{text:"[B,1,1,1]",why:"정답입니다."},{text:"[B]",why:"마지막 W축과 잘못 맞을 수 있습니다."},{text:"[1,B,1,1]",why:"B가 channel 위치입니다."},{text:"[B,C,H,W]만 가능",why:"broadcasting을 사용할 수 있습니다."},{text:"[T,1,1,1]",why:"전체 schedule이며 batch t를 고르지 않았습니다."}]},
    {id:"exam-v05-m4",source_question_id:"exam-v05-08",topic:"마지막 reverse step",prompt:"t_index==0에서 p_sample이 반환해야 하는 것은?",answer_index:4,explanation:"최종 step에는 추가 noise 없이 평균을 반환합니다.",choices:[{text:"새 Gaussian noise",why:"생성이 다시 초기화됩니다."},{text:"posterior variance",why:"이미지가 아닙니다."},{text:"model(x,t)만",why:"예측 noise입니다."},{text:"mean+sqrt(var)*noise",why:"최종 결과에 noise가 남습니다."},{text:"model_mean",why:"정답입니다."}]},
    {id:"exam-v05-m5",source_question_id:"exam-v05-09",topic:"Sampling 방향",prompt:"reverse generation loop의 timestep 순서는?",answer_index:2,explanation:"xT에서 x0로 역순 진행합니다.",choices:[{text:"0부터 T-1",why:"forward 방향입니다."},{text:"무작위 순서",why:"연속 transition이 깨집니다."},{text:"T-1부터 0",why:"정답입니다."},{text:"항상 t=0",why:"단계별 denoising이 없습니다."},{text:"짝수 t만",why:"학습된 모든 transition을 사용하지 않습니다."}]}
  ];chapter.questionCount=chapter.subjective.length;chapter.exam_design={version:2,style:"diffusion 수식·Tensor 문맥형",difficulty:["schedule·shape","forward objective","reverse process 독립 구현"],excluded:["이미지 URL","저장 경로","고정 epoch·샘플 수"]};
})();

(() => {
  "use strict";
  const course=window.LLM_COURSE,chapter=course.chapters.find(c=>c.file==="04_Unet.ipynb");if(!chapter)return;
  chapter.notebook_goal="Binary segmentation용 mask dataset과 U-Net encoder·decoder·skip connection을 구성하고 pixelwise logits를 학습·시각화한다.";
  chapter.capability="[B,1,H,W] 입력·mask의 공간 shape를 유지하며 Down·Up·skip concat·binary loss 코드를 독립적으로 완성할 수 있다.";
  chapter.summary="U-Net은 Down path에서 해상도를 줄이며 문맥 특징을 만들고 Up path에서 해상도를 복원하면서 같은 크기의 encoder feature를 channel 축으로 연결해 정확한 위치 정보를 되살립니다.";
  chapter.overview={title:"이미지가 같은 크기의 pixel mask로 복원되는 과정",subtitle:"encoder의 문맥과 skip의 위치 정보를 decoder에서 결합해 각 pixel의 binary logit을 만든다.",steps:[{label:"Dataset",code:"image + binary mask",flow:"[H,W] → [1,H,W]"},{label:"Encoder",code:"DoubleConv + MaxPool",flow:"H,W↓ · C↑"},{label:"Bottleneck",code:"deep context",flow:"[B,1024,H/16,W/16]"},{label:"Decoder",code:"Upsample + concat(skip)",flow:"H,W↑ · C↓"},{label:"Mask",code:"1×1 Conv + BCE logits",flow:"[B,1,H,W]"}],rules:["segmentation target은 이미지당 class 하나가 아니라 pixel마다 정답을 갖는다.","padding=1인 3×3 Conv는 H,W를 유지하고 MaxPool2d(2)는 절반으로 줄인다.","skip connection은 공간 크기를 맞춘 후 channel 축 dim=1로 concat한다.","binary segmentation head는 1채널 raw logits를 내고 BCEWithLogitsLoss가 sigmoid를 내부 처리한다.","추론에서만 sigmoid와 threshold를 적용해 0/1 mask를 만든다."]};
  chapter.key_points=[{title:"Mask 데이터",purpose:"입력 이미지와 동일 공간 크기의 binary target을 만듭니다.",code:"mask[distance<=radius]=1\nexpand_dims(axis=0)",flow:"[H,W] → image/mask [1,H,W]",watch:"channel 축을 앞에 추가합니다."},{title:"DoubleConv·Down",purpose:"공간 크기를 유지하며 특징을 만들고 pooling으로 다음 scale로 이동합니다.",code:"(Conv3×3,pad1→ReLU)×2\nMaxPool2d(2)",flow:"[B,C,H,W] → [B,Cout,H/2,W/2]",watch:"pool이 Conv보다 먼저 적용됩니다."},{title:"Up·Skip",purpose:"decoder feature를 skip과 같은 해상도로 키워 위치 정보를 결합합니다.",code:"up(x1)→pad→cat([x2,x1],dim=1)→DoubleConv",flow:"[B,Cd,H/2,W/2]+[B,Cs,H,W] → [B,Cout,H,W]",watch:"x2가 encoder skip, x1이 decoder입니다."},{title:"Output head",purpose:"마지막 1×1 Conv가 feature channel을 class logit channel로 투영합니다.",code:"Conv2d(64,n_classes,kernel_size=1)",flow:"[B,64,H,W] → [B,1,H,W]",watch:"binary라도 softmax용 2채널이 아니라 1 logit을 사용합니다."},{title:"Loss·Prediction",purpose:"pixel별 binary logits와 mask를 학습하고 확률 threshold로 mask를 만듭니다.",code:"BCEWithLogitsLoss(logits,masks)\nsigmoid(logits)>0.5",flow:"[B,1,H,W] → scalar / binary mask",watch:"학습 전에 sigmoid를 중복 적용하지 않습니다."}];
  chapter.theory_guide=[{title:"Contracting path",concept:"pooling은 receptive field를 넓혀 문맥을 모으지만 세밀한 위치 정보는 줄입니다.",flow:"H,W /2 each stage; channels increase",code_signal:"down1~down4 출력 x1~x5를 모두 보관합니다.",exam_clue:"보관된 x1~x4는 나중에 역순으로 skip에 사용됩니다."},{title:"Skip connection",concept:"decoder의 거친 문맥 feature와 encoder의 고해상도 feature를 channel 방향으로 붙입니다.",flow:"same H,W; channels add",code_signal:"torch.cat([x2,x1],dim=1) 뒤 DoubleConv in_channels는 합계입니다.",exam_clue:"dim=0은 batch가 늘어나므로 틀립니다."},{title:"Padding alignment",concept:"홀수 크기에서 upsample 결과와 skip의 H,W가 다를 수 있어 차이를 좌우·상하로 나눠 pad합니다.",flow:"diff_x,diff_y → [left,right,top,bottom]",code_signal:"F.pad 인자 순서가 W축 쌍, H축 쌍입니다.",exam_clue:"차이의 절반과 나머지를 양쪽에 배분합니다."},{title:"Binary logits",concept:"BCEWithLogitsLoss는 안정적인 sigmoid+BCE 결합이므로 모델은 확률이 아닌 logit을 반환합니다.",flow:"logits + {0,1} mask → scalar",code_signal:"visualize_predictions에서만 torch.sigmoid가 등장합니다.",exam_clue:"criterion 전에는 sigmoid를 넣지 않습니다."}];
  const cells={
    "exam-v4-mask":`dist_from_center = np.sqrt((x - center_x) ** 2 + (y - center_y) ** 2)\nmask[dist_from_center <= radius] = 1.0\nimg = mask + 0.2 * np.random.randn(self.image_size, self.image_size).astype(np.float32)\nimg = np.clip(img, 0.0, 1.0)`,
    "exam-v4-tensor":`img = np.expand_dims(img, axis=0)\nmask = np.expand_dims(mask, axis=0)\nimg = torch.from_numpy(img)\nmask = torch.from_numpy(mask)`,
    "exam-v4-double":`nn.Conv2d(in_channels, mid_channels, kernel_size=3, padding=1, bias=False),\nnn.ReLU(inplace=True),\nnn.Conv2d(mid_channels, out_channels, kernel_size=3, padding=1, bias=False),\nnn.ReLU(inplace=True),`,
    "exam-v4-down":`x = self.pool(x)\nx = self.conv(x)\nreturn x`,
    "exam-v4-upinit":`self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2)\nself.conv = DoubleConv(in_channels, out_channels)`,
    "exam-v4-up":`x1 = self.up(x1)\nx1 = F.pad(x1, [diff_x // 2, diff_x - diff_x // 2,  # left, right\n                diff_y // 2, diff_y - diff_y // 2]) # top, bottom\nx = torch.cat([x2, x1], dim=1)`,
    "exam-v4-encoder":`x1 = self.inc(x)\nx2 = self.down1(x1)\nx3 = self.down2(x2)\nx4 = self.down3(x3)\nx5 = self.down4(x4)`,
    "exam-v4-decoder":`x = self.up1(x5, x4)\nx = self.up2(x, x3)\nx = self.up3(x, x2)\nx = self.up4(x, x1)\nlogits = self.outc(x)`,
    "exam-v4-train":`optimizer.zero_grad()\nlogits = model(imgs)\nloss = criterion(logits, masks)\nloss.backward()\noptimizer.step()`,
    "exam-v4-predict":`logits = model(imgs)\nprobs = torch.sigmoid(logits)\npreds = (probs > 0.5).float()`
  };Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"},make=d=>({...base,accepted_answers:[d.answer],...d});
  chapter.subjective=[
    make({id:"exam-v04-01",topic:"Synthetic Mask",difficulty:"2 · Dataset",sourceId:"exam-v4-mask",prompt:"원 중심까지 거리로 binary 원 mask를 만들고 Gaussian noise를 더한 입력 이미지를 0~1로 제한하는 네 줄을 작성하세요.",answer:cells["exam-v4-mask"],problem_context:`y, x = np.ogrid[:self.image_size, :self.image_size]\n????\n????\n????\n????`,explanation:"각 pixel과 중심의 Euclidean distance가 radius 이하면 foreground 1입니다. 입력은 mask에 noise를 더하되 유효 이미지 범위로 clip합니다.",tensor_flow:"coordinate grids [H,1],[1,W] → distance [H,W] → mask/image [H,W]",code_signal:"center_x,center_y,radius와 입력 설명 noise+mask가 수식을 결정합니다.",retry:"sqrt 없이 squared distance와 radius**2를 비교하는 동등한 식을 쓰세요."}),
    make({id:"exam-v04-02",topic:"Channel Tensor",difficulty:"1 · Shape",sourceId:"exam-v4-tensor",prompt:"2D NumPy image와 mask 앞에 channel 축을 추가하고 복사 없이 PyTorch Tensor로 변환하는 네 줄을 작성하세요.",answer:cells["exam-v4-tensor"],problem_context:`# (H,W) -> (1,H,W)\n????\n????\n????\n????`,explanation:"Conv2d sample은 C,H,W를 요구하므로 axis=0을 추가합니다. from_numpy는 같은 dtype float32를 유지하며 메모리를 공유합니다.",tensor_flow:"two [H,W] np.float32 → two [1,H,W] torch.float32",code_signal:"주석의 목표 shape와 반환 img,mask 타입이 연산을 알려줍니다.",retry:"axis=-1을 쓰면 만들어지는 shape와 Conv2d 기대 shape를 비교하세요."}),
    make({id:"exam-v04-03",topic:"DoubleConv",difficulty:"2 · Layer 구성",sourceId:"exam-v4-double",prompt:"3×3 convolution으로 공간 크기를 유지하면서 in→mid→out channel을 변환하는 두 Conv·ReLU 쌍 네 줄을 작성하세요.",answer:cells["exam-v4-double"],problem_context:`self.net = nn.Sequential(\n    ????\n    ????\n    ????\n    ????\n)`,explanation:"kernel 3에 padding 1을 사용해 H,W를 유지합니다. 첫 Conv가 mid channel, 둘째가 out channel을 만들고 각 뒤에 in-place ReLU가 옵니다.",tensor_flow:"[B,Cin,H,W] → [B,Cmid,H,W] → [B,Cout,H,W]",code_signal:"docstring의 (Conv→ReLU)×2와 mid_channels 설명이 constructor 인자를 줍니다.",retry:"padding=0일 때 두 Conv 후 H,W가 얼마나 줄어드는지 계산하세요."}),
    make({id:"exam-v04-04",topic:"Down Block",difficulty:"1 · 순서",sourceId:"exam-v4-down",prompt:"입력 해상도를 절반으로 줄인 뒤 DoubleConv로 output channel 특징을 만들고 반환하는 세 줄을 작성하세요.",answer:cells["exam-v4-down"],problem_context:`def forward(self, x):\n    ????\n    ????\n    ????`,explanation:"MaxPool2d가 먼저 H,W를 절반으로 줄이고 DoubleConv가 공간 크기를 유지하며 channel을 바꿉니다.",tensor_flow:"[B,Cin,H,W] → [B,Cin,H/2,W/2] → [B,Cout,H/2,W/2]",code_signal:"self.pool과 self.conv 정의 및 주석 1)해상도 축소 2)특징 추출이 순서를 정합니다.",retry:"두 줄 순서를 바꾸면 Conv가 처리하는 공간 연산량이 어떻게 달라지는지 말하세요."}),
    make({id:"exam-v04-05",topic:"Learned Upsampling",difficulty:"2 · Layer 구성",sourceId:"exam-v4-upinit",prompt:"bilinear=False에서 공간 크기를 2배로 하고 channel을 절반으로 줄이는 학습형 upsample과 concat 후 특징을 정제할 block을 만드는 두 줄을 작성하세요.",answer:cells["exam-v4-upinit"],problem_context:`else:\n    ????\n    ????`,explanation:"2×2 stride2 transposed convolution이 H,W를 2배, channel을 절반으로 만듭니다. skip concat 후 총 channel은 원래 in_channels가 되어 DoubleConv 입력과 맞습니다.",tensor_flow:"[B,C,H/2,W/2] → [B,C/2,H,W] → concat [B,C,H,W]",code_signal:"주석 deconv가 channel도 절반으로 줄임과 Up의 in_channels 정의가 답을 줍니다.",retry:"bilinear=True 분기에서 channel 감소를 어느 block이 담당하는지 확인하세요."}),
    make({id:"exam-v04-06",topic:"Up·Skip 정렬",difficulty:"3 · 독립 구현",sourceId:"exam-v4-up",prompt:"H,W 차이 diff_y·diff_x가 계산된 상태에서 decoder x1을 upsample·대칭 padding하고 encoder skip x2와 channel 축으로 연결하는 네 줄을 작성하세요.",answer:cells["exam-v4-up"],problem_context:`????\ndiff_y = x2.size(2) - x1.size(2)\ndiff_x = x2.size(3) - x1.size(3)\n????\n                ????\n????\nreturn self.conv(x)`,explanation:"upsample 후 홀수 크기 오차를 x2 기준 diff로 구합니다. pad 순서는 left,right,top,bottom이며 마지막에 같은 공간 크기의 두 feature를 dim=1로 concat합니다.",tensor_flow:"x1 [B,Cd,h,w] → [B,Cup,H,W]; x2 [B,Cs,H,W] → [B,Cs+Cup,H,W]",code_signal:"F.pad 주석과 cat dim=1은 공간 정렬 후 channel 결합을 명시합니다.",retry:"diff_x=3이면 left와 right pad가 각각 얼마인지 계산하세요."}),
    make({id:"exam-v04-07",topic:"Encoder Skip 저장",difficulty:"2 · 모델 흐름",sourceId:"exam-v4-encoder",prompt:"입력부터 bottleneck까지 네 Down stage를 순서대로 적용하면서 decoder skip에 쓸 다섯 feature를 저장하는 다섯 줄을 작성하세요.",answer:cells["exam-v4-encoder"],problem_context:`????\n????\n????\n????\n????\n# decoder follows`,explanation:"각 단계 출력은 다음 Down 입력이면서 대응 decoder stage의 skip입니다. x5만 bottleneck 시작값이고 x4~x1은 역순으로 사용합니다.",tensor_flow:"H,W → H/2 → H/4 → H/8 → H/16; channels increase",code_signal:"UNet __init__의 inc/down1~4와 decoder 호출 x5,x4...가 변수 연결을 결정합니다.",retry:"x3의 shape와 어느 Up 호출에서 skip으로 쓰이는지 적으세요."}),
    make({id:"exam-v04-08",topic:"Decoder·Output",difficulty:"3 · 모델 흐름",sourceId:"exam-v4-decoder",prompt:"bottleneck에서 시작해 encoder skip을 역순으로 결합하고 원래 해상도를 복원한 뒤 pixel class logits를 만드는 다섯 줄을 작성하세요.",answer:cells["exam-v4-decoder"],problem_context:`????\n????\n????\n????\n????\nreturn logits`,explanation:"각 Up은 현재 decoder feature와 같은 scale의 encoder feature를 받습니다. 마지막 x1까지 결합한 [B,64,H,W]를 1×1 head가 [B,n_classes,H,W]로 투영합니다.",tensor_flow:"[B,1024,H/16,W/16] → four Up → [B,64,H,W] → logits [B,1,H,W]",code_signal:"up1~up4 constructor 순서와 저장된 x5~x1 shape가 인자 쌍을 정합니다.",retry:"up2가 x2가 아니라 x3을 받는 이유를 spatial scale로 설명하세요."}),
    make({id:"exam-v04-09",topic:"Binary Segmentation 학습",difficulty:"2 · Loss",sourceId:"exam-v4-train",prompt:"입력·mask가 device에 준비된 batch에서 raw mask logits와 binary loss를 계산하고 parameter를 갱신하는 다섯 줄을 작성하세요.",answer:cells["exam-v4-train"],problem_context:`????\n????\n????\n????\n????`,explanation:"BCEWithLogitsLoss가 sigmoid를 포함하므로 raw logits를 mask와 직접 비교합니다. gradient 초기화, backward, step 순서로 학습합니다.",tensor_flow:"imgs [B,1,H,W] → logits [B,1,H,W] + masks → scalar → gradients",code_signal:"criterion 정의와 모델 output 주석이 sigmoid 없이 model(imgs)를 쓰도록 지시합니다.",retry:"criterion 전에 sigmoid를 넣으면 왜 수치 안정성과 함수 의미가 나빠지는지 말하세요."}),
    make({id:"exam-v04-10",topic:"Mask 추론",difficulty:"1 · Prediction",sourceId:"exam-v4-predict",prompt:"평가 이미지에서 raw logits를 foreground 확률로 바꾸고 0.5 기준 binary float mask를 만드는 세 줄을 작성하세요.",answer:cells["exam-v4-predict"],problem_context:`????\n????\n????`,explanation:"학습 때와 달리 해석 가능한 확률이 필요하므로 sigmoid를 적용하고 threshold 비교 boolean을 float 0/1로 변환합니다.",tensor_flow:"[B,1,H,W] logits → probabilities → binary masks",code_signal:"visualize 함수의 Pred mask와 threshold 0.5가 세 연산을 알려줍니다.",retry:"multi-class K채널 segmentation이라면 sigmoid 대신 어떤 축 연산을 쓰는지 말하세요."})
  ];
  chapter.mcq=[
    {id:"exam-v04-m1",source_question_id:"exam-v04-06",topic:"Skip concat 축",prompt:"[B,C1,H,W]와 [B,C2,H,W]를 U-Net skip으로 결합할 축은?",answer_index:1,explanation:"공간과 batch를 유지하고 channel을 더합니다.",choices:[{text:"dim=0",why:"batch 수가 늘어납니다."},{text:"dim=1",why:"channel이 C1+C2가 됩니다."},{text:"dim=2",why:"높이가 늘어납니다."},{text:"dim=3",why:"너비가 늘어납니다."},{text:"stack",why:"새 축이 생깁니다."}]},
    {id:"exam-v04-m2",source_question_id:"exam-v04-09",topic:"Binary loss",prompt:"1채널 raw logits와 0/1 mask를 학습할 criterion은?",answer_index:3,explanation:"sigmoid와 binary cross entropy가 결합된 loss입니다.",choices:[{text:"CrossEntropyLoss after sigmoid",why:"K-class index target 조합입니다."},{text:"MSELoss after argmax",why:"argmax는 미분 불가능합니다."},{text:"NLLLoss",why:"log-probability와 class index target용입니다."},{text:"BCEWithLogitsLoss",why:"raw binary logits에 알맞습니다."},{text:"L1Loss after threshold",why:"threshold는 gradient를 끊습니다."}]},
    {id:"exam-v04-m3",source_question_id:"exam-v04-03",topic:"공간 크기",prompt:"stride1 kernel3 Conv 두 번 후 H,W를 유지하려면 각 padding은?",answer_index:0,explanation:"kernel3의 양쪽 한 pixel padding이 크기를 유지합니다.",choices:[{text:"1",why:"H,W가 유지됩니다."},{text:"0",why:"Conv마다 2 pixel 줄어듭니다."},{text:"2",why:"Conv마다 2 pixel 늘어납니다."},{text:"3",why:"과도한 padding입니다."},{text:"padding 없음",why:"0과 같아 줄어듭니다."}]},
    {id:"exam-v04-m4",source_question_id:"exam-v04-08",topic:"Skip 순서",prompt:"bottleneck x5 이후 첫 Up의 skip 입력은?",answer_index:4,explanation:"같은 목표 spatial scale인 가장 깊은 encoder x4를 사용합니다.",choices:[{text:"x1",why:"원본 해상도라 너무 큽니다."},{text:"x2",why:"H/2 scale입니다."},{text:"x3",why:"H/4 scale입니다."},{text:"x5",why:"bottleneck 자신입니다."},{text:"x4",why:"upsample한 x5와 H/8 scale이 맞습니다."}]},
    {id:"exam-v04-m5",source_question_id:"exam-v04-10",topic:"학습·추론",prompt:"sigmoid와 0.5 threshold를 적용할 위치는?",answer_index:2,explanation:"학습 loss는 raw logits, 최종 mask 해석은 sigmoid 확률을 사용합니다.",choices:[{text:"모델 마지막 layer 안에서 항상",why:"BCEWithLogitsLoss와 sigmoid가 중복됩니다."},{text:"criterion 호출 전",why:"loss가 raw logits를 기대합니다."},{text:"추론에서 binary mask를 만들 때",why:"확률과 0/1 결과가 필요할 때입니다."},{text:"optimizer.step 뒤 parameter에",why:"parameter 변환이 아닙니다."},{text:"입력 이미지에",why:"출력 logit 변환입니다."}]}
  ];chapter.questionCount=chapter.subjective.length;chapter.exam_design={version:2,style:"segmentation shape·skip 문맥형",difficulty:["dataset·block","shape 연결","UNet forward 독립 구현"],excluded:["패키지 설치","plot 제목","고정 epoch"]};
})();

(() => {
  "use strict";
  const course=window.LLM_COURSE,chapter=course.chapters.find(c=>c.file==="03_DETR.ipynb");if(!chapter)return;
  chapter.notebook_goal="DETR 입력 전처리부터 query별 class·box 후처리와 encoder/decoder attention hook 분석까지 구현한다.";
  chapter.capability="pred_logits·pred_boxes와 feature-map attention의 shape를 근거로 탐지 후처리·필터링·좌표 변환·hook 코드를 완성할 수 있다.";
  chapter.summary="DETR은 CNN feature를 Transformer에 넣고 고정된 object query마다 class와 정규화 box를 냅니다. no-object를 제외해 신뢰도를 필터링하고 box를 pixel 좌표로 복원하며 attention으로 query의 근거를 분석합니다.";
  chapter.overview={title:"한 장의 이미지가 object query별 탐지 결과가 되는 과정",subtitle:"ResNet feature와 Transformer query가 class·box를 예측하고 후처리가 화면 좌표와 attention map을 복원한다.",steps:[{label:"Preprocess",code:"Resize→Tensor→ImageNet Normalize",flow:"PIL → [1,3,H,W]"},{label:"DETR",code:"backbone→encoder→decoder queries",flow:"image → logits·boxes"},{label:"Filter",code:"softmax, remove no-object, threshold",flow:"[Q,C+1] → keep [Q]"},{label:"Box",code:"cxcywh→xyxy→pixel",flow:"[K,4] normalized → pixels"},{label:"Explain",code:"forward hooks + reshape",flow:"query/position attention maps"}],rules:["pred_logits의 마지막 class는 no-object이므로 confidence 계산에서 제외한다.","box는 중심·크기 표현을 모서리 좌표로 바꾼 뒤 W,H,W,H를 곱한다.","query마다 하나의 예측이 나오며 threshold mask를 logits와 boxes에 동일하게 적용한다.","hook output에서 attention weight 위치 output[1]을 저장하고 사용 후 hook을 제거한다.","CNN의 HW sequence attention은 feature map H,W를 이용해 공간 map으로 reshape한다."]};
  chapter.key_points=[{title:"DETR 전처리",purpose:"COCO pretrained ResNet backbone의 입력 분포에 맞춥니다.",code:"Resize(800)→ToTensor→Normalize(ImageNet)",flow:"PIL → [3,H,W] float",watch:"정규화는 RGB ImageNet mean/std를 사용합니다."},{title:"Query 출력",purpose:"고정 Q개 query가 class(C+1)와 box 4개를 동시에 예측합니다.",code:"pred_logits [B,Q,C+1]\npred_boxes [B,Q,4]",flow:"decoder queries → set prediction",watch:"마지막 class는 배경이 아니라 no-object입니다."},{title:"Box 복원",purpose:"정규화 center box를 원본 이미지 pixel corner로 바꿉니다.",code:"cx±w/2, cy±h/2\n* [W,H,W,H]",flow:"[K,4] 0~1 → pixel xyxy",watch:"PIL size는 (W,H) 순서입니다."},{title:"Confidence filter",purpose:"no-object를 제외한 최고 class 확률이 threshold를 넘는 query만 남깁니다.",code:"softmax(-1)[0,:,:-1]\nmax(-1).values>threshold",flow:"[1,Q,C+1] → [Q,C] → keep [Q]",watch:"argmax index가 아니라 max values를 threshold와 비교합니다."},{title:"Attention hook",purpose:"모델 수정 없이 backbone·encoder·decoder 중간 출력을 캡처합니다.",code:"register_forward_hook(... output[1])",flow:"forward → saved feature/weights",watch:"중복 실행·메모리 누수를 막기 위해 remove합니다."}];
  chapter.theory_guide=[{title:"Set prediction",concept:"DETR은 anchor와 NMS 대신 고정 object query 집합이 객체 후보를 직접 냅니다.",flow:"Q queries → Q class distributions + Q boxes",code_signal:"pred_logits와 pred_boxes의 두 번째 축이 num_queries입니다.",exam_clue:"keep은 query 축 길이의 boolean mask입니다."},{title:"좌표계",concept:"모델은 해상도와 무관한 (cx,cy,w,h) 0~1 값을 내고 시각화는 (xmin,ymin,xmax,ymax) pixel을 요구합니다.",flow:"center normalized → corner normalized → corner pixels",code_signal:"unbind(1) 네 값과 PIL size=(W,H)가 공식을 결정합니다.",exam_clue:"x에는 W, y에는 H를 곱합니다."},{title:"Encoder·Decoder attention",concept:"encoder self-attention은 image position↔position, decoder cross-attention은 object query↔image position 관계입니다.",flow:"encoder [HW,HW]; decoder [Q,HW]",code_signal:"decoder map은 query idx로 선택해 H×W로 view합니다.",exam_clue:"box와 attention을 연결하는 index는 keep.nonzero의 query id입니다."},{title:"Forward hook",concept:"hook은 module forward 직후 input/output을 받아 중간 Tensor를 외부 저장소에 기록합니다.",flow:"register → model(img) → capture → remove",code_signal:"list append를 쓰는 이유는 closure에서 결과를 보관하기 위해서입니다.",exam_clue:"attention module의 반환 tuple에서 weight는 output[1]입니다."}];
  const cells={
    "exam-v3-transform":`T.Resize(800),\nT.ToTensor(),\nT.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])`,
    "exam-v3-box":`x_c, y_c, w, h = x.unbind(1)\nb = [(x_c - 0.5 * w), (y_c - 0.5 * h),\n     (x_c + 0.5 * w), (y_c + 0.5 * h)]\nreturn torch.stack(b, dim=1)`,
    "exam-v3-rescale":`img_w, img_h = size\nb = box_cxcywh_to_xyxy(out_bbox)\nb = b * torch.tensor([img_w, img_h, img_w, img_h], dtype=torch.float32)\nreturn b`,
    "exam-v3-infer":`outputs = model(img)\nprobas = outputs['pred_logits'].softmax(-1)[0, :, :-1]\nkeep = probas.max(-1).values > 0.9\nbboxes_scaled = rescale_bboxes(outputs['pred_boxes'][0, keep], im.size)`,
    "exam-v3-plot":`cl = p.argmax()\ntext = f'{CLASSES[cl]}: {p[cl]:0.2f}'\nax.text(xmin, ymin, text, fontsize=15,\n        bbox=dict(facecolor='yellow', alpha=0.5))`,
    "exam-v3-hooks":`lambda self, input, output: enc_attn_weights.append(output[1])\nlambda self, input, output: dec_attn_weights.append(output[1])`,
    "exam-v3-capture":`outputs = model(img)\nfor hook in hooks:\n    hook.remove()\nenc_attn_weights = enc_attn_weights[0]\ndec_attn_weights = dec_attn_weights[0]`,
    "exam-v3-attnshape":`h, w = conv_features['0'].tensors.shape[-2:]\nax.imshow(dec_attn_weights[0, idx].view(h, w))\nshape = f_map.tensors.shape[-2:]\nsattn = enc_attn_weights[0].reshape(shape + shape)`,
    "exam-v3-point":`idx = (idx_o[0] // fact, idx_o[1] // fact)\nax.imshow(sattn[..., idx[0], idx[1]], cmap='cividis', interpolation='nearest')`
  };Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"},make=d=>({...base,accepted_answers:[d.answer],...d});
  chapter.subjective=[
    make({id:"exam-v03-01",topic:"DETR 전처리",difficulty:"1 · Pipeline",sourceId:"exam-v3-transform",prompt:"COCO pretrained backbone에 맞게 짧은 변을 800으로 조정하고 CHW Tensor·ImageNet 정규화를 적용하는 세 줄을 순서대로 작성하세요.",answer:cells["exam-v3-transform"],problem_context:`transform = T.Compose([\n    ????\n    ????\n    ????\n])`,explanation:"공간 resize를 PIL에 적용하고 Tensor 변환 뒤 pretrained backbone이 학습된 ImageNet 채널 분포로 정규화합니다.",tensor_flow:"PIL → [3,H,W] float 0~1 → normalized float",code_signal:"COCO pretrained ResNet backbone과 주석의 Resize/Normalize가 값을 정합니다.",retry:"ToTensor와 Normalize 순서를 바꾸면 안 되는 이유를 설명하세요."}),
    make({id:"exam-v03-02",topic:"Box 형식 변환",difficulty:"2 · 좌표",sourceId:"exam-v3-box",prompt:"N개 normalized (cx,cy,w,h) box를 성분별로 나누고 (xmin,ymin,xmax,ymax) Tensor로 변환하는 네 줄을 작성하세요.",answer:cells["exam-v3-box"],problem_context:`def box_cxcywh_to_xyxy(x):\n    ????\n    ????\n         ????\n    ????`,explanation:"중심에서 절반 크기를 빼면 좌상단, 더하면 우하단입니다. 각 성분 [N]을 dim=1에 stack해 [N,4]를 복원합니다.",tensor_flow:"[N,4] cxcywh → four [N] → [N,4] xyxy",code_signal:"함수명과 plot이 xmin,ymin,xmax,ymax를 요구하는 문맥이 수식을 결정합니다.",retry:"cx=0.5,w=0.2의 xmin과 xmax를 계산하세요."}),
    make({id:"exam-v03-03",topic:"Pixel Box 복원",difficulty:"2 · Broadcasting",sourceId:"exam-v3-rescale",prompt:"normalized box를 corner 형식으로 바꾸고 PIL 원본 크기 (W,H)에 맞춰 pixel 좌표로 복원하는 네 줄을 작성하세요.",answer:cells["exam-v3-rescale"],problem_context:`def rescale_bboxes(out_bbox, size):\n    ????\n    ????\n    ????\n    ????`,explanation:"x 좌표에는 image width, y 좌표에는 height를 곱합니다. [4] scale Tensor가 [N,4] box 전체에 broadcasting됩니다.",tensor_flow:"[N,4] normalized × [4] WHWH → [N,4] pixels",code_signal:"PIL size 주석 (W,H)와 xyxy 성분 순서가 scale 배열을 결정합니다.",retry:"W와 H를 바꾸면 비정사각형 이미지에서 어떤 왜곡이 생기는지 설명하세요."}),
    make({id:"exam-v03-04",topic:"Query 필터링",difficulty:"3 · 후처리",sourceId:"exam-v3-infer",prompt:"DETR forward 후 no-object class를 제외한 확률을 만들고 최고 class confidence가 0.9를 넘는 query의 box만 pixel 좌표로 복원하는 네 줄을 작성하세요.",answer:cells["exam-v3-infer"],problem_context:`????\n????\n????\n????`,explanation:"softmax는 class 축 마지막에 적용하고 batch 0, 모든 query, 마지막 class 제외를 선택합니다. query별 max value로 keep mask를 만들고 동일 mask를 box에 적용합니다.",tensor_flow:"logits [1,Q,C+1] → probs [Q,C] → keep [Q] → boxes [K,4]",code_signal:"출력 shape 주석의 +1=no-object와 pred_boxes의 query 축이 slicing을 알려줍니다.",retry:"[:-1]을 query 축에 적용하면 어떤 오류가 생기는지 확인하세요."}),
    make({id:"exam-v03-05",topic:"탐지 Label",difficulty:"1 · 시각화",sourceId:"exam-v3-plot",prompt:"한 query 확률 p에서 class를 고르고 클래스명·점수 문자열을 만들어 box 좌상단에 표시하는 네 줄을 작성하세요.",answer:cells["exam-v3-plot"],problem_context:`for p, (xmin, ymin, xmax, ymax), c in zip(prob, boxes.tolist(), colors):\n    # rectangle already added\n    ????\n    ????\n    ????\n            ????`,explanation:"최고 확률 index로 CLASSES를 조회하고 해당 확률을 함께 표시합니다. box의 xmin,ymin이 label 위치가 됩니다.",tensor_flow:"p [C] → class scalar → text",code_signal:"CLASSES index table과 p[cl]이 class 이름·confidence를 연결합니다.",retry:"p.max()만 사용하면 잃는 정보가 무엇인지 말하세요."}),
    make({id:"exam-v03-06",topic:"Attention Hook 등록",difficulty:"3 · 모델 분석",sourceId:"exam-v3-hooks",prompt:"마지막 encoder self-attention과 decoder cross-attention hook이 반환값의 attention weight를 각각 리스트에 저장하도록 두 callback을 작성하세요.",answer:cells["exam-v3-hooks"],problem_context:`model.transformer.encoder.layers[-1].self_attn.register_forward_hook(\n    ????\n)\nmodel.transformer.decoder.layers[-1].multihead_attn.register_forward_hook(\n    ????\n)`,explanation:"각 forward hook은 module·input·output을 받고 tuple output의 두 번째 값인 attention weights를 closure 리스트에 append합니다.",tensor_flow:"module forward output tuple → weights → Python list",code_signal:"두 리스트 이름과 attention module의 output[1] 주석이 callback 본문을 알려줍니다.",retry:"두 callback에서 저장 대상 리스트만 바뀐다는 점을 표시하세요."}),
    make({id:"exam-v03-07",topic:"Hook 수집·해제",difficulty:"2 · 실행 순서",sourceId:"exam-v3-capture",prompt:"hook 등록 후 forward를 실행하고 모든 hook을 제거한 뒤 encoder·decoder weight Tensor를 리스트에서 꺼내는 다섯 줄을 작성하세요.",answer:cells["exam-v3-capture"],problem_context:`????\n????\n    ????\n????\n????`,explanation:"중간 출력은 실제 forward 때 저장됩니다. 이후 handle을 제거해 재호출 시 중복 append를 막고 각 리스트의 첫 capture를 Tensor로 바꿉니다.",tensor_flow:"registered hooks → forward → one captured item/list → Tensor",code_signal:"주석 propagate through model, hook 해제, list no longer needed가 순서를 그대로 제공합니다.",retry:"remove를 생략하고 세 번 실행하면 list 길이가 어떻게 되는지 말하세요."}),
    make({id:"exam-v03-08",topic:"Attention 공간 복원",difficulty:"3 · Shape",sourceId:"exam-v3-attnshape",prompt:"backbone feature의 H,W를 구해 선택 query의 decoder attention을 2D로 표시하고 encoder HW×HW attention을 H,W,H,W로 복원하는 네 줄을 작성하세요.",answer:cells["exam-v3-attnshape"],problem_context:`????\n????\n# encoder section\n????\n????`,explanation:"Transformer가 공간 H×W를 HW token으로 펼쳤으므로 시각화 시 원래 feature-map 크기를 사용합니다. decoder는 query별 HW, encoder는 HW×HW입니다.",tensor_flow:"decoder [1,Q,HW] → [H,W]; encoder [HW,HW] → [H,W,H,W]",code_signal:"conv feature 마지막 두 축이 H,W이며 idx는 keep.nonzero에서 온 query id입니다.",retry:"입력 이미지 H,W가 아니라 backbone feature H,W를 써야 하는 이유를 설명하세요."}),
    make({id:"exam-v03-09",topic:"Self-Attention 기준점",difficulty:"2 · 좌표 매핑",sourceId:"exam-v3-point",prompt:"원본 이미지 기준점 (y,x)을 backbone downsampling factor로 feature 좌표로 바꾸고 해당 token의 self-attention map을 표시하는 두 줄을 작성하세요.",answer:cells["exam-v3-point"],problem_context:`for idx_o, ax in zip(idxs, axs):\n    ????\n    ????`,explanation:"pixel 좌표를 factor로 정수 나눗셈해 feature token 위치로 바꾸고, 복원된 [H,W,H,W] attention의 query 위치를 마지막 두 축에서 선택합니다.",tensor_flow:"pixel (y,x) → token (y/f,x/f) → attention [H,W]",code_signal:"fact=32와 sattn reshape shape + shape가 좌표 변환과 index 방향을 알려줍니다.",retry:"sattn[idx0,idx1,...]와 현재 코드의 방향 차이를 설명하세요."})
  ];
  chapter.mcq=[
    {id:"exam-v03-m1",source_question_id:"exam-v03-04",topic:"No-object",prompt:"pred_logits [1,Q,C+1]에서 실제 class 확률만 고르는 slicing은?",answer_index:2,explanation:"batch 0, 모든 query, 마지막 no-object 제외입니다.",choices:[{text:"[0,:-1,:]",why:"마지막 query를 제거합니다."},{text:"[:,:,0]",why:"첫 class만 고릅니다."},{text:"[0,:,:-1]",why:"class 축 마지막을 제외합니다."},{text:"[-1,:,:]",why:"마지막 batch이며 no-object가 남습니다."},{text:"[0,0,:]",why:"첫 query만 고릅니다."}]},
    {id:"exam-v03-m2",source_question_id:"exam-v03-03",topic:"Box scale",prompt:"xyxy normalized box에 곱할 pixel scale 순서는?",answer_index:4,explanation:"x 좌표 두 개는 W, y 좌표 두 개는 H입니다.",choices:[{text:"[H,W,H,W]",why:"x,y scale이 바뀌었습니다."},{text:"[W,W,H,H]",why:"성분 순서와 다릅니다."},{text:"[H,H,W,W]",why:"corner 좌표 순서와 다릅니다."},{text:"[W,H]",why:"4개 성분과 직접 대응하지 않습니다."},{text:"[W,H,W,H]",why:"xmin,ymin,xmax,ymax 순서와 맞습니다."}]},
    {id:"exam-v03-m3",source_question_id:"exam-v03-06",topic:"Hook output",prompt:"MultiheadAttention forward hook에서 attention weight는 일반적으로 어느 값인가요?",answer_index:1,explanation:"output tuple의 두 번째 항이 attention weights입니다.",choices:[{text:"input[0]",why:"입력 query입니다."},{text:"output[1]",why:"attention weights입니다."},{text:"output[0].grad",why:"attention output의 gradient가 아닙니다."},{text:"module.weight",why:"투영 parameter입니다."},{text:"hook handle",why:"등록 해제용 객체입니다."}]},
    {id:"exam-v03-m4",source_question_id:"exam-v03-08",topic:"Attention shape",prompt:"decoder cross-attention [Q,HW]의 한 query를 공간 map으로 바꿀 shape는?",answer_index:0,explanation:"backbone feature의 H,W로 view합니다.",choices:[{text:"[H,W]",why:"HW token을 원래 공간으로 복원합니다."},{text:"원본 이미지 [Hi,Wi]",why:"attention은 downsample feature token 기준입니다."},{text:"[Q,H]",why:"query 축을 공간축으로 오해했습니다."},{text:"[C,H,W]",why:"channel 축이 없습니다."},{text:"[HW,HW]",why:"encoder self-attention shape입니다."}]},
    {id:"exam-v03-m5",source_question_id:"exam-v03-04",topic:"Confidence mask",prompt:"query별 threshold와 비교할 값은?",answer_index:3,explanation:"실제 class 중 최대 probability 값을 사용합니다.",choices:[{text:"argmax class index",why:"class 번호는 confidence가 아닙니다."},{text:"box width",why:"확률이 아닙니다."},{text:"no-object 확률만",why:"실제 class confidence를 필터링해야 합니다."},{text:"probas.max(-1).values",why:"query별 최고 실제 class 확률입니다."},{text:"전체 평균 확률",why:"query별 객체 신뢰도를 잃습니다."}]}
  ];chapter.questionCount=chapter.subjective.length;chapter.exam_design={version:2,style:"탐지 후처리·attention 문맥형",difficulty:["전처리·좌표","query filtering","hook·shape 독립 구현"],excluded:["이미지 URL","COCO 클래스 문자열","위젯 배치"]};
})();

(() => {
  "use strict";
  const course=window.LLM_COURSE,chapter=course.chapters.find(c=>c.file==="02_ViT_CIFAR10.ipynb");if(!chapter)return;
  chapter.notebook_goal="CIFAR-10 이미지를 patch token으로 바꾸고 Q·K·V self-attention, CLS·position embedding, residual encoder, 분류 학습까지 구현한다.";
  chapter.capability="이미지와 토큰의 shape를 추적하며 ViT patch embedding·multi-head attention·CLS pooling·loss 코드를 독립적으로 완성할 수 있다.";
  chapter.summary="32×32 이미지는 4×4 patch 64개와 CLS 1개로 구성된 token sequence가 되고, multi-head self-attention과 FFN을 거쳐 CLS 표현에서 10-class logits를 만듭니다.";
  chapter.overview={title:"이미지가 65개 토큰을 거쳐 분류 logits가 되는 과정",subtitle:"공간 패치를 sequence로 바꾸고 모든 토큰 사이의 관계를 attention으로 학습한다.",steps:[{label:"Patchify",code:"[B,C,H,W] → [B,N,patch_dim]",flow:"32×32 / 4×4 → N=64"},{label:"Embedding",code:"Linear + CLS + Position",flow:"[B,64,D] → [B,65,D]"},{label:"Attention",code:"QKᵀ/√d → softmax → AV",flow:"[B,H,65,d]"},{label:"Encoder",code:"Attention+residual, FFN+residual",flow:"[B,65,D] 유지"},{label:"Classifier",code:"CLS or mean → Linear",flow:"[B,D] → [B,10]"}],rules:["패치 수 N=(H/Ph)(W/Pw), patch_dim=C·Ph·Pw를 구분한다.","Q·K·V를 head별 [B,H,N,d]로 재배열한 뒤 attention score는 [B,H,N,N]이다.","softmax는 각 query가 참조할 key 축인 마지막 차원에 적용한다.","CLS를 붙인 뒤 position embedding 길이도 n+1만큼 사용한다.","CrossEntropy 조합은 raw logits, log_softmax+nll_loss 조합은 log-probability를 입력한다."]};
  chapter.key_points=[{title:"Patch token",purpose:"2차원 이미지를 Transformer가 처리할 sequence로 변환합니다.",code:"N=(H/Ph)*(W/Pw)\npatch_dim=C*Ph*Pw",flow:"[B,C,H,W] → [B,N,patch_dim] → [B,N,D]",watch:"token 수와 token feature 차원을 바꾸지 않습니다."},{title:"Multi-head Attention",purpose:"각 token이 다른 모든 token에서 필요한 정보를 가중합합니다.",code:"QKᵀ * d^-0.5 → Softmax → Attention·V",flow:"Q,K,V [B,H,N,d] → attn [B,H,N,N] → [B,N,D]",watch:"K의 token 축을 transpose하는 einsum index를 확인합니다."},{title:"CLS·Position",purpose:"CLS는 이미지 전체 표현을 모으고 position은 patch의 공간 순서를 알려줍니다.",code:"cat(CLS,x,dim=1)\nx += pos[:,:n+1]",flow:"[B,N,D] → [B,N+1,D]",watch:"CLS token은 batch만큼 repeat합니다."},{title:"Residual Encoder",purpose:"Attention과 FFN의 변화량을 원래 token에 더해 깊은 학습을 안정화합니다.",code:"x=attn(x)+x\nx=ff(x)+x",flow:"[B,N+1,D] shape 유지",watch:"두 sublayer 모두 별도의 residual이 있습니다."},{title:"분류·평가",purpose:"CLS 또는 token 평균을 class head에 넣고 정답 label과 loss를 계산합니다.",code:"x=x[:,0] or x.mean(1)\nlogits=head(x)",flow:"[B,65,D] → [B,D] → [B,10]",watch:"분류 head 전에 token 축을 제거합니다."}];
  chapter.theory_guide=[{title:"Scaled dot-product",concept:"Q와 K 내적은 d가 커질수록 값이 커지므로 1/√d를 곱해 softmax가 지나치게 포화되지 않게 합니다.",flow:"[B,H,N,d]×[B,H,N,d] → [B,H,N,N]",code_signal:"self.scale=dim_head ** -0.5입니다.",exam_clue:"** -0.5는 제곱근의 역수입니다."},{title:"einsum index",concept:"i는 query token, j는 key/value token, d는 head feature입니다.",flow:"q[i,d]·k[j,d] → score[i,j]; attn[i,j]·v[j,d] → out[i,d]",code_signal:"첫 식은 d를 줄이고 i,j를 남기며 두 번째는 j를 줄입니다.",exam_clue:"출력에 남아야 할 index를 먼저 적으세요."},{title:"CLS와 position",concept:"동일한 patch 변환만으로는 위치 순서를 알 수 없으므로 학습 가능한 position vector를 더합니다.",flow:"64 patch + 1 CLS = 65 token",code_signal:"pos_embedding의 두 번째 차원이 num_patches+1입니다.",exam_clue:"slice는 n이 아니라 n+1까지입니다."},{title:"학습 loss 조합",concept:"log_softmax는 log-probability를 만들고 NLL loss가 정답 class의 음의 log 값을 최소화합니다.",flow:"logits [B,C] → log_probs [B,C] + labels [B] → scalar",code_signal:"F.log_softmax와 F.nll_loss가 연속합니다.",exam_clue:"CrossEntropyLoss를 쓰면 log_softmax를 별도로 적용하지 않습니다."}];
  const cells={
    "exam-v2-patchcalc":`num_patches = (image_height // patch_height) * (image_width // patch_width)\npatch_dim = cfg.channels * patch_height * patch_width`,
    "exam-v2-qkv":`qkv = self.to_qkv(x).chunk(3, dim = -1)\nq, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h = h), qkv)`,
    "exam-v2-attn":`dots = einsum('b h i d, b h j d -> b h i j', q, k) * self.scale\nattn = self.attend(dots)\nout = einsum('b h i j, b h j d -> b h i d', attn, v)`,
    "exam-v2-residual":`x = attn(x) + x\nx = ff(x) + x`,
    "exam-v2-clspos":`x = self.to_patch_embedding(img)\ncls_tokens = repeat(self.cls_token, "1 1 d -> b 1 d", b=b)\nx = torch.cat((cls_tokens, x), dim=1)\nx = x + self.pos_embedding[:, : (n + 1)]`,
    "exam-v2-head":`x = x[:, 0] if self.pool == "cls" else x.mean(dim=1)\nreturn self.mlp_head(x)`,
    "exam-v2-train":`optimizer.zero_grad()\noutput = F.log_softmax(model(data), dim=1)\nloss = F.nll_loss(output, target)\nloss.backward()\noptimizer.step()`,
    "exam-v2-eval":`output = F.log_softmax(model(data), dim=1)\nloss = F.nll_loss(output, target, reduction='sum')\n_, pred = torch.max(output, dim=1)\ntotal_loss += float(loss.item())\ncorrect_samples += int(pred.eq(target).sum().item())`,
    "exam-v2-clsmap":`cls_attn = attn_bhNN.mean(dim=1)[0, 0, 1:]\nattn_2d = cls_attn_1d.reshape(grid_h, grid_w)\nattn_up = F.interpolate(attn_t, size=(out_h, out_w), mode="bilinear", align_corners=False)[0,0]`,
    "exam-v2-wrong":`logits = model(data)\npreds = logits.argmax(dim=1)\nwrong_mask = preds.ne(target)\nwrong_data = data[wrong_mask].detach().cpu()`
  };Object.entries(cells).forEach(([id,source])=>course.cells[id]={source});
  const base={subject:"Vision",chapterId:chapter.id,chapterNumber:chapter.number,chapterTitle:chapter.title,file:chapter.file,occurrence:0,isSourceBlank:true,source_type:"원본 노트북 전체 코드 기반 예상문제"},make=d=>({...base,accepted_answers:[d.answer],...d});
  chapter.subjective=[
    make({id:"exam-v02-01",topic:"Patch 수·차원",difficulty:"1 · Shape",sourceId:"exam-v2-patchcalc",prompt:"image·patch 크기와 channel 수로 patch token 개수와 펼친 patch feature 차원을 계산하는 두 줄을 작성하세요.",answer:cells["exam-v2-patchcalc"],problem_context:`image_height, image_width = pair(cfg.image_size)\npatch_height, patch_width = pair(cfg.patch_size)\n????\n????`,explanation:"patch 개수는 세로·가로 grid 수의 곱이고 한 patch vector는 channel×patch 높이×너비입니다.",tensor_flow:"[B,C,H,W] → N=(H/Ph)(W/Pw), patch_dim=CPhPw",code_signal:"Rearrange의 h,w와 p1,p2,c가 두 수식에 그대로 대응합니다.",retry:"32×32 RGB, 4×4 patch일 때 N과 patch_dim을 계산하세요."}),
    make({id:"exam-v02-02",topic:"Q·K·V Head 분리",difficulty:"2 · Tensor 재배열",sourceId:"exam-v2-qkv",prompt:"token [B,N,D]를 한 번에 Q·K·V로 투영·분할하고 각각 [B,H,N,d]로 재배열하는 두 줄을 작성하세요.",answer:cells["exam-v2-qkv"],problem_context:`b, n, _, h = *x.shape, self.heads\n????\n????`,explanation:"Linear 출력의 마지막 축 3·H·d를 세 Tensor로 나눈 뒤 결합된 H·d를 head와 head_dim으로 분리합니다.",tensor_flow:"[B,N,D] → [B,N,3Hd] → 3×[B,H,N,d]",code_signal:"to_qkv의 out_features=inner_dim*3과 self.heads가 chunk 수·rearrange pattern을 결정합니다.",retry:"chunk의 dim을 1로 쓰면 어떤 축이 잘못 나뉘는지 설명하세요."}),
    make({id:"exam-v02-03",topic:"Scaled Self-Attention",difficulty:"3 · 독립 구현",sourceId:"exam-v2-attn",prompt:"head별 Q·K로 scaled token score를 만들고 마지막 축 softmax 후 V를 가중합하는 세 줄을 작성하세요.",answer:cells["exam-v2-attn"],problem_context:`????\n????\nself.last_attn = attn.detach()\n????`,explanation:"Q의 i token과 K의 j token 내적으로 [i,j] score를 만들고 scale 후 softmax합니다. j축 attention으로 V[j]를 합쳐 query i의 새 표현을 얻습니다.",tensor_flow:"Q,K [B,H,N,d] → dots/attn [B,H,N,N] → out [B,H,N,d]",code_signal:"einsum 출력에 첫 계산은 i,j, 두 번째는 i,d가 남아야 합니다.",retry:"각 einsum에서 합산되어 사라지는 index를 표시하세요."}),
    make({id:"exam-v02-04",topic:"Encoder Residual",difficulty:"1 · Layer 연결",sourceId:"exam-v2-residual",prompt:"각 Transformer layer에서 Attention과 FFN 출력에 각각 residual을 적용하는 두 줄을 작성하세요.",answer:cells["exam-v2-residual"],problem_context:`for attn, ff in self.layers:\n    ????\n    ????`,explanation:"각 sublayer가 만든 변화량을 입력 x에 더해 원래 정보를 보존하고 gradient 흐름을 안정화합니다.",tensor_flow:"[B,N,D] → attention+identity → FFN+identity → [B,N,D]",code_signal:"PreNorm wrapper가 정규화를 내부 처리하므로 loop에는 두 함수 호출과 +x만 남습니다.",retry:"두 번째 줄이 ff(attn(x))+x가 아닌 이유를 설명하세요."}),
    make({id:"exam-v02-05",topic:"CLS·Position",difficulty:"3 · Sequence 구성",sourceId:"exam-v2-clspos",prompt:"이미지를 patch embedding으로 바꾸고 CLS를 batch만큼 복제해 앞에 붙인 뒤 n+1개 position embedding을 더하는 네 줄을 작성하세요.",answer:cells["exam-v2-clspos"],problem_context:`????\nb, n, _ = x.shape\n????\n????\n????`,explanation:"patch sequence 앞에 학습 가능한 CLS를 추가하므로 token 수가 n+1이 됩니다. 위치 embedding도 같은 길이로 slice되어 broadcasting됩니다.",tensor_flow:"[B,C,H,W] → [B,N,D] → [B,N+1,D] + [1,N+1,D]",code_signal:"cls_token shape [1,1,D], pos_embedding shape [1,num_patches+1,D]가 repeat·cat 축을 알려줍니다.",retry:"cat dim=-1을 쓰면 어떤 차원이 잘못 늘어나는지 확인하세요."}),
    make({id:"exam-v02-06",topic:"Pooling·Classifier",difficulty:"2 · 출력",sourceId:"exam-v2-head",prompt:"Encoder token에서 설정에 따라 CLS 또는 token 평균을 선택하고 class head로 logits를 반환하는 두 줄을 작성하세요.",answer:cells["exam-v2-head"],problem_context:`x = self.transformer(x)\n????\n????`,explanation:"CLS pooling은 index 0, mean pooling은 token 축 dim=1을 제거합니다. 둘 다 [B,D]가 되어 mlp_head에서 [B,C] logits로 바뀝니다.",tensor_flow:"[B,N+1,D] → [B,D] → [B,num_classes]",code_signal:"self.pool에 허용된 문자열 cls/mean과 head 첫 Linear 입력 D가 선택을 결정합니다.",retry:"mean(dim=-1)을 쓰면 head 입력 shape가 왜 틀리는지 설명하세요."}),
    make({id:"exam-v02-07",topic:"ViT 학습 Step",difficulty:"2 · Loss",sourceId:"exam-v2-train",prompt:"batch에서 gradient를 초기화하고 ViT logits를 log-probability로 바꿔 NLL loss를 계산·역전파·갱신하는 다섯 줄을 작성하세요.",answer:cells["exam-v2-train"],problem_context:`????\n????\n????\n????\n????`,explanation:"log_softmax와 NLL loss는 CrossEntropy와 동등한 조합입니다. 이전 gradient를 지운 후 loss gradient로 optimizer가 parameter를 갱신합니다.",tensor_flow:"data [B,3,32,32] → logits/log_probs [B,10] + target [B] → scalar",code_signal:"주석 Negative Log Likelihood와 optimizer가 표준 학습 순서를 알려줍니다.",retry:"CrossEntropyLoss를 사용한 대체 두 줄을 작성하세요."}),
    make({id:"exam-v02-08",topic:"평가 Loss·Accuracy",difficulty:"3 · Metric 연결",sourceId:"exam-v2-eval",prompt:"gradient 없는 평가에서 log-probability, 합산 loss, class 예측을 구해 전체 loss와 정답 개수를 누적하는 다섯 줄을 작성하세요.",answer:cells["exam-v2-eval"],problem_context:`with torch.no_grad():\n    # inside loop\n    ????\n    ????\n    ????\n    ????\n    ????`,explanation:"batch loss를 reduction=sum으로 계산해야 전체 sample 기준 평균을 마지막에 정확히 구할 수 있습니다. class 최대값 index를 target과 비교해 맞은 개수를 누적합니다.",tensor_flow:"[B,10] → batch loss sum + pred [B] → dataset totals",code_signal:"loop 밖 avg_loss=total_loss/total_samples와 acc=correct_samples/total_samples가 reduction과 누적 방식을 정합니다.",retry:"reduction 기본 mean을 사용하면 total_loss 누적에 무엇을 곱해야 하는지 말하세요."}),
    make({id:"exam-v02-09",topic:"CLS Attention Map",difficulty:"3 · 해석",sourceId:"exam-v2-clsmap",prompt:"attention [1,H,N+1,N+1]에서 head 평균 CLS→patch 값만 골라 patch grid로 바꾸고 이미지 크기로 보간하는 세 줄을 작성하세요.",answer:cells["exam-v2-clsmap"],problem_context:`# CLS index=0, patches=1:\n????\n????\n????`,explanation:"head를 평균낸 뒤 batch0의 query CLS 0에서 key patch 1:만 선택합니다. 1D patch 값을 grid로 reshape하고 bilinear interpolation으로 입력 해상도에 맞춥니다.",tensor_flow:"[1,H,N+1,N+1] → [N] → [Gh,Gw] → [H,W]",code_signal:"CLS와 patch index 주석, grid_h*grid_w=num_patches 조건이 slicing과 reshape를 결정합니다.",retry:"마지막 1:을 생략하면 grid reshape가 실패하는 이유를 설명하세요."}),
    make({id:"exam-v02-10",topic:"오분류 선택",difficulty:"2 · 분석",sourceId:"exam-v2-wrong",prompt:"평가 batch의 logits에서 예측 class를 만들고 target과 다른 mask로 오분류 이미지만 CPU Tensor로 선택하는 네 줄을 작성하세요.",answer:cells["exam-v2-wrong"],problem_context:`????\n????\n????\nif wrong_mask.any():\n    ????`,explanation:"class 축 argmax로 예측 [B]를 만들고 ne 비교 mask [B]를 image batch 첫 축에 적용합니다. 시각화를 위해 gradient를 분리해 CPU로 옮깁니다.",tensor_flow:"data [B,C,H,W] → logits [B,K] → mask [B] → wrong [M,C,H,W]",code_signal:"오분류 조건은 preds와 target의 not-equal이며 boolean mask는 batch 축을 선택합니다.",retry:"labels와 predictions까지 같은 mask로 선택하는 두 줄을 추가하세요."})
  ];
  chapter.mcq=[
    {id:"exam-v02-m1",source_question_id:"exam-v02-01",topic:"Patch shape",prompt:"32×32 RGB 이미지를 4×4 patch로 나눌 때 token 수와 patch_dim은?",answer_index:2,explanation:"8×8=64 patch, 3×4×4=48 feature입니다.",choices:[{text:"16,64",why:"grid와 embedding dim을 혼동했습니다."},{text:"48,64",why:"patch_dim과 token 수 순서가 바뀌었습니다."},{text:"64,48",why:"올바른 계산입니다."},{text:"65,48",why:"65는 CLS를 붙인 뒤 token 수입니다."},{text:"64,3",why:"patch 공간 크기를 반영하지 않았습니다."}]},
    {id:"exam-v02-m2",source_question_id:"exam-v02-03",topic:"Attention score",prompt:"Q,K가 [B,H,N,d]일 때 QKᵀ score shape는?",answer_index:4,explanation:"각 query token과 모든 key token 조합을 갖습니다.",choices:[{text:"[B,N,d]",why:"head와 key token 관계가 없습니다."},{text:"[B,H,d,d]",why:"token이 아니라 feature 관계입니다."},{text:"[N,N]",why:"batch와 head가 사라졌습니다."},{text:"[B,H,N,d]",why:"value 가중합 후 shape입니다."},{text:"[B,H,N,N]",why:"query와 key token 축이 남습니다."}]},
    {id:"exam-v02-m3",source_question_id:"exam-v02-05",topic:"CLS 연결",prompt:"CLS [B,1,D]를 patch [B,N,D] 앞에 붙일 축은?",answer_index:1,explanation:"token sequence 축 dim=1을 연결합니다.",choices:[{text:"dim=0",why:"batch 수가 늘어납니다."},{text:"dim=1",why:"token 수가 N+1이 됩니다."},{text:"dim=2",why:"embedding 차원이 늘어납니다."},{text:"stack dim=1",why:"새 축이 생겨 rank가 달라집니다."},{text:"연결하지 않고 더함",why:"token 수 1과 N이 맞지 않습니다."}]},
    {id:"exam-v02-m4",source_question_id:"exam-v02-07",topic:"Loss 조합",prompt:"F.log_softmax(model(data),dim=1)의 올바른 loss는?",answer_index:0,explanation:"log-probability는 NLL loss와 짝을 이룹니다.",choices:[{text:"F.nll_loss(output,target)",why:"올바른 조합입니다."},{text:"MSELoss(output,target)",why:"class index 회귀가 아닙니다."},{text:"CrossEntropyLoss(output,target)",why:"log_softmax를 중복 처리합니다."},{text:"BCEWithLogitsLoss(output,target)",why:"단일-label multiclass 설정과 target 형식이 다릅니다."},{text:"softmax(output)",why:"loss가 아닙니다."}]},
    {id:"exam-v02-m5",source_question_id:"exam-v02-09",topic:"Attention 해석",prompt:"CLS가 patch를 참고한 attention만 선택하는 index는?",answer_index:3,explanation:"query CLS=0, key patch=1:이며 head는 평균합니다.",choices:[{text:"attn[0,:,1:,0]",why:"patch query가 CLS key를 보는 반대 방향입니다."},{text:"attn.mean(1)[0,1:,1:]",why:"patch-to-patch matrix입니다."},{text:"attn[0,0,0,0]",why:"한 head의 CLS self 값 하나입니다."},{text:"attn.mean(1)[0,0,1:]",why:"head 평균 CLS→patch vector입니다."},{text:"attn.mean(0)",why:"batch만 평균하고 필요한 index를 고르지 않았습니다."}]}
  ];chapter.questionCount=chapter.subjective.length;chapter.exam_design={version:2,style:"전체 코드·Tensor 문맥형",difficulty:["shape 계산","연산 연결","attention 독립 구현"],excluded:["경로·패키지 설치","고정 epoch","시각화 제목"]};
})();
