(() => {
  const line = (text, highlight = false) => ({ text, highlight });
  const cell = (cell_number, problem, answer, marked) => ({
    cell_number,
    blank_count: marked.length,
    problem_lines: problem.map((text, i) => line(text, marked.includes(i))),
    answer_lines: answer.map((text, i) => line(text, marked.includes(i))),
  });
  const transformProblem = [
    "train_tfms = T.Compose([",
    "    T.????(32, padding=4),",
    "    T.????(),",
    "    T.????(),  # PIL → Tensor (C, H, W), 0~1",
    "    T.????(CIFAR10_MEAN, CIFAR10_STD),",
    "]) ",
    "train_loader = DataLoader(train_set, batch_size=batch_size, ????=True)",
  ];
  const transformAnswer = [
    "train_tfms = T.Compose([",
    "    T.RandomCrop(32, padding=4),",
    "    T.RandomHorizontalFlip(),",
    "    T.ToTensor(),  # PIL → Tensor (C, H, W), 0~1",
    "    T.Normalize(CIFAR10_MEAN, CIFAR10_STD),",
    "]) ",
    "train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)",
  ];
  const modelProblem = [
    "model = models.resnet18(weights=None)",
    "model.conv1 = nn.Conv2d(????, 64, kernel_size=3, stride=1, padding=1, bias=False)",
    "model.maxpool = nn.Identity()",
    "model.fc = nn.Linear(model.fc.in_features, ????)",
  ];
  const modelAnswer = [
    "model = models.resnet18(weights=None)",
    "model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)",
    "model.maxpool = nn.Identity()",
    "model.fc = nn.Linear(model.fc.in_features, num_classes)",
  ];
  const trainProblem = [
    "optimizer.zero_grad(set_to_none=True)",
    "logits = ????(images)",
    "loss = criterion(logits, labels)",
    "scaler.scale(loss).????()",
    "scaler.step(optimizer)",
    "scaler.update()",
    "preds = logits.????(dim=1)",
  ];
  const trainAnswer = [
    "optimizer.zero_grad(set_to_none=True)",
    "logits = model(images)",
    "loss = criterion(logits, labels)",
    "scaler.scale(loss).backward()",
    "scaler.step(optimizer)",
    "scaler.update()",
    "preds = logits.argmax(dim=1)",
  ];
  const vitAttentionProblem = [
    "class Attention(nn.Module):",
    "    def forward(self, x):",
    "        b, n, _, h = *x.shape, self.heads",
    "        qkv = self.to_qkv(x).????(3, dim=-1)",
    "        q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h=h), qkv)",
    "        dots = einsum('b h i d, b h j d -> b h i j', ????, ????) * self.scale",
    "        attn = self.????(dots)",
    "        out = einsum('b h i j, b h j d -> b h i d', attn, ????)",
    "        out = rearrange(out, 'b h n d -> b n (h d)')",
    "        return self.to_out(out)",
  ];
  const vitAttentionAnswer = [
    "class Attention(nn.Module):",
    "    def forward(self, x):",
    "        b, n, _, h = *x.shape, self.heads",
    "        qkv = self.to_qkv(x).chunk(3, dim=-1)",
    "        q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h=h), qkv)",
    "        dots = einsum('b h i d, b h j d -> b h i j', q, k) * self.scale",
    "        attn = self.attend(dots)",
    "        out = einsum('b h i j, b h j d -> b h i d', attn, v)",
    "        out = rearrange(out, 'b h n d -> b n (h d)')",
    "        return self.to_out(out)",
  ];
  const vitPatchProblem = [
    "num_patches = (image_height // patch_height) * (image_width // patch_width)",
    "patch_dim = cfg.???? * patch_height * patch_width",
    "self.to_patch_embedding = nn.Sequential(",
    "    Rearrange('b c (h p1) (w p2) -> b (h w) (p1 p2 c)',",
    "              p1=patch_height, p2=patch_width),",
    "    nn.????(patch_dim, cfg.dim),",
    ")",
    "self.cls_token = nn.????(torch.randn(1, 1, cfg.dim))",
    "self.pos_embedding = nn.Parameter(torch.randn(1, num_patches + 1, cfg.dim))",
  ];
  const vitPatchAnswer = [
    "num_patches = (image_height // patch_height) * (image_width // patch_width)",
    "patch_dim = cfg.channels * patch_height * patch_width",
    "self.to_patch_embedding = nn.Sequential(",
    "    Rearrange('b c (h p1) (w p2) -> b (h w) (p1 p2 c)',",
    "              p1=patch_height, p2=patch_width),",
    "    nn.Linear(patch_dim, cfg.dim),",
    ")",
    "self.cls_token = nn.Parameter(torch.randn(1, 1, cfg.dim))",
    "self.pos_embedding = nn.Parameter(torch.randn(1, num_patches + 1, cfg.dim))",
  ];
  const vitForwardProblem = [
    "def forward(self, img):",
    "    x = self.????(img)",
    "    b, n, _ = x.shape",
    "    cls_tokens = repeat(self.cls_token, '1 1 d -> b 1 d', b=b)",
    "    x = torch.????((cls_tokens, x), dim=1)",
    "    x = x + self.pos_embedding[:, : (n + 1)]",
    "    x = self.dropout(x)",
    "    x = self.????(x)",
    "    x = x[:, 0] if self.pool == 'cls' else x.????(dim=1)",
    "    return self.mlp_head(x)",
  ];
  const vitForwardAnswer = [
    "def forward(self, img):",
    "    x = self.to_patch_embedding(img)",
    "    b, n, _ = x.shape",
    "    cls_tokens = repeat(self.cls_token, '1 1 d -> b 1 d', b=b)",
    "    x = torch.cat((cls_tokens, x), dim=1)",
    "    x = x + self.pos_embedding[:, : (n + 1)]",
    "    x = self.dropout(x)",
    "    x = self.transformer(x)",
    "    x = x[:, 0] if self.pool == 'cls' else x.mean(dim=1)",
    "    return self.mlp_head(x)",
  ];
  const vitTransformerProblem = [
    "def forward(self, x):",
    "    for attn, ff in self.layers:",
    "        # Attention 결과에 입력 x를 더하는 residual 연결",
    "        x = ????(x) + x",
    "        # FFN 결과에 입력 x를 더하는 residual 연결",
    "        x = ????(x) + x",
    "    return x",
  ];
  const vitTransformerAnswer = [
    "def forward(self, x):",
    "    for attn, ff in self.layers:",
    "        # Attention 결과에 입력 x를 더하는 residual 연결",
    "        x = attn(x) + x",
    "        # FFN 결과에 입력 x를 더하는 residual 연결",
    "        x = ff(x) + x",
    "    return x",
  ];
  const vitTrainProblem = [
    "optimizer.zero_grad()",
    "output = F.log_softmax(????(data), dim=1)",
    "loss = F.????(output, target)",
    "loss.????()",
    "optimizer.????()",
    "",
    "with torch.no_grad():",
    "    output = F.log_softmax(model(data), dim=1)",
    "    _, pred = torch.????(output, dim=1)",
    "    correct_samples += int(pred.????(target).sum().item())",
  ];
  const vitTrainAnswer = [
    "optimizer.zero_grad()",
    "output = F.log_softmax(model(data), dim=1)",
    "loss = F.nll_loss(output, target)",
    "loss.backward()",
    "optimizer.step()",
    "",
    "with torch.no_grad():",
    "    output = F.log_softmax(model(data), dim=1)",
    "    _, pred = torch.max(output, dim=1)",
    "    correct_samples += int(pred.eq(target).sum().item())",
  ];
  const detrTransformProblem = [
    "transform = T.Compose([",
    "    T.????(800),",
    "    T.????(),",
    "    T.????([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])",
    "])",
    "",
    "def box_cxcywh_to_xyxy(x):",
    "    x_c, y_c, w, h = x.????(1)",
    "    b = [x_c - 0.5*w, y_c - 0.5*h, x_c + 0.5*w, y_c + 0.5*h]",
    "    return torch.????(b, dim=1)",
  ];
  const detrTransformAnswer = [
    "transform = T.Compose([",
    "    T.Resize(800),",
    "    T.ToTensor(),",
    "    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])",
    "])",
    "",
    "def box_cxcywh_to_xyxy(x):",
    "    x_c, y_c, w, h = x.unbind(1)",
    "    b = [x_c - 0.5*w, y_c - 0.5*h, x_c + 0.5*w, y_c + 0.5*h]",
    "    return torch.stack(b, dim=1)",
  ];
  const detrRescaleProblem = [
    "def rescale_bboxes(out_bbox, size):",
    "    img_w, img_h = size",
    "    b = ????(out_bbox)",
    "    scale = torch.tensor([img_w, img_h, img_w, img_h], dtype=torch.float32)",
    "    return b ???? scale",
  ];
  const detrRescaleAnswer = [
    "def rescale_bboxes(out_bbox, size):",
    "    img_w, img_h = size",
    "    b = box_cxcywh_to_xyxy(out_bbox)",
    "    scale = torch.tensor([img_w, img_h, img_w, img_h], dtype=torch.float32)",
    "    return b * scale",
  ];
  const detrInferenceProblem = [
    "# PIL 이미지에 전처리를 적용하고 배치 차원을 추가합니다.",
    "img = transform(im).????(0)",
    "outputs = ????(img)",
    "# no-object인 마지막 클래스를 제외합니다.",
    "probas = outputs['pred_logits'].????(-1)[0, :, :-1]",
    "# 가장 높은 클래스 확률이 0.9를 넘는 query만 선택합니다.",
    "keep = probas.????(-1).values > 0.9",
    "bboxes_scaled = rescale_bboxes(outputs['pred_boxes'][0, ????], im.size)",
  ];
  const detrInferenceAnswer = [
    "# PIL 이미지에 전처리를 적용하고 배치 차원을 추가합니다.",
    "img = transform(im).unsqueeze(0)",
    "outputs = model(img)",
    "# no-object인 마지막 클래스를 제외합니다.",
    "probas = outputs['pred_logits'].softmax(-1)[0, :, :-1]",
    "# 가장 높은 클래스 확률이 0.9를 넘는 query만 선택합니다.",
    "keep = probas.max(-1).values > 0.9",
    "bboxes_scaled = rescale_bboxes(outputs['pred_boxes'][0, keep], im.size)",
  ];
  const detrHooksProblem = [
    "conv_features, enc_attn_weights, dec_attn_weights = [], [], []",
    "hooks = [",
    "    model.backbone[-2].????(",
    "        lambda self, input, output: conv_features.append(output)),",
    "    model.transformer.encoder.layers[-1].self_attn.register_forward_hook(",
    "        lambda self, input, output: enc_attn_weights.append(output[????])),",
    "    model.transformer.decoder.layers[-1].multihead_attn.register_forward_hook(",
    "        lambda self, input, output: dec_attn_weights.append(output[????])),",
    "]",
    "outputs = model(img)",
    "for hook in hooks:",
    "    hook.????()",
  ];
  const detrHooksAnswer = [
    "conv_features, enc_attn_weights, dec_attn_weights = [], [], []",
    "hooks = [",
    "    model.backbone[-2].register_forward_hook(",
    "        lambda self, input, output: conv_features.append(output)),",
    "    model.transformer.encoder.layers[-1].self_attn.register_forward_hook(",
    "        lambda self, input, output: enc_attn_weights.append(output[1])),",
    "    model.transformer.decoder.layers[-1].multihead_attn.register_forward_hook(",
    "        lambda self, input, output: dec_attn_weights.append(output[1])),",
    "]",
    "outputs = model(img)",
    "for hook in hooks:",
    "    hook.remove()",
  ];
  const detrAttentionProblem = [
    "f_map = conv_features['0']",
    "shape = f_map.tensors.shape[????:]",
    "# 펼쳐진 HW×HW attention을 H×W×H×W로 복원합니다.",
    "sattn = enc_attn_weights[0].????(shape + shape)",
    "h, w = conv_features['0'].tensors.shape[-2:]",
    "# 선택된 object query의 decoder cross-attention을 2차원으로 봅니다.",
    "query_map = dec_attn_weights[0, idx].????(h, w)",
  ];
  const detrAttentionAnswer = [
    "f_map = conv_features['0']",
    "shape = f_map.tensors.shape[-2:]",
    "# 펼쳐진 HW×HW attention을 H×W×H×W로 복원합니다.",
    "sattn = enc_attn_weights[0].reshape(shape + shape)",
    "h, w = conv_features['0'].tensors.shape[-2:]",
    "# 선택된 object query의 decoder cross-attention을 2차원으로 봅니다.",
    "query_map = dec_attn_weights[0, idx].view(h, w)",
  ];
  window.LLM_COURSE = {
    subject: "2. Vision",
    sample_mode: true,
    cells: {
      "v-01": { source: "T.RandomCrop(32, padding=4)" },
      "v-02": { source: "T.RandomHorizontalFlip()" },
      "v-03": { source: "T.ToTensor()" },
      "v-04": { source: "T.Normalize(CIFAR10_MEAN, CIFAR10_STD)" },
      "v-05": { source: "DataLoader(train_set, batch_size=batch_size, shuffle=True)" },
      "v-06": { source: "nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)" },
      "v-07": { source: "nn.Linear(model.fc.in_features, num_classes)" },
      "v-08": { source: "logits = model(images)" },
      "v-09": { source: "scaler.scale(loss).backward()" },
      "v-10": { source: "preds = logits.argmax(dim=1)" },
      "vit-01": { source: "self.to_qkv(x).chunk(3, dim=-1)" },
      "vit-02": { source: "einsum('b h i d, b h j d -> b h i j', q, k)" },
      "vit-03": { source: "self.attend(dots)" },
      "vit-04": { source: "nn.Linear(patch_dim, cfg.dim)" },
      "vit-05": { source: "nn.Parameter(torch.randn(1, 1, cfg.dim))" },
      "vit-06": { source: "torch.cat((cls_tokens, x), dim=1)" },
      "vit-07": { source: "self.transformer(x)" },
      "vit-08": { source: "x[:, 0]" },
      "vit-09": { source: "x = attn(x) + x" },
      "vit-10": { source: "loss.backward()" },
      "vit-11": { source: "optimizer.step()" },
      "vit-12": { source: "torch.max(output, dim=1)" },
      "detr-01": { source: "T.Resize(800)" },
      "detr-02": { source: "T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])" },
      "detr-03": { source: "x.unbind(1)" },
      "detr-04": { source: "torch.stack(b, dim=1)" },
      "detr-05": { source: "box_cxcywh_to_xyxy(out_bbox)" },
      "detr-06": { source: "transform(im).unsqueeze(0)" },
      "detr-07": { source: "outputs['pred_logits'].softmax(-1)[0, :, :-1]" },
      "detr-08": { source: "probas.max(-1).values > 0.9" },
      "detr-09": { source: "outputs['pred_boxes'][0, keep]" },
      "detr-10": { source: "register_forward_hook" },
      "detr-11": { source: "output[1]" },
      "detr-12": { source: "hook.remove()" },
      "detr-13": { source: "reshape(shape + shape)" },
      "detr-14": { source: "view(h, w)" },
    },
    chapters: [{
      id: "vision-01", number: "01", title: "ResNet18 & CIFAR-10", file: "01_ResNet18_CIFAR10.ipynb",
      capability: "CIFAR-10 이미지 분류를 위해 변형·ResNet18·학습 루프·Accuracy를 연결해 구현할 수 있다.",
      summary: "이미지 데이터가 Transform과 DataLoader를 거쳐 [B,C,H,W] Tensor가 되고, ResNet의 logits를 정답과 비교해 학습하는 흐름입니다.",
      notebook_goal: "CIFAR-10 이미지를 증강·정규화하고, ResNet18을 10개 클래스 분류기에 맞춰 학습·평가하는 파이프라인을 구현한다.",
      key_points: [
        { title: "학습 이미지 증강", purpose: "학습 데이터에만 crop과 flip을 적용해 같은 이미지의 다양한 모습을 학습합니다.", code: "T.RandomCrop(32, padding=4)\nT.RandomHorizontalFlip()", flow: "PIL → 증강된 PIL", watch: "평가 데이터에는 무작위 증강을 넣지 않습니다." },
        { title: "이미지 Tensor와 정규화", purpose: "ToTensor는 이미지를 [C,H,W] float Tensor로, Normalize는 채널별 분포를 맞춘 값으로 바꿉니다.", code: "T.ToTensor()\nT.Normalize(mean, std)", flow: "PIL → [C,H,W] float", watch: "Normalize는 ToTensor 뒤에 와야 합니다." },
        { title: "CIFAR용 ResNet 변경", purpose: "RGB 입력 채널 3개와 10개 클래스 출력에 맞게 첫 Conv와 마지막 Linear를 바꿉니다.", code: "nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1)\nnn.Linear(in_features, num_classes)", flow: "[B,3,32,32] → [B,10]", watch: "분류기의 출력 차원은 클래스 수입니다." },
        { title: "분류 학습과 Accuracy", purpose: "logits와 label로 loss를 만들고 backward 후 optimizer가 가중치를 갱신합니다.", code: "logits = model(images)\nloss.backward()\npreds = logits.argmax(dim=1)", flow: "[B,C], [B] → loss → gradient", watch: "argmax는 클래스 차원 dim=1에서 수행합니다." },
      ],
      theory_guide: [
        { title: "1. Data augmentation", concept: "증강은 학습 이미지에 무작위 변형을 적용해 새로운 입력처럼 보이게 만드는 방법입니다. 과적합을 줄이는 데 쓰입니다.", flow: "PIL → RandomCrop/Flip → Tensor", code_signal: "train_tfms에만 Random으로 시작하는 transform이 들어갑니다.", exam_clue: "crop은 크기와 padding, flip은 함수 호출 괄호를 함께 봅니다." },
        { title: "2. Tensor 입력 형태", concept: "이미지 분류 모델은 배치·채널·높이·너비 순서의 Tensor를 입력으로 받습니다.", flow: "[B, C, H, W] = [batch, 3, 32, 32]", code_signal: "RGB 이미지의 Conv2d 첫 입력 채널은 3입니다.", exam_clue: "CIFAR-10은 RGB이므로 1이 아니라 3입니다." },
        { title: "3. Logits와 CrossEntropyLoss", concept: "logits는 각 클래스에 대한 점수이며, CrossEntropyLoss가 정수 label과 비교해 학습 신호를 만듭니다.", flow: "model(images) [B,10] + labels [B] → loss", code_signal: "criterion(logits, labels) 앞에서는 model(images)가 필요합니다.", exam_clue: "softmax를 따로 넣지 않고 raw logits를 CrossEntropyLoss에 전달합니다." },
        { title: "4. 예측과 Accuracy", concept: "가장 큰 logit의 위치가 모델이 고른 클래스입니다. 이를 label과 비교해 맞은 비율을 구합니다.", flow: "[B,10] → argmax(dim=1) → [B]", code_signal: "클래스 차원이 두 번째 축이면 dim=1입니다.", exam_clue: "argmax는 값이 아니라 class index를 반환합니다." },
      ],
      full_code_cells: [cell(1, transformProblem, transformAnswer, [1,2,3,4,6]), cell(2, modelProblem, modelAnswer, [1,3]), cell(3, trainProblem, trainAnswer, [1,3,6])],
      subjective: [
        { id:"v-q1", sourceId:"v-01", occurrence:0, answer:"RandomCrop", accepted_answers:["RandomCrop"], topic:"학습 증강", prompt:"32×32 crop과 padding=4를 적용하는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q2", sourceId:"v-02", occurrence:0, answer:"RandomHorizontalFlip", accepted_answers:["RandomHorizontalFlip"], topic:"학습 증강", prompt:"좌우 반전을 무작위로 적용하는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q3", sourceId:"v-03", occurrence:0, answer:"ToTensor", accepted_answers:["ToTensor"], topic:"Tensor 변환", prompt:"PIL 이미지를 [C,H,W] Tensor로 바꾸는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q4", sourceId:"v-04", occurrence:0, answer:"Normalize", accepted_answers:["Normalize"], topic:"정규화", prompt:"채널별 mean과 std로 정규화하는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q5", sourceId:"v-05", occurrence:0, answer:"shuffle", accepted_answers:["shuffle"], topic:"DataLoader", prompt:"학습 배치의 순서를 매 epoch 섞는 인자 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q6", sourceId:"v-06", occurrence:0, answer:"3", accepted_answers:["3"], topic:"ResNet 입력", prompt:"CIFAR-10 RGB 입력의 Conv2d in_channels를 채우세요.", isSourceBlank:false },
        { id:"v-q7", sourceId:"v-07", occurrence:0, answer:"num_classes", accepted_answers:["num_classes","10"], topic:"ResNet 출력", prompt:"마지막 분류기의 출력 차원을 클래스 수로 맞추는 변수를 채우세요.", isSourceBlank:false },
        { id:"v-q8", sourceId:"v-08", occurrence:0, answer:"model", accepted_answers:["model"], topic:"학습", prompt:"images를 입력해 logits를 만드는 호출 대상을 채우세요.", isSourceBlank:false },
        { id:"v-q9", sourceId:"v-09", occurrence:0, answer:"backward", accepted_answers:["backward"], topic:"역전파", prompt:"scaled loss에서 gradient를 계산하는 메서드 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q10", sourceId:"v-10", occurrence:0, answer:"argmax", accepted_answers:["argmax"], topic:"예측", prompt:"클래스 점수에서 가장 높은 클래스 index를 고르는 메서드 이름을 채우세요.", isSourceBlank:false },
      ],
      mcq: [
        { id:"v-m1", source_question_id:"v-q4", topic:"Tensor 변환 순서", prompt:"PIL 이미지를 정규화하려면 빈칸에 무엇이 들어가야 하나요?", answer_index:1, explanation:"Normalize는 Tensor를 입력으로 받으므로 ToTensor 다음에 사용합니다.", choices:[{text:"RandomCrop",why:"공간 증강입니다."},{text:"Normalize",why:"정답: 채널별 정규화입니다."},{text:"DataLoader",why:"배치 생성 객체입니다."},{text:"argmax",why:"예측 class 선택 메서드입니다."},{text:"backward",why:"역전파 메서드입니다."}] },
        { id:"v-m2", source_question_id:"v-q6", topic:"RGB 입력 채널", prompt:"CIFAR-10용 첫 Conv의 입력 채널 수는?", answer_index:2, explanation:"CIFAR-10 이미지는 RGB이므로 채널 수가 3입니다.", choices:[{text:"1",why:"흑백 이미지 채널 수입니다."},{text:"10",why:"클래스 수입니다."},{text:"3",why:"정답: RGB 채널 수입니다."},{text:"32",why:"이미지 높이·너비입니다."},{text:"64",why:"첫 Conv의 출력 채널입니다."}] },
        { id:"v-m3", source_question_id:"v-q10", topic:"예측 class", prompt:"logits [B, C]에서 클래스 index [B]를 얻는 표현은?", answer_index:0, explanation:"C가 두 번째 차원이므로 argmax(dim=1)입니다.", choices:[{text:"argmax",why:"정답: 빈칸 뒤의 (dim=1)과 합쳐져 class index를 만듭니다."},{text:"softmax",why:"확률은 만들지만 index를 고르지 않습니다."},{text:"backward",why:"gradient 계산입니다."},{text:"Normalize",why:"이미지 변환입니다."},{text:"shuffle",why:"DataLoader 인자입니다."}] },
      ],
    }, {
      id: "vision-02",
      number: "02",
      title: "ViT & CIFAR-10",
      file: "02_ViT_CIFAR10.ipynb",
      capability: "이미지를 패치 토큰으로 바꾸고 Self-Attention과 CLS 토큰을 거쳐 분류 logits를 만드는 ViT를 구현할 수 있다.",
      summary: "[B,3,32,32] 이미지가 64개 패치와 CLS 토큰을 포함한 [B,65,dim] 시퀀스가 되고, Transformer Encoder와 분류 헤드를 거쳐 [B,10] logits가 됩니다.",
      notebook_goal: "CIFAR-10 이미지를 패치 시퀀스로 변환하고 멀티헤드 Self-Attention 기반 Vision Transformer로 분류하는 전체 흐름을 구현한다.",
      key_points: [
        { title:"패치 토큰화", purpose:"이미지를 겹치지 않는 패치로 나누고 각 패치를 Transformer 차원으로 투영합니다.", code:"Rearrange(...)\nnn.Linear(patch_dim, dim)", flow:"[B,C,H,W] → [B,N,patch_dim] → [B,N,dim]", watch:"N=(H/Ph)×(W/Pw), patch_dim=C×Ph×Pw입니다." },
        { title:"Q·K·V Self-Attention", purpose:"각 토큰이 다른 토큰을 얼마나 참고할지 계산합니다.", code:"qkv.chunk(3)\ndots = QKᵀ / √d\nattn @ V", flow:"[B,N,dim] → [B,H,N,d] → [B,H,N,N] → [B,N,dim]", watch:"Softmax는 토큰 점수의 마지막 차원에 적용합니다." },
        { title:"CLS와 위치 정보", purpose:"CLS 토큰은 전체 이미지 표현을 모으고 위치 임베딩은 패치 순서를 알려줍니다.", code:"torch.cat((cls_tokens, x), dim=1)\nx + pos_embedding", flow:"[B,N,dim] → [B,N+1,dim]", watch:"위치 임베딩 길이도 num_patches+1이어야 합니다." },
        { title:"학습과 평가", purpose:"log-probability와 정답 label로 loss를 만들고 평가에서는 gradient 없이 정확도를 계산합니다.", code:"F.log_softmax\nF.nll_loss\nloss.backward()\noptimizer.step()", flow:"[B,10]+[B] → loss → gradient → update", watch:"log_softmax와 nll_loss는 한 쌍이며 CrossEntropyLoss로 대체할 수 있습니다." },
      ],
      theory_guide: [
        { title:"1. Patch Embedding", concept:"패치 임베딩은 2차원 이미지를 Transformer가 처리할 수 있는 토큰 시퀀스로 바꾸는 단계입니다.", flow:"32×32, patch 4×4 → 8×8=64 tokens", code_signal:"Rearrange 뒤의 Linear가 펼친 패치를 cfg.dim으로 투영합니다.", exam_clue:"패치 수와 패치 차원을 서로 바꾸지 않도록 구분합니다." },
        { title:"2. Scaled Dot-Product Attention", concept:"Query와 Key의 내적으로 관련도를 구하고 √d로 나눈 뒤 Softmax를 적용하여 Value를 가중합합니다.", flow:"QKᵀ/√d → Softmax → Attention×V", code_signal:"einsum 두 번 사이에 Softmax가 위치합니다.", exam_clue:"첫 einsum은 q,k이고 두 번째 einsum은 attn,v입니다." },
        { title:"3. CLS·Position·Residual", concept:"CLS는 분류용 대표 토큰, Position은 공간 순서, Residual은 원래 정보를 보존하는 덧셈 연결입니다.", flow:"tokens → +CLS → +position → Encoder residual", code_signal:"cat은 dim=1, residual은 block(x)+x입니다.", exam_clue:"CLS의 index는 0이며 위치 임베딩에는 CLS 자리까지 포함됩니다." },
        { title:"4. Tensor 흐름", concept:"ViT는 토큰 개수 축을 유지한 채 Encoder를 통과하고 마지막에 CLS 또는 mean으로 토큰 축을 제거합니다.", flow:"[B,65,64] → [B,65,64] → [B,64] → [B,10]", code_signal:"x[:,0] 또는 x.mean(dim=1) 뒤 mlp_head를 호출합니다.", exam_clue:"분류 결과는 확률이 아니라 raw logits 또는 log_softmax 결과입니다." },
      ],
      full_code_cells: [
        cell(1, vitAttentionProblem, vitAttentionAnswer, [3,5,6,7]),
        cell(2, vitPatchProblem, vitPatchAnswer, [1,5,7]),
        cell(3, vitForwardProblem, vitForwardAnswer, [1,4,7,8]),
        cell(4, vitTransformerProblem, vitTransformerAnswer, [3,5]),
        cell(5, vitTrainProblem, vitTrainAnswer, [1,2,3,4,8,9]),
      ],
      subjective: [
        {id:"vit-q1",sourceId:"vit-01",occurrence:0,answer:"chunk",accepted_answers:["chunk"],topic:"QKV 분할",prompt:"QKV 선형변환 결과를 3개로 나누는 메서드를 채우세요.",isSourceBlank:false},
        {id:"vit-q2",sourceId:"vit-02",occurrence:0,answer:"q, k",accepted_answers:["q,k","q, k"],topic:"Attention score",prompt:"토큰 간 관련도 행렬을 만드는 두 입력을 순서대로 채우세요.",isSourceBlank:false},
        {id:"vit-q3",sourceId:"vit-03",occurrence:0,answer:"attend",accepted_answers:["attend","self.attend"],topic:"Softmax",prompt:"dots를 attention 확률로 바꾸는 모듈 이름을 채우세요.",isSourceBlank:false},
        {id:"vit-q4",sourceId:"vit-04",occurrence:0,answer:"Linear",accepted_answers:["Linear","nn.Linear"],topic:"Patch projection",prompt:"patch_dim을 cfg.dim으로 투영하는 layer를 채우세요.",isSourceBlank:false},
        {id:"vit-q5",sourceId:"vit-05",occurrence:0,answer:"Parameter",accepted_answers:["Parameter","nn.Parameter"],topic:"CLS token",prompt:"CLS 토큰을 학습 가능한 파라미터로 등록하는 클래스를 채우세요.",isSourceBlank:false},
        {id:"vit-q6",sourceId:"vit-06",occurrence:0,answer:"cat",accepted_answers:["cat","torch.cat"],topic:"CLS 결합",prompt:"CLS 토큰을 패치 시퀀스 앞에 연결하는 함수를 채우세요.",isSourceBlank:false},
        {id:"vit-q7",sourceId:"vit-07",occurrence:0,answer:"transformer",accepted_answers:["transformer","self.transformer"],topic:"Encoder",prompt:"토큰 시퀀스를 Encoder에 통과시키는 모듈 이름을 채우세요.",isSourceBlank:false},
        {id:"vit-q8",sourceId:"vit-08",occurrence:0,answer:"0",accepted_answers:["0"],topic:"CLS pooling",prompt:"CLS pooling에서 선택할 토큰 index를 채우세요.",isSourceBlank:false},
        {id:"vit-q9",sourceId:"vit-09",occurrence:0,answer:"attn",accepted_answers:["attn"],topic:"Residual",prompt:"첫 residual 연결에서 x에 더할 블록 호출 대상을 채우세요.",isSourceBlank:false},
        {id:"vit-q10",sourceId:"vit-10",occurrence:0,answer:"backward",accepted_answers:["backward"],topic:"역전파",prompt:"loss에서 gradient를 계산하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"vit-q11",sourceId:"vit-11",occurrence:0,answer:"step",accepted_answers:["step"],topic:"가중치 갱신",prompt:"optimizer가 계산된 gradient로 파라미터를 갱신하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"vit-q12",sourceId:"vit-12",occurrence:0,answer:"max",accepted_answers:["max","torch.max"],topic:"예측",prompt:"log-probability에서 최댓값과 class index를 얻는 함수를 채우세요.",isSourceBlank:false},
      ],
      mcq: [
        {id:"vit-m1",source_question_id:"vit-q2",topic:"QK score",prompt:"Self-Attention에서 Softmax 직전 토큰 간 점수를 만드는 조합은?",answer_index:1,explanation:"Query와 Key의 내적이 각 토큰 쌍의 관련도 점수를 만듭니다.",choices:[{text:"Q와 V",why:"Value는 점수 계산 뒤 가중합에 쓰입니다."},{text:"Q와 K",why:"정답: QKᵀ가 관련도 점수입니다."},{text:"K와 V",why:"Query가 빠져 어떤 토큰의 관심인지 알 수 없습니다."},{text:"V와 V",why:"내용끼리의 내적은 attention score 정의가 아닙니다."},{text:"Attention과 K",why:"Attention 확률은 이미 score 이후 결과입니다."}]},
        {id:"vit-m2",source_question_id:"vit-q6",topic:"CLS 연결 축",prompt:"[B,N,D] 패치 토큰 앞에 [B,1,D] CLS 토큰을 붙일 축은?",answer_index:2,explanation:"토큰 개수 N이 있는 두 번째 축(dim=1)을 늘려야 합니다.",choices:[{text:"dim=0",why:"배치 수가 늘어납니다."},{text:"dim=-1",why:"임베딩 차원이 늘어납니다."},{text:"dim=1",why:"정답: 토큰 축입니다."},{text:"dim=2",why:"임베딩 축입니다."},{text:"축 지정 불필요",why:"cat은 연결 축이 필수입니다."}]},
        {id:"vit-m3",source_question_id:"vit-q10",topic:"학습 순서",prompt:"loss 계산 뒤 올바른 학습 순서는?",answer_index:0,explanation:"gradient를 계산한 뒤 optimizer가 그 gradient로 파라미터를 갱신합니다.",choices:[{text:"loss.backward() → optimizer.step()",why:"정답입니다."},{text:"optimizer.step() → loss.backward()",why:"gradient 계산 전에 갱신할 수 없습니다."},{text:"model.eval() → optimizer.step()",why:"평가 모드는 학습 순서가 아닙니다."},{text:"torch.no_grad() → loss.backward()",why:"no_grad 안에서는 역전파 그래프가 없습니다."},{text:"argmax() → backward()",why:"argmax는 미분 가능한 학습 손실이 아닙니다."}]},
      ],
    }, {
      id: "vision-03",
      number: "03",
      title: "DETR Object Detection",
      file: "03_DETR.ipynb",
      capability: "DETR 입력을 전처리하고 object query의 클래스·박스 출력을 필터링하여 원본 이미지 좌표로 복원할 수 있다.",
      summary: "PIL 이미지가 [1,3,H,W] Tensor로 바뀌고, DETR의 고정 개수 object query가 class logits와 정규화된 박스를 출력한 뒤 confidence 필터와 좌표 복원을 거칩니다.",
      notebook_goal: "DETR의 전처리, 클래스·박스 후처리, object query 필터링, encoder·decoder attention 추출 과정을 코드로 구현한다.",
      key_points: [
        { title:"입력 전처리", purpose:"ResNet-50 backbone의 사전학습 분포에 맞춰 이미지 크기와 채널 분포를 맞춥니다.", code:"T.Resize(800)\nT.ToTensor()\nT.Normalize(ImageNet mean, std)", flow:"PIL → [3,H,W] → [1,3,H,W]", watch:"모델 호출 전 unsqueeze(0)으로 배치 축을 추가합니다." },
        { title:"박스 좌표 복원", purpose:"정규화된 중심 좌표 박스를 원본 이미지 픽셀의 꼭짓점 좌표로 바꿉니다.", code:"(cx,cy,w,h) → (xmin,ymin,xmax,ymax)\n× [W,H,W,H]", flow:"[N,4] normalized → [N,4] pixels", watch:"PIL size 순서는 (width, height)입니다." },
        { title:"Object query 필터", purpose:"no-object 클래스를 제외하고 실제 객체일 확률이 높은 query만 남깁니다.", code:"softmax(-1)[0,:,:-1]\nmax(-1).values > 0.9", flow:"[1,Q,C+1] → [Q,C] → [Q] bool", watch:"마지막 클래스가 no-object이므로 :-1로 제외합니다." },
        { title:"Attention hook", purpose:"forward 중 backbone feature와 encoder·decoder attention weight를 저장합니다.", code:"register_forward_hook(... output[1])\nhook.remove()", flow:"module output → list → tensor", watch:"사용 후 hook을 제거해야 다음 forward에서 중복 저장되지 않습니다." },
      ],
      theory_guide: [
        { title:"1. DETR 출력 구조", concept:"DETR은 고정 개수의 object query마다 클래스와 박스를 동시에 예측하며 객체가 없는 query는 no-object로 분류합니다.", flow:"image → backbone → encoder → decoder queries → class/box heads", code_signal:"pred_logits와 pred_boxes가 같은 query 축을 공유합니다.", exam_clue:"클래스 확률 계산에서 마지막 no-object 슬롯을 제외합니다." },
        { title:"2. 좌표계 변환", concept:"모델의 박스는 중심점과 크기를 0~1로 표현하므로 시각화 전에 꼭짓점 좌표와 픽셀 단위로 바꿔야 합니다.", flow:"cxcywh → xyxy → pixel scale", code_signal:"unbind로 네 성분을 나눈 뒤 stack으로 다시 [N,4]를 만듭니다.", exam_clue:"xmin에는 cx-w/2, xmax에는 cx+w/2가 들어갑니다." },
        { title:"3. Boolean indexing", concept:"keep은 각 query를 유지할지 나타내는 bool Tensor이며 클래스 확률과 박스에 같은 마스크를 적용해야 대응이 보존됩니다.", flow:"[Q] keep → probas[keep], boxes[0,keep]", code_signal:"threshold 결과와 두 출력의 indexing을 함께 확인합니다.", exam_clue:"확률과 박스에 서로 다른 마스크를 쓰면 탐지 결과가 어긋납니다." },
        { title:"4. Encoder와 Decoder Attention", concept:"Encoder self-attention은 이미지 위치끼리, decoder cross-attention은 object query와 이미지 위치 사이의 관계를 나타냅니다.", flow:"encoder [HW,HW], decoder [Q,HW] → 2D map", code_signal:"reshape(shape+shape)와 view(h,w)가 각각 다른 attention을 복원합니다.", exam_clue:"encoder와 decoder hook 대상을 바꾸지 않도록 모듈 경로를 구분합니다." },
      ],
      full_code_cells: [
        cell(1, detrTransformProblem, detrTransformAnswer, [1,2,3,7,9]),
        cell(2, detrRescaleProblem, detrRescaleAnswer, [2,4]),
        cell(3, detrInferenceProblem, detrInferenceAnswer, [1,2,4,6,7]),
        cell(4, detrHooksProblem, detrHooksAnswer, [2,5,7,11]),
        cell(5, detrAttentionProblem, detrAttentionAnswer, [1,3,6]),
      ],
      subjective: [
        {id:"detr-q1",sourceId:"detr-01",occurrence:0,answer:"Resize",accepted_answers:["Resize","T.Resize"],topic:"전처리",prompt:"공식 DETR 데모에서 짧은 변을 800으로 맞추는 transform을 채우세요.",isSourceBlank:false},
        {id:"detr-q2",sourceId:"detr-02",occurrence:0,answer:"Normalize",accepted_answers:["Normalize","T.Normalize"],topic:"전처리",prompt:"ImageNet mean/std를 적용하는 transform을 채우세요.",isSourceBlank:false},
        {id:"detr-q3",sourceId:"detr-03",occurrence:0,answer:"unbind",accepted_answers:["unbind"],topic:"박스 변환",prompt:"[N,4] 박스 Tensor를 네 좌표 성분으로 분리하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q4",sourceId:"detr-04",occurrence:0,answer:"stack",accepted_answers:["stack","torch.stack"],topic:"박스 변환",prompt:"계산한 네 꼭짓점 좌표를 [N,4]로 결합하는 함수를 채우세요.",isSourceBlank:false},
        {id:"detr-q5",sourceId:"detr-05",occurrence:0,answer:"box_cxcywh_to_xyxy",accepted_answers:["box_cxcywh_to_xyxy"],topic:"좌표 복원",prompt:"픽셀 스케일을 곱하기 전에 박스를 xyxy로 바꾸는 함수를 채우세요.",isSourceBlank:false},
        {id:"detr-q6",sourceId:"detr-06",occurrence:0,answer:"unsqueeze",accepted_answers:["unsqueeze"],topic:"배치 축",prompt:"한 장의 [C,H,W] 입력에 배치 축을 추가하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q7",sourceId:"detr-07",occurrence:0,answer:"softmax",accepted_answers:["softmax"],topic:"클래스 확률",prompt:"pred_logits를 query별 클래스 확률로 바꾸는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q8",sourceId:"detr-08",occurrence:0,answer:"max",accepted_answers:["max"],topic:"신뢰도 필터",prompt:"각 query의 최고 클래스 확률을 구하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q9",sourceId:"detr-09",occurrence:0,answer:"keep",accepted_answers:["keep"],topic:"Boolean indexing",prompt:"확률 기준을 통과한 박스만 고르는 bool 마스크를 채우세요.",isSourceBlank:false},
        {id:"detr-q10",sourceId:"detr-10",occurrence:0,answer:"register_forward_hook",accepted_answers:["register_forward_hook"],topic:"Hook",prompt:"모듈의 forward 출력을 캡처하도록 hook을 등록하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q11",sourceId:"detr-11",occurrence:0,answer:"1",accepted_answers:["1"],topic:"Attention weight",prompt:"MultiheadAttention 출력 tuple에서 attention weight의 index를 채우세요.",isSourceBlank:false},
        {id:"detr-q12",sourceId:"detr-12",occurrence:0,answer:"remove",accepted_answers:["remove"],topic:"Hook 해제",prompt:"사용이 끝난 forward hook을 해제하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q13",sourceId:"detr-13",occurrence:0,answer:"reshape",accepted_answers:["reshape"],topic:"Encoder attention",prompt:"[HW,HW] self-attention을 [H,W,H,W]로 복원하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q14",sourceId:"detr-14",occurrence:0,answer:"view",accepted_answers:["view"],topic:"Decoder attention",prompt:"object query의 [HW] cross-attention을 [H,W]로 보는 메서드를 채우세요.",isSourceBlank:false},
      ],
      mcq: [
        {id:"detr-m1",source_question_id:"detr-q7",topic:"no-object 제외",prompt:"pred_logits에서 실제 COCO 클래스 확률만 얻는 올바른 흐름은?",answer_index:2,explanation:"클래스 축에 softmax를 적용한 뒤 마지막 no-object 슬롯을 제외합니다.",choices:[{text:"sigmoid 후 첫 클래스 제외",why:"공식 데모 흐름과 다르고 no-object는 마지막입니다."},{text:"argmax 후 softmax",why:"argmax를 먼저 하면 클래스별 확률이 사라집니다."},{text:"softmax(-1) 후 [..., :-1]",why:"정답입니다."},{text:"softmax(0) 후 배치 제거",why:"배치 축에 정규화하면 query별 클래스 확률이 아닙니다."},{text:"pred_boxes에 softmax",why:"박스 좌표는 클래스 logits가 아닙니다."}]},
        {id:"detr-m2",source_question_id:"detr-q5",topic:"박스 좌표",prompt:"(cx,cy,w,h)에서 xmin을 구하는 식은?",answer_index:1,explanation:"중심 x에서 폭의 절반을 빼면 왼쪽 꼭짓점입니다.",choices:[{text:"cx-w",why:"폭 전체를 빼면 너무 멀리 이동합니다."},{text:"cx-0.5*w",why:"정답입니다."},{text:"cx+0.5*w",why:"xmax입니다."},{text:"w-0.5*cx",why:"중심과 폭의 역할이 뒤바뀌었습니다."},{text:"cx/w",why:"좌표 변환식이 아닙니다."}]},
        {id:"detr-m3",source_question_id:"detr-q11",topic:"Attention 종류",prompt:"object query가 이미지의 어느 위치를 참고했는지 볼 대상은?",answer_index:3,explanation:"Decoder cross-attention이 query와 encoder 이미지 위치 사이의 관계를 나타냅니다.",choices:[{text:"backbone convolution weight",why:"필터 자체이지 특정 query의 관심 위치가 아닙니다."},{text:"encoder self-attention만",why:"이미지 위치끼리의 관계이며 object query 축이 없습니다."},{text:"class_embed bias",why:"분류 head의 편향입니다."},{text:"decoder multihead cross-attention",why:"정답입니다."},{text:"optimizer state",why:"학습 상태이며 attention이 아닙니다."}]},
      ],
    }],
  };
})();
