(() => {
  const line = (text, highlight = false) => ({ text, highlight });
  const cell = (cell_number, problem, answer, marked) => ({
    cell_number,
    blank_count: marked.length,
    problem_lines: problem.map((text, i) => line(text, marked.includes(i))),
    answer_lines: answer.map((text, i) => line(text, marked.includes(i))),
  });
  const transformProblem = [
    "train_tfms = T.Compose([",
    "    T.????(32, padding=4),",
    "    T.????(),",
    "    T.????(),  # PIL → Tensor (C, H, W), 0~1",
    "    T.????(CIFAR10_MEAN, CIFAR10_STD),",
    "]) ",
    "train_loader = DataLoader(train_set, batch_size=batch_size, ????=True)",
  ];
  const transformAnswer = [
    "train_tfms = T.Compose([",
    "    T.RandomCrop(32, padding=4),",
    "    T.RandomHorizontalFlip(),",
    "    T.ToTensor(),  # PIL → Tensor (C, H, W), 0~1",
    "    T.Normalize(CIFAR10_MEAN, CIFAR10_STD),",
    "]) ",
    "train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)",
  ];
  const modelProblem = [
    "model = models.resnet18(weights=None)",
    "model.conv1 = nn.Conv2d(????, 64, kernel_size=3, stride=1, padding=1, bias=False)",
    "model.maxpool = nn.Identity()",
    "model.fc = nn.Linear(model.fc.in_features, ????)",
  ];
  const modelAnswer = [
    "model = models.resnet18(weights=None)",
    "model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)",
    "model.maxpool = nn.Identity()",
    "model.fc = nn.Linear(model.fc.in_features, num_classes)",
  ];
  const trainProblem = [
    "optimizer.zero_grad(set_to_none=True)",
    "logits = ????(images)",
    "loss = criterion(logits, labels)",
    "scaler.scale(loss).????()",
    "scaler.step(optimizer)",
    "scaler.update()",
    "preds = logits.????(dim=1)",
  ];
  const trainAnswer = [
    "optimizer.zero_grad(set_to_none=True)",
    "logits = model(images)",
    "loss = criterion(logits, labels)",
    "scaler.scale(loss).backward()",
    "scaler.step(optimizer)",
    "scaler.update()",
    "preds = logits.argmax(dim=1)",
  ];
  const vitAttentionProblem = [
    "class Attention(nn.Module):",
    "    def forward(self, x):",
    "        b, n, _, h = *x.shape, self.heads",
    "        qkv = self.to_qkv(x).????(3, dim=-1)",
    "        q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h=h), qkv)",
    "        dots = einsum('b h i d, b h j d -> b h i j', ????, ????) * self.scale",
    "        attn = self.????(dots)",
    "        out = einsum('b h i j, b h j d -> b h i d', attn, ????)",
    "        out = rearrange(out, 'b h n d -> b n (h d)')",
    "        return self.to_out(out)",
  ];
  const vitAttentionAnswer = [
    "class Attention(nn.Module):",
    "    def forward(self, x):",
    "        b, n, _, h = *x.shape, self.heads",
    "        qkv = self.to_qkv(x).chunk(3, dim=-1)",
    "        q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h=h), qkv)",
    "        dots = einsum('b h i d, b h j d -> b h i j', q, k) * self.scale",
    "        attn = self.attend(dots)",
    "        out = einsum('b h i j, b h j d -> b h i d', attn, v)",
    "        out = rearrange(out, 'b h n d -> b n (h d)')",
    "        return self.to_out(out)",
  ];
  const vitPatchProblem = [
    "num_patches = (image_height // patch_height) * (image_width // patch_width)",
    "patch_dim = cfg.???? * patch_height * patch_width",
    "self.to_patch_embedding = nn.Sequential(",
    "    Rearrange('b c (h p1) (w p2) -> b (h w) (p1 p2 c)',",
    "              p1=patch_height, p2=patch_width),",
    "    nn.????(patch_dim, cfg.dim),",
    ")",
    "self.cls_token = nn.????(torch.randn(1, 1, cfg.dim))",
    "self.pos_embedding = nn.Parameter(torch.randn(1, num_patches + 1, cfg.dim))",
  ];
  const vitPatchAnswer = [
    "num_patches = (image_height // patch_height) * (image_width // patch_width)",
    "patch_dim = cfg.channels * patch_height * patch_width",
    "self.to_patch_embedding = nn.Sequential(",
    "    Rearrange('b c (h p1) (w p2) -> b (h w) (p1 p2 c)',",
    "              p1=patch_height, p2=patch_width),",
    "    nn.Linear(patch_dim, cfg.dim),",
    ")",
    "self.cls_token = nn.Parameter(torch.randn(1, 1, cfg.dim))",
    "self.pos_embedding = nn.Parameter(torch.randn(1, num_patches + 1, cfg.dim))",
  ];
  const vitForwardProblem = [
    "def forward(self, img):",
    "    x = self.????(img)",
    "    b, n, _ = x.shape",
    "    cls_tokens = repeat(self.cls_token, '1 1 d -> b 1 d', b=b)",
    "    x = torch.????((cls_tokens, x), dim=1)",
    "    x = x + self.pos_embedding[:, : (n + 1)]",
    "    x = self.dropout(x)",
    "    x = self.????(x)",
    "    x = x[:, 0] if self.pool == 'cls' else x.????(dim=1)",
    "    return self.mlp_head(x)",
  ];
  const vitForwardAnswer = [
    "def forward(self, img):",
    "    x = self.to_patch_embedding(img)",
    "    b, n, _ = x.shape",
    "    cls_tokens = repeat(self.cls_token, '1 1 d -> b 1 d', b=b)",
    "    x = torch.cat((cls_tokens, x), dim=1)",
    "    x = x + self.pos_embedding[:, : (n + 1)]",
    "    x = self.dropout(x)",
    "    x = self.transformer(x)",
    "    x = x[:, 0] if self.pool == 'cls' else x.mean(dim=1)",
    "    return self.mlp_head(x)",
  ];
  const vitTransformerProblem = [
    "def forward(self, x):",
    "    for attn, ff in self.layers:",
    "        # Attention 결과에 입력 x를 더하는 residual 연결",
    "        x = ????(x) + x",
    "        # FFN 결과에 입력 x를 더하는 residual 연결",
    "        x = ????(x) + x",
    "    return x",
  ];
  const vitTransformerAnswer = [
    "def forward(self, x):",
    "    for attn, ff in self.layers:",
    "        # Attention 결과에 입력 x를 더하는 residual 연결",
    "        x = attn(x) + x",
    "        # FFN 결과에 입력 x를 더하는 residual 연결",
    "        x = ff(x) + x",
    "    return x",
  ];
  const vitTrainProblem = [
    "optimizer.zero_grad()",
    "output = F.log_softmax(????(data), dim=1)",
    "loss = F.????(output, target)",
    "loss.????()",
    "optimizer.????()",
    "",
    "with torch.no_grad():",
    "    output = F.log_softmax(model(data), dim=1)",
    "    _, pred = torch.????(output, dim=1)",
    "    correct_samples += int(pred.????(target).sum().item())",
  ];
  const vitTrainAnswer = [
    "optimizer.zero_grad()",
    "output = F.log_softmax(model(data), dim=1)",
    "loss = F.nll_loss(output, target)",
    "loss.backward()",
    "optimizer.step()",
    "",
    "with torch.no_grad():",
    "    output = F.log_softmax(model(data), dim=1)",
    "    _, pred = torch.max(output, dim=1)",
    "    correct_samples += int(pred.eq(target).sum().item())",
  ];
  const detrTransformProblem = [
    "transform = T.Compose([",
    "    T.????(800),",
    "    T.????(),",
    "    T.????([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])",
    "])",
    "",
    "def box_cxcywh_to_xyxy(x):",
    "    x_c, y_c, w, h = x.????(1)",
    "    b = [x_c - 0.5*w, y_c - 0.5*h, x_c + 0.5*w, y_c + 0.5*h]",
    "    return torch.????(b, dim=1)",
  ];
  const detrTransformAnswer = [
    "transform = T.Compose([",
    "    T.Resize(800),",
    "    T.ToTensor(),",
    "    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])",
    "])",
    "",
    "def box_cxcywh_to_xyxy(x):",
    "    x_c, y_c, w, h = x.unbind(1)",
    "    b = [x_c - 0.5*w, y_c - 0.5*h, x_c + 0.5*w, y_c + 0.5*h]",
    "    return torch.stack(b, dim=1)",
  ];
  const detrRescaleProblem = [
    "def rescale_bboxes(out_bbox, size):",
    "    img_w, img_h = size",
    "    b = ????(out_bbox)",
    "    scale = torch.tensor([img_w, img_h, img_w, img_h], dtype=torch.float32)",
    "    return b ???? scale",
  ];
  const detrRescaleAnswer = [
    "def rescale_bboxes(out_bbox, size):",
    "    img_w, img_h = size",
    "    b = box_cxcywh_to_xyxy(out_bbox)",
    "    scale = torch.tensor([img_w, img_h, img_w, img_h], dtype=torch.float32)",
    "    return b * scale",
  ];
  const detrInferenceProblem = [
    "# PIL 이미지에 전처리를 적용하고 배치 차원을 추가합니다.",
    "img = transform(im).????(0)",
    "outputs = ????(img)",
    "# no-object인 마지막 클래스를 제외합니다.",
    "probas = outputs['pred_logits'].????(-1)[0, :, :-1]",
    "# 가장 높은 클래스 확률이 0.9를 넘는 query만 선택합니다.",
    "keep = probas.????(-1).values > 0.9",
    "bboxes_scaled = rescale_bboxes(outputs['pred_boxes'][0, ????], im.size)",
  ];
  const detrInferenceAnswer = [
    "# PIL 이미지에 전처리를 적용하고 배치 차원을 추가합니다.",
    "img = transform(im).unsqueeze(0)",
    "outputs = model(img)",
    "# no-object인 마지막 클래스를 제외합니다.",
    "probas = outputs['pred_logits'].softmax(-1)[0, :, :-1]",
    "# 가장 높은 클래스 확률이 0.9를 넘는 query만 선택합니다.",
    "keep = probas.max(-1).values > 0.9",
    "bboxes_scaled = rescale_bboxes(outputs['pred_boxes'][0, keep], im.size)",
  ];
  const detrHooksProblem = [
    "conv_features, enc_attn_weights, dec_attn_weights = [], [], []",
    "hooks = [",
    "    model.backbone[-2].????(",
    "        lambda self, input, output: conv_features.append(output)),",
    "    model.transformer.encoder.layers[-1].self_attn.register_forward_hook(",
    "        lambda self, input, output: enc_attn_weights.append(output[????])),",
    "    model.transformer.decoder.layers[-1].multihead_attn.register_forward_hook(",
    "        lambda self, input, output: dec_attn_weights.append(output[????])),",
    "]",
    "outputs = model(img)",
    "for hook in hooks:",
    "    hook.????()",
  ];
  const detrHooksAnswer = [
    "conv_features, enc_attn_weights, dec_attn_weights = [], [], []",
    "hooks = [",
    "    model.backbone[-2].register_forward_hook(",
    "        lambda self, input, output: conv_features.append(output)),",
    "    model.transformer.encoder.layers[-1].self_attn.register_forward_hook(",
    "        lambda self, input, output: enc_attn_weights.append(output[1])),",
    "    model.transformer.decoder.layers[-1].multihead_attn.register_forward_hook(",
    "        lambda self, input, output: dec_attn_weights.append(output[1])),",
    "]",
    "outputs = model(img)",
    "for hook in hooks:",
    "    hook.remove()",
  ];
  const detrAttentionProblem = [
    "f_map = conv_features['0']",
    "shape = f_map.tensors.shape[????:]",
    "# 펼쳐진 HW×HW attention을 H×W×H×W로 복원합니다.",
    "sattn = enc_attn_weights[0].????(shape + shape)",
    "h, w = conv_features['0'].tensors.shape[-2:]",
    "# 선택된 object query의 decoder cross-attention을 2차원으로 봅니다.",
    "query_map = dec_attn_weights[0, idx].????(h, w)",
  ];
  const detrAttentionAnswer = [
    "f_map = conv_features['0']",
    "shape = f_map.tensors.shape[-2:]",
    "# 펼쳐진 HW×HW attention을 H×W×H×W로 복원합니다.",
    "sattn = enc_attn_weights[0].reshape(shape + shape)",
    "h, w = conv_features['0'].tensors.shape[-2:]",
    "# 선택된 object query의 decoder cross-attention을 2차원으로 봅니다.",
    "query_map = dec_attn_weights[0, idx].view(h, w)",
  ];
  const unetDatasetProblem = [
    "def __getitem__(self, idx):",
    "    img = np.????((self.image_size, self.image_size), dtype=np.float32)",
    "    mask = np.zeros_like(img)",
    "    y, x = np.????[:self.image_size, :self.image_size]",
    "    dist = np.sqrt((x-center_x)**2 + (y-center_y)**2)",
    "    mask[dist <= radius] = 1.0",
    "    img = np.????(img, 0.0, 1.0)",
    "    img = np.????(img, axis=0)",
    "    mask = np.expand_dims(mask, axis=0)",
    "    return torch.????(img), torch.from_numpy(mask)",
  ];
  const unetDatasetAnswer = [
    "def __getitem__(self, idx):",
    "    img = np.zeros((self.image_size, self.image_size), dtype=np.float32)",
    "    mask = np.zeros_like(img)",
    "    y, x = np.ogrid[:self.image_size, :self.image_size]",
    "    dist = np.sqrt((x-center_x)**2 + (y-center_y)**2)",
    "    mask[dist <= radius] = 1.0",
    "    img = np.clip(img, 0.0, 1.0)",
    "    img = np.expand_dims(img, axis=0)",
    "    mask = np.expand_dims(mask, axis=0)",
    "    return torch.from_numpy(img), torch.from_numpy(mask)",
  ];
  const unetBlocksProblem = [
    "self.net = nn.Sequential(",
    "    nn.????(in_channels, mid_channels, kernel_size=3, padding=1, bias=False),",
    "    nn.????(inplace=True),",
    "    nn.Conv2d(mid_channels, out_channels, kernel_size=3, padding=1, bias=False),",
    "    nn.ReLU(inplace=True),",
    ")",
    "",
    "self.pool = nn.????(kernel_size=2)",
    "x = self.????(x)",
    "x = self.conv(x)",
  ];
  const unetBlocksAnswer = [
    "self.net = nn.Sequential(",
    "    nn.Conv2d(in_channels, mid_channels, kernel_size=3, padding=1, bias=False),",
    "    nn.ReLU(inplace=True),",
    "    nn.Conv2d(mid_channels, out_channels, kernel_size=3, padding=1, bias=False),",
    "    nn.ReLU(inplace=True),",
    ")",
    "",
    "self.pool = nn.MaxPool2d(kernel_size=2)",
    "x = self.pool(x)",
    "x = self.conv(x)",
  ];
  const unetUpProblem = [
    "def forward(self, x1, x2):",
    "    x1 = self.????(x1)",
    "    diff_y = x2.size(2) - x1.size(2)",
    "    diff_x = x2.size(3) - x1.size(3)",
    "    x1 = F.????(x1, [diff_x//2, diff_x-diff_x//2,",
    "                        diff_y//2, diff_y-diff_y//2])",
    "    # skip feature와 decoder feature를 채널 축으로 연결합니다.",
    "    x = torch.????([x2, x1], dim=????)",
    "    return self.conv(x)",
  ];
  const unetUpAnswer = [
    "def forward(self, x1, x2):",
    "    x1 = self.up(x1)",
    "    diff_y = x2.size(2) - x1.size(2)",
    "    diff_x = x2.size(3) - x1.size(3)",
    "    x1 = F.pad(x1, [diff_x//2, diff_x-diff_x//2,",
    "                        diff_y//2, diff_y-diff_y//2])",
    "    # skip feature와 decoder feature를 채널 축으로 연결합니다.",
    "    x = torch.cat([x2, x1], dim=1)",
    "    return self.conv(x)",
  ];
  const unetForwardProblem = [
    "def forward(self, x):",
    "    x1 = self.????(x)",
    "    x2 = self.down1(x1)",
    "    x3 = self.down2(x2)",
    "    x4 = self.down3(x3)",
    "    x5 = self.down4(x4)",
    "    x = self.up1(x5, ???? )",
    "    x = self.up2(x, ???? )",
    "    x = self.up3(x, ???? )",
    "    x = self.up4(x, ???? )",
    "    logits = self.????(x)",
    "    return logits",
  ];
  const unetForwardAnswer = [
    "def forward(self, x):",
    "    x1 = self.inc(x)",
    "    x2 = self.down1(x1)",
    "    x3 = self.down2(x2)",
    "    x4 = self.down3(x3)",
    "    x5 = self.down4(x4)",
    "    x = self.up1(x5, x4)",
    "    x = self.up2(x, x3)",
    "    x = self.up3(x, x2)",
    "    x = self.up4(x, x1)",
    "    logits = self.outc(x)",
    "    return logits",
  ];
  const unetTrainProblem = [
    "criterion = nn.????()",
    "optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)",
    "optimizer.????()",
    "logits = model(imgs)",
    "loss = criterion(logits, masks)",
    "loss.????()",
    "optimizer.????()",
    "",
    "# 평가/시각화에서는 logits를 binary mask로 바꿉니다.",
    "probs = torch.????(logits)",
    "preds = (probs > 0.5).????()",
  ];
  const unetTrainAnswer = [
    "criterion = nn.BCEWithLogitsLoss()",
    "optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)",
    "optimizer.zero_grad()",
    "logits = model(imgs)",
    "loss = criterion(logits, masks)",
    "loss.backward()",
    "optimizer.step()",
    "",
    "# 평가/시각화에서는 logits를 binary mask로 바꿉니다.",
    "probs = torch.sigmoid(logits)",
    "preds = (probs > 0.5).float()",
  ];
  const ddpmTimeProblem = [
    "def forward(self, time):",
    "    half_dim = self.dim ???? 2",
    "    freq = math.log(10000) / (half_dim - 1)",
    "    freq = torch.????(torch.arange(half_dim, device=time.device) * -freq)",
    "    args = time[:, ????].float() * freq[None, :]",
    "    emb = torch.????([args.sin(), args.cos()], dim=-1)",
    "    return emb",
  ];
  const ddpmTimeAnswer = [
    "def forward(self, time):",
    "    half_dim = self.dim // 2",
    "    freq = math.log(10000) / (half_dim - 1)",
    "    freq = torch.exp(torch.arange(half_dim, device=time.device) * -freq)",
    "    args = time[:, None].float() * freq[None, :]",
    "    emb = torch.cat([args.sin(), args.cos()], dim=-1)",
    "    return emb",
  ];
  const ddpmScheduleProblem = [
    "timesteps = 300",
    "betas = linear_beta_schedule(timesteps)",
    "alphas = 1.0 ???? betas",
    "alphas_cumprod = torch.????(alphas, dim=0)",
    "alphas_cumprod_prev = F.????(alphas_cumprod[:-1], (1, 0), value=1.0)",
    "sqrt_alphas_cumprod = torch.sqrt(alphas_cumprod)",
    "sqrt_one_minus_alphas_cumprod = torch.sqrt(1.0 - alphas_cumprod)",
  ];
  const ddpmScheduleAnswer = [
    "timesteps = 300",
    "betas = linear_beta_schedule(timesteps)",
    "alphas = 1.0 - betas",
    "alphas_cumprod = torch.cumprod(alphas, dim=0)",
    "alphas_cumprod_prev = F.pad(alphas_cumprod[:-1], (1, 0), value=1.0)",
    "sqrt_alphas_cumprod = torch.sqrt(alphas_cumprod)",
    "sqrt_one_minus_alphas_cumprod = torch.sqrt(1.0 - alphas_cumprod)",
  ];
  const ddpmForwardProblem = [
    "def extract(a, t, x_shape):",
    "    batch_size = t.shape[0]",
    "    out = a.????(-1, t.cpu())",
    "    return out.????(batch_size, *((1,) * (len(x_shape)-1))).to(t.device)",
    "",
    "def q_sample(x_start, t, noise=None):",
    "    noise = torch.????(x_start) if noise is None else noise",
    "    c1 = extract(sqrt_alphas_cumprod, t, x_start.shape)",
    "    c2 = extract(sqrt_one_minus_alphas_cumprod, t, x_start.shape)",
    "    return c1 * ???? + c2 * ????",
  ];
  const ddpmForwardAnswer = [
    "def extract(a, t, x_shape):",
    "    batch_size = t.shape[0]",
    "    out = a.gather(-1, t.cpu())",
    "    return out.reshape(batch_size, *((1,) * (len(x_shape)-1))).to(t.device)",
    "",
    "def q_sample(x_start, t, noise=None):",
    "    noise = torch.randn_like(x_start) if noise is None else noise",
    "    c1 = extract(sqrt_alphas_cumprod, t, x_start.shape)",
    "    c2 = extract(sqrt_one_minus_alphas_cumprod, t, x_start.shape)",
    "    return c1 * x_start + c2 * noise",
  ];
  const ddpmLossProblem = [
    "def p_losses(denoise_model, x_start, t, noise=None, loss_type='l2'):",
    "    if noise is None:",
    "        noise = torch.????(x_start)",
    "    x_noisy = ????(x_start=x_start, t=t, noise=noise)",
    "    predicted_noise = denoise_model(????, ???? )",
    "    if loss_type == 'l2':",
    "        loss = F.????(noise, predicted_noise)",
    "    return loss",
  ];
  const ddpmLossAnswer = [
    "def p_losses(denoise_model, x_start, t, noise=None, loss_type='l2'):",
    "    if noise is None:",
    "        noise = torch.randn_like(x_start)",
    "    x_noisy = q_sample(x_start=x_start, t=t, noise=noise)",
    "    predicted_noise = denoise_model(x_noisy, t)",
    "    if loss_type == 'l2':",
    "        loss = F.mse_loss(noise, predicted_noise)",
    "    return loss",
  ];
  const ddpmReverseProblem = [
    "@torch.no_grad()",
    "def p_sample(model, x, t, t_index):",
    "    betas_t = extract(betas, t, x.shape)",
    "    sqrt_recip_alphas_t = extract(sqrt_recip_alphas, t, x.shape)",
    "    sqrt_one_minus_t = extract(sqrt_one_minus_alphas_cumprod, t, x.shape)",
    "    model_mean = sqrt_recip_alphas_t * (",
    "        x - betas_t * ????(x, t) / sqrt_one_minus_t)",
    "    if t_index == 0:",
    "        return ????",
    "    variance_t = extract(posterior_variance, t, x.shape)",
    "    noise = torch.????(x)",
    "    return model_mean + torch.????(variance_t) * noise",
  ];
  const ddpmReverseAnswer = [
    "@torch.no_grad()",
    "def p_sample(model, x, t, t_index):",
    "    betas_t = extract(betas, t, x.shape)",
    "    sqrt_recip_alphas_t = extract(sqrt_recip_alphas, t, x.shape)",
    "    sqrt_one_minus_t = extract(sqrt_one_minus_alphas_cumprod, t, x.shape)",
    "    model_mean = sqrt_recip_alphas_t * (",
    "        x - betas_t * model(x, t) / sqrt_one_minus_t)",
    "    if t_index == 0:",
    "        return model_mean",
    "    variance_t = extract(posterior_variance, t, x.shape)",
    "    noise = torch.randn_like(x)",
    "    return model_mean + torch.sqrt(variance_t) * noise",
  ];
  const ddpmLoopProblem = [
    "@torch.no_grad()",
    "def p_sample_loop(model, shape):",
    "    device = next(model.parameters()).device",
    "    b = shape[0]",
    "    img = torch.????(shape, device=device)",
    "    imgs = []",
    "    for i in reversed(range(0, timesteps)):",
    "        t = torch.????((b,), i, device=device, dtype=torch.long)",
    "        img = ????(model, img, t, i)",
    "        imgs.????(img.cpu().numpy())",
    "    return imgs",
  ];
  const ddpmLoopAnswer = [
    "@torch.no_grad()",
    "def p_sample_loop(model, shape):",
    "    device = next(model.parameters()).device",
    "    b = shape[0]",
    "    img = torch.randn(shape, device=device)",
    "    imgs = []",
    "    for i in reversed(range(0, timesteps)):",
    "        t = torch.full((b,), i, device=device, dtype=torch.long)",
    "        img = p_sample(model, img, t, i)",
    "        imgs.append(img.cpu().numpy())",
    "    return imgs",
  ];
  const sdLoadProblem = [
    "from diffusers import ????",
    "model_id = 'CompVis/stable-diffusion-v1-4'",
    "pipe = StableDiffusionPipeline.????(",
    "    model_id,",
    "    torch_dtype=torch.????",
    ").to('????')",
    "for name, component in pipe.????.items():",
    "    print(name, type(component).__name__)",
  ];
  const sdLoadAnswer = [
    "from diffusers import StableDiffusionPipeline",
    "model_id = 'CompVis/stable-diffusion-v1-4'",
    "pipe = StableDiffusionPipeline.from_pretrained(",
    "    model_id,",
    "    torch_dtype=torch.float16",
    ").to('cuda')",
    "for name, component in pipe.components.items():",
    "    print(name, type(component).__name__)",
  ];
  const sdGenerateProblem = [
    "guidance_scale = 7.5",
    "prompt = 'A futuristic cityscape at sunset with flying cars'",
    "result = ????(prompt, guidance_scale=guidance_scale)",
    "image = result.????[0]",
  ];
  const sdGenerateAnswer = [
    "guidance_scale = 7.5",
    "prompt = 'A futuristic cityscape at sunset with flying cars'",
    "result = pipe(prompt, guidance_scale=guidance_scale)",
    "image = result.images[0]",
  ];
  const sdCompareProblem = [
    "scales = [1.5, 10.0, 20.0]",
    "images = []",
    "for scale in scales:",
    "    # 같은 noise에서 guidance 영향만 비교하도록 seed를 고정합니다.",
    "    generator = torch.????(50)",
    "    result = pipe(prompt, guidance_scale=????, generator=generator).images[0]",
    "    images.????((scale, result))",
  ];
  const sdCompareAnswer = [
    "scales = [1.5, 10.0, 20.0]",
    "images = []",
    "for scale in scales:",
    "    # 같은 noise에서 guidance 영향만 비교하도록 seed를 고정합니다.",
    "    generator = torch.manual_seed(50)",
    "    result = pipe(prompt, guidance_scale=scale, generator=generator).images[0]",
    "    images.append((scale, result))",
  ];
  const sdNegativeProblem = [
    "generator = torch.Generator('cuda').????(2024)",
    "image = pipe(",
    "    prompt,",
    "    negative_prompt=????,",
    "    generator=generator,",
    "    num_inference_steps=????,",
    "    guidance_scale=7.5,",
    ").images[????]",
  ];
  const sdNegativeAnswer = [
    "generator = torch.Generator('cuda').manual_seed(2024)",
    "image = pipe(",
    "    prompt,",
    "    negative_prompt=neg_prompt,",
    "    generator=generator,",
    "    num_inference_steps=30,",
    "    guidance_scale=7.5,",
    ").images[0]",
  ];
  const sdSizeProblem = [
    "sizes = [(512, 512), (768, 512), (512, 768)]",
    "images = []",
    "for w, h in sizes:",
    "    generator = torch.manual_seed(10)",
    "    img = pipe(prompt, width=????, height=????, generator=generator).images[0]",
    "    images.append((f'{w}x{h}', img))",
    "",
    "def clean_memory():",
    "    gc.????()",
    "    torch.cuda.????()",
  ];
  const sdSizeAnswer = [
    "sizes = [(512, 512), (768, 512), (512, 768)]",
    "images = []",
    "for w, h in sizes:",
    "    generator = torch.manual_seed(10)",
    "    img = pipe(prompt, width=w, height=h, generator=generator).images[0]",
    "    images.append((f'{w}x{h}', img))",
    "",
    "def clean_memory():",
    "    gc.collect()",
    "    torch.cuda.empty_cache()",
  ];
  window.LLM_COURSE = {
    subject: "2. Vision",
    sample_mode: true,
    cells: {
      "v-01": { source: "T.RandomCrop(32, padding=4)" },
      "v-02": { source: "T.RandomHorizontalFlip()" },
      "v-03": { source: "T.ToTensor()" },
      "v-04": { source: "T.Normalize(CIFAR10_MEAN, CIFAR10_STD)" },
      "v-05": { source: "DataLoader(train_set, batch_size=batch_size, shuffle=True)" },
      "v-06": { source: "nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)" },
      "v-07": { source: "nn.Linear(model.fc.in_features, num_classes)" },
      "v-08": { source: "logits = model(images)" },
      "v-09": { source: "scaler.scale(loss).backward()" },
      "v-10": { source: "preds = logits.argmax(dim=1)" },
      "vit-01": { source: "self.to_qkv(x).chunk(3, dim=-1)" },
      "vit-02": { source: "einsum('b h i d, b h j d -> b h i j', q, k)" },
      "vit-03": { source: "self.attend(dots)" },
      "vit-04": { source: "nn.Linear(patch_dim, cfg.dim)" },
      "vit-05": { source: "nn.Parameter(torch.randn(1, 1, cfg.dim))" },
      "vit-06": { source: "torch.cat((cls_tokens, x), dim=1)" },
      "vit-07": { source: "self.transformer(x)" },
      "vit-08": { source: "x[:, 0]" },
      "vit-09": { source: "x = attn(x) + x" },
      "vit-10": { source: "loss.backward()" },
      "vit-11": { source: "optimizer.step()" },
      "vit-12": { source: "torch.max(output, dim=1)" },
      "detr-01": { source: "T.Resize(800)" },
      "detr-02": { source: "T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])" },
      "detr-03": { source: "x.unbind(1)" },
      "detr-04": { source: "torch.stack(b, dim=1)" },
      "detr-05": { source: "box_cxcywh_to_xyxy(out_bbox)" },
      "detr-06": { source: "transform(im).unsqueeze(0)" },
      "detr-07": { source: "outputs['pred_logits'].softmax(-1)[0, :, :-1]" },
      "detr-08": { source: "probas.max(-1).values > 0.9" },
      "detr-09": { source: "outputs['pred_boxes'][0, keep]" },
      "detr-10": { source: "register_forward_hook" },
      "detr-11": { source: "output[1]" },
      "detr-12": { source: "hook.remove()" },
      "detr-13": { source: "reshape(shape + shape)" },
      "detr-14": { source: "view(h, w)" },
      "unet-01": { source: "np.zeros((self.image_size, self.image_size), dtype=np.float32)" },
      "unet-02": { source: "np.ogrid[:self.image_size, :self.image_size]" },
      "unet-03": { source: "np.expand_dims(img, axis=0)" },
      "unet-04": { source: "torch.from_numpy(img)" },
      "unet-05": { source: "nn.Conv2d(in_channels, mid_channels, kernel_size=3, padding=1, bias=False)" },
      "unet-06": { source: "nn.MaxPool2d(kernel_size=2)" },
      "unet-07": { source: "F.pad(x1" },
      "unet-08": { source: "torch.cat([x2, x1], dim=1)" },
      "unet-09": { source: "self.up1(x5, x4)" },
      "unet-10": { source: "self.outc(x)" },
      "unet-11": { source: "nn.BCEWithLogitsLoss()" },
      "unet-12": { source: "loss.backward()" },
      "unet-13": { source: "torch.sigmoid(logits)" },
      "unet-14": { source: "(probs > 0.5).float()" },
      "ddpm-01": { source: "self.dim // 2" },
      "ddpm-02": { source: "torch.exp(torch.arange(half_dim" },
      "ddpm-03": { source: "torch.cat([args.sin(), args.cos()], dim=-1)" },
      "ddpm-04": { source: "alphas = 1.0 - betas" },
      "ddpm-05": { source: "torch.cumprod(alphas, dim=0)" },
      "ddpm-06": { source: "F.pad(alphas_cumprod[:-1], (1, 0), value=1.0)" },
      "ddpm-07": { source: "a.gather(-1, t.cpu())" },
      "ddpm-08": { source: "torch.randn_like(x_start)" },
      "ddpm-09": { source: "q_sample(x_start=x_start, t=t, noise=noise)" },
      "ddpm-10": { source: "denoise_model(x_noisy, t)" },
      "ddpm-11": { source: "F.mse_loss(noise, predicted_noise)" },
      "ddpm-12": { source: "model(x, t)" },
      "ddpm-13": { source: "torch.sqrt(posterior_variance_t) * noise" },
      "ddpm-14": { source: "torch.full((b,), i, device=device, dtype=torch.long)" },
      "ddpm-15": { source: "p_sample(" },
      "sd-01": { source: "StableDiffusionPipeline" },
      "sd-02": { source: "from_pretrained(" },
      "sd-03": { source: "torch_dtype=torch.float16" },
      "sd-04": { source: ".to(\"cuda\")" },
      "sd-05": { source: "pipe.components.items()" },
      "sd-06": { source: "pipe(prompt, guidance_scale=guidance_scale).images[0]" },
      "sd-07": { source: "torch.manual_seed(50)" },
      "sd-08": { source: "guidance_scale=scale" },
      "sd-09": { source: "negative_prompt=neg_prompt" },
      "sd-10": { source: "num_inference_steps=30" },
      "sd-11": { source: "width=w, height=h" },
      "sd-12": { source: "torch.cuda.empty_cache()" },
    },
    chapters: [{
      id: "vision-01", number: "01", title: "ResNet18 & CIFAR-10", file: "01_ResNet18_CIFAR10.ipynb",
      capability: "CIFAR-10 이미지 분류를 위해 변형·ResNet18·학습 루프·Accuracy를 연결해 구현할 수 있다.",
      summary: "이미지 데이터가 Transform과 DataLoader를 거쳐 [B,C,H,W] Tensor가 되고, ResNet의 logits를 정답과 비교해 학습하는 흐름입니다.",
      notebook_goal: "CIFAR-10 이미지를 증강·정규화하고, ResNet18을 10개 클래스 분류기에 맞춰 학습·평가하는 파이프라인을 구현한다.",
      key_points: [
        { title: "학습 이미지 증강", purpose: "학습 데이터에만 crop과 flip을 적용해 같은 이미지의 다양한 모습을 학습합니다.", code: "T.RandomCrop(32, padding=4)\nT.RandomHorizontalFlip()", flow: "PIL → 증강된 PIL", watch: "평가 데이터에는 무작위 증강을 넣지 않습니다." },
        { title: "이미지 Tensor와 정규화", purpose: "ToTensor는 이미지를 [C,H,W] float Tensor로, Normalize는 채널별 분포를 맞춘 값으로 바꿉니다.", code: "T.ToTensor()\nT.Normalize(mean, std)", flow: "PIL → [C,H,W] float", watch: "Normalize는 ToTensor 뒤에 와야 합니다." },
        { title: "CIFAR용 ResNet 변경", purpose: "RGB 입력 채널 3개와 10개 클래스 출력에 맞게 첫 Conv와 마지막 Linear를 바꿉니다.", code: "nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1)\nnn.Linear(in_features, num_classes)", flow: "[B,3,32,32] → [B,10]", watch: "분류기의 출력 차원은 클래스 수입니다." },
        { title: "분류 학습과 Accuracy", purpose: "logits와 label로 loss를 만들고 backward 후 optimizer가 가중치를 갱신합니다.", code: "logits = model(images)\nloss.backward()\npreds = logits.argmax(dim=1)", flow: "[B,C], [B] → loss → gradient", watch: "argmax는 클래스 차원 dim=1에서 수행합니다." },
      ],
      theory_guide: [
        { title: "1. Data augmentation", concept: "증강은 학습 이미지에 무작위 변형을 적용해 새로운 입력처럼 보이게 만드는 방법입니다. 과적합을 줄이는 데 쓰입니다.", flow: "PIL → RandomCrop/Flip → Tensor", code_signal: "train_tfms에만 Random으로 시작하는 transform이 들어갑니다.", exam_clue: "crop은 크기와 padding, flip은 함수 호출 괄호를 함께 봅니다." },
        { title: "2. Tensor 입력 형태", concept: "이미지 분류 모델은 배치·채널·높이·너비 순서의 Tensor를 입력으로 받습니다.", flow: "[B, C, H, W] = [batch, 3, 32, 32]", code_signal: "RGB 이미지의 Conv2d 첫 입력 채널은 3입니다.", exam_clue: "CIFAR-10은 RGB이므로 1이 아니라 3입니다." },
        { title: "3. Logits와 CrossEntropyLoss", concept: "logits는 각 클래스에 대한 점수이며, CrossEntropyLoss가 정수 label과 비교해 학습 신호를 만듭니다.", flow: "model(images) [B,10] + labels [B] → loss", code_signal: "criterion(logits, labels) 앞에서는 model(images)가 필요합니다.", exam_clue: "softmax를 따로 넣지 않고 raw logits를 CrossEntropyLoss에 전달합니다." },
        { title: "4. 예측과 Accuracy", concept: "가장 큰 logit의 위치가 모델이 고른 클래스입니다. 이를 label과 비교해 맞은 비율을 구합니다.", flow: "[B,10] → argmax(dim=1) → [B]", code_signal: "클래스 차원이 두 번째 축이면 dim=1입니다.", exam_clue: "argmax는 값이 아니라 class index를 반환합니다." },
      ],
      full_code_cells: [cell(1, transformProblem, transformAnswer, [1,2,3,4,6]), cell(2, modelProblem, modelAnswer, [1,3]), cell(3, trainProblem, trainAnswer, [1,3,6])],
      subjective: [
        { id:"v-q1", sourceId:"v-01", occurrence:0, answer:"RandomCrop", accepted_answers:["RandomCrop"], topic:"학습 증강", prompt:"32×32 crop과 padding=4를 적용하는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q2", sourceId:"v-02", occurrence:0, answer:"RandomHorizontalFlip", accepted_answers:["RandomHorizontalFlip"], topic:"학습 증강", prompt:"좌우 반전을 무작위로 적용하는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q3", sourceId:"v-03", occurrence:0, answer:"ToTensor", accepted_answers:["ToTensor"], topic:"Tensor 변환", prompt:"PIL 이미지를 [C,H,W] Tensor로 바꾸는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q4", sourceId:"v-04", occurrence:0, answer:"Normalize", accepted_answers:["Normalize"], topic:"정규화", prompt:"채널별 mean과 std로 정규화하는 transform 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q5", sourceId:"v-05", occurrence:0, answer:"shuffle", accepted_answers:["shuffle"], topic:"DataLoader", prompt:"학습 배치의 순서를 매 epoch 섞는 인자 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q6", sourceId:"v-06", occurrence:0, answer:"3", accepted_answers:["3"], topic:"ResNet 입력", prompt:"CIFAR-10 RGB 입력의 Conv2d in_channels를 채우세요.", isSourceBlank:false },
        { id:"v-q7", sourceId:"v-07", occurrence:0, answer:"num_classes", accepted_answers:["num_classes","10"], topic:"ResNet 출력", prompt:"마지막 분류기의 출력 차원을 클래스 수로 맞추는 변수를 채우세요.", isSourceBlank:false },
        { id:"v-q8", sourceId:"v-08", occurrence:0, answer:"model", accepted_answers:["model"], topic:"학습", prompt:"images를 입력해 logits를 만드는 호출 대상을 채우세요.", isSourceBlank:false },
        { id:"v-q9", sourceId:"v-09", occurrence:0, answer:"backward", accepted_answers:["backward"], topic:"역전파", prompt:"scaled loss에서 gradient를 계산하는 메서드 이름을 채우세요.", isSourceBlank:false },
        { id:"v-q10", sourceId:"v-10", occurrence:0, answer:"argmax", accepted_answers:["argmax"], topic:"예측", prompt:"클래스 점수에서 가장 높은 클래스 index를 고르는 메서드 이름을 채우세요.", isSourceBlank:false },
      ],
      mcq: [
        { id:"v-m1", source_question_id:"v-q4", topic:"Tensor 변환 순서", prompt:"PIL 이미지를 정규화하려면 빈칸에 무엇이 들어가야 하나요?", answer_index:1, explanation:"Normalize는 Tensor를 입력으로 받으므로 ToTensor 다음에 사용합니다.", choices:[{text:"RandomCrop",why:"공간 증강입니다."},{text:"Normalize",why:"정답: 채널별 정규화입니다."},{text:"DataLoader",why:"배치 생성 객체입니다."},{text:"argmax",why:"예측 class 선택 메서드입니다."},{text:"backward",why:"역전파 메서드입니다."}] },
        { id:"v-m2", source_question_id:"v-q6", topic:"RGB 입력 채널", prompt:"CIFAR-10용 첫 Conv의 입력 채널 수는?", answer_index:2, explanation:"CIFAR-10 이미지는 RGB이므로 채널 수가 3입니다.", choices:[{text:"1",why:"흑백 이미지 채널 수입니다."},{text:"10",why:"클래스 수입니다."},{text:"3",why:"정답: RGB 채널 수입니다."},{text:"32",why:"이미지 높이·너비입니다."},{text:"64",why:"첫 Conv의 출력 채널입니다."}] },
        { id:"v-m3", source_question_id:"v-q10", topic:"예측 class", prompt:"logits [B, C]에서 클래스 index [B]를 얻는 표현은?", answer_index:0, explanation:"C가 두 번째 차원이므로 argmax(dim=1)입니다.", choices:[{text:"argmax",why:"정답: 빈칸 뒤의 (dim=1)과 합쳐져 class index를 만듭니다."},{text:"softmax",why:"확률은 만들지만 index를 고르지 않습니다."},{text:"backward",why:"gradient 계산입니다."},{text:"Normalize",why:"이미지 변환입니다."},{text:"shuffle",why:"DataLoader 인자입니다."}] },
      ],
    }, {
      id: "vision-02",
      number: "02",
      title: "ViT & CIFAR-10",
      file: "02_ViT_CIFAR10.ipynb",
      capability: "이미지를 패치 토큰으로 바꾸고 Self-Attention과 CLS 토큰을 거쳐 분류 logits를 만드는 ViT를 구현할 수 있다.",
      summary: "[B,3,32,32] 이미지가 64개 패치와 CLS 토큰을 포함한 [B,65,dim] 시퀀스가 되고, Transformer Encoder와 분류 헤드를 거쳐 [B,10] logits가 됩니다.",
      notebook_goal: "CIFAR-10 이미지를 패치 시퀀스로 변환하고 멀티헤드 Self-Attention 기반 Vision Transformer로 분류하는 전체 흐름을 구현한다.",
      key_points: [
        { title:"패치 토큰화", purpose:"이미지를 겹치지 않는 패치로 나누고 각 패치를 Transformer 차원으로 투영합니다.", code:"Rearrange(...)\nnn.Linear(patch_dim, dim)", flow:"[B,C,H,W] → [B,N,patch_dim] → [B,N,dim]", watch:"N=(H/Ph)×(W/Pw), patch_dim=C×Ph×Pw입니다." },
        { title:"Q·K·V Self-Attention", purpose:"각 토큰이 다른 토큰을 얼마나 참고할지 계산합니다.", code:"qkv.chunk(3)\ndots = QKᵀ / √d\nattn @ V", flow:"[B,N,dim] → [B,H,N,d] → [B,H,N,N] → [B,N,dim]", watch:"Softmax는 토큰 점수의 마지막 차원에 적용합니다." },
        { title:"CLS와 위치 정보", purpose:"CLS 토큰은 전체 이미지 표현을 모으고 위치 임베딩은 패치 순서를 알려줍니다.", code:"torch.cat((cls_tokens, x), dim=1)\nx + pos_embedding", flow:"[B,N,dim] → [B,N+1,dim]", watch:"위치 임베딩 길이도 num_patches+1이어야 합니다." },
        { title:"학습과 평가", purpose:"log-probability와 정답 label로 loss를 만들고 평가에서는 gradient 없이 정확도를 계산합니다.", code:"F.log_softmax\nF.nll_loss\nloss.backward()\noptimizer.step()", flow:"[B,10]+[B] → loss → gradient → update", watch:"log_softmax와 nll_loss는 한 쌍이며 CrossEntropyLoss로 대체할 수 있습니다." },
      ],
      theory_guide: [
        { title:"1. Patch Embedding", concept:"패치 임베딩은 2차원 이미지를 Transformer가 처리할 수 있는 토큰 시퀀스로 바꾸는 단계입니다.", flow:"32×32, patch 4×4 → 8×8=64 tokens", code_signal:"Rearrange 뒤의 Linear가 펼친 패치를 cfg.dim으로 투영합니다.", exam_clue:"패치 수와 패치 차원을 서로 바꾸지 않도록 구분합니다." },
        { title:"2. Scaled Dot-Product Attention", concept:"Query와 Key의 내적으로 관련도를 구하고 √d로 나눈 뒤 Softmax를 적용하여 Value를 가중합합니다.", flow:"QKᵀ/√d → Softmax → Attention×V", code_signal:"einsum 두 번 사이에 Softmax가 위치합니다.", exam_clue:"첫 einsum은 q,k이고 두 번째 einsum은 attn,v입니다." },
        { title:"3. CLS·Position·Residual", concept:"CLS는 분류용 대표 토큰, Position은 공간 순서, Residual은 원래 정보를 보존하는 덧셈 연결입니다.", flow:"tokens → +CLS → +position → Encoder residual", code_signal:"cat은 dim=1, residual은 block(x)+x입니다.", exam_clue:"CLS의 index는 0이며 위치 임베딩에는 CLS 자리까지 포함됩니다." },
        { title:"4. Tensor 흐름", concept:"ViT는 토큰 개수 축을 유지한 채 Encoder를 통과하고 마지막에 CLS 또는 mean으로 토큰 축을 제거합니다.", flow:"[B,65,64] → [B,65,64] → [B,64] → [B,10]", code_signal:"x[:,0] 또는 x.mean(dim=1) 뒤 mlp_head를 호출합니다.", exam_clue:"분류 결과는 확률이 아니라 raw logits 또는 log_softmax 결과입니다." },
      ],
      full_code_cells: [
        cell(1, vitAttentionProblem, vitAttentionAnswer, [3,5,6,7]),
        cell(2, vitPatchProblem, vitPatchAnswer, [1,5,7]),
        cell(3, vitForwardProblem, vitForwardAnswer, [1,4,7,8]),
        cell(4, vitTransformerProblem, vitTransformerAnswer, [3,5]),
        cell(5, vitTrainProblem, vitTrainAnswer, [1,2,3,4,8,9]),
      ],
      subjective: [
        {id:"vit-q1",sourceId:"vit-01",occurrence:0,answer:"chunk",accepted_answers:["chunk"],topic:"QKV 분할",prompt:"QKV 선형변환 결과를 3개로 나누는 메서드를 채우세요.",isSourceBlank:false},
        {id:"vit-q2",sourceId:"vit-02",occurrence:0,answer:"q, k",accepted_answers:["q,k","q, k"],topic:"Attention score",prompt:"토큰 간 관련도 행렬을 만드는 두 입력을 순서대로 채우세요.",isSourceBlank:false},
        {id:"vit-q3",sourceId:"vit-03",occurrence:0,answer:"attend",accepted_answers:["attend","self.attend"],topic:"Softmax",prompt:"dots를 attention 확률로 바꾸는 모듈 이름을 채우세요.",isSourceBlank:false},
        {id:"vit-q4",sourceId:"vit-04",occurrence:0,answer:"Linear",accepted_answers:["Linear","nn.Linear"],topic:"Patch projection",prompt:"patch_dim을 cfg.dim으로 투영하는 layer를 채우세요.",isSourceBlank:false},
        {id:"vit-q5",sourceId:"vit-05",occurrence:0,answer:"Parameter",accepted_answers:["Parameter","nn.Parameter"],topic:"CLS token",prompt:"CLS 토큰을 학습 가능한 파라미터로 등록하는 클래스를 채우세요.",isSourceBlank:false},
        {id:"vit-q6",sourceId:"vit-06",occurrence:0,answer:"cat",accepted_answers:["cat","torch.cat"],topic:"CLS 결합",prompt:"CLS 토큰을 패치 시퀀스 앞에 연결하는 함수를 채우세요.",isSourceBlank:false},
        {id:"vit-q7",sourceId:"vit-07",occurrence:0,answer:"transformer",accepted_answers:["transformer","self.transformer"],topic:"Encoder",prompt:"토큰 시퀀스를 Encoder에 통과시키는 모듈 이름을 채우세요.",isSourceBlank:false},
        {id:"vit-q8",sourceId:"vit-08",occurrence:0,answer:"0",accepted_answers:["0"],topic:"CLS pooling",prompt:"CLS pooling에서 선택할 토큰 index를 채우세요.",isSourceBlank:false},
        {id:"vit-q9",sourceId:"vit-09",occurrence:0,answer:"attn",accepted_answers:["attn"],topic:"Residual",prompt:"첫 residual 연결에서 x에 더할 블록 호출 대상을 채우세요.",isSourceBlank:false},
        {id:"vit-q10",sourceId:"vit-10",occurrence:0,answer:"backward",accepted_answers:["backward"],topic:"역전파",prompt:"loss에서 gradient를 계산하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"vit-q11",sourceId:"vit-11",occurrence:0,answer:"step",accepted_answers:["step"],topic:"가중치 갱신",prompt:"optimizer가 계산된 gradient로 파라미터를 갱신하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"vit-q12",sourceId:"vit-12",occurrence:0,answer:"max",accepted_answers:["max","torch.max"],topic:"예측",prompt:"log-probability에서 최댓값과 class index를 얻는 함수를 채우세요.",isSourceBlank:false},
      ],
      mcq: [
        {id:"vit-m1",source_question_id:"vit-q2",topic:"QK score",prompt:"Self-Attention에서 Softmax 직전 토큰 간 점수를 만드는 조합은?",answer_index:1,explanation:"Query와 Key의 내적이 각 토큰 쌍의 관련도 점수를 만듭니다.",choices:[{text:"Q와 V",why:"Value는 점수 계산 뒤 가중합에 쓰입니다."},{text:"Q와 K",why:"정답: QKᵀ가 관련도 점수입니다."},{text:"K와 V",why:"Query가 빠져 어떤 토큰의 관심인지 알 수 없습니다."},{text:"V와 V",why:"내용끼리의 내적은 attention score 정의가 아닙니다."},{text:"Attention과 K",why:"Attention 확률은 이미 score 이후 결과입니다."}]},
        {id:"vit-m2",source_question_id:"vit-q6",topic:"CLS 연결 축",prompt:"[B,N,D] 패치 토큰 앞에 [B,1,D] CLS 토큰을 붙일 축은?",answer_index:2,explanation:"토큰 개수 N이 있는 두 번째 축(dim=1)을 늘려야 합니다.",choices:[{text:"dim=0",why:"배치 수가 늘어납니다."},{text:"dim=-1",why:"임베딩 차원이 늘어납니다."},{text:"dim=1",why:"정답: 토큰 축입니다."},{text:"dim=2",why:"임베딩 축입니다."},{text:"축 지정 불필요",why:"cat은 연결 축이 필수입니다."}]},
        {id:"vit-m3",source_question_id:"vit-q10",topic:"학습 순서",prompt:"loss 계산 뒤 올바른 학습 순서는?",answer_index:0,explanation:"gradient를 계산한 뒤 optimizer가 그 gradient로 파라미터를 갱신합니다.",choices:[{text:"loss.backward() → optimizer.step()",why:"정답입니다."},{text:"optimizer.step() → loss.backward()",why:"gradient 계산 전에 갱신할 수 없습니다."},{text:"model.eval() → optimizer.step()",why:"평가 모드는 학습 순서가 아닙니다."},{text:"torch.no_grad() → loss.backward()",why:"no_grad 안에서는 역전파 그래프가 없습니다."},{text:"argmax() → backward()",why:"argmax는 미분 가능한 학습 손실이 아닙니다."}]},
      ],
    }, {
      id: "vision-03",
      number: "03",
      title: "DETR Object Detection",
      file: "03_DETR.ipynb",
      capability: "DETR 입력을 전처리하고 object query의 클래스·박스 출력을 필터링하여 원본 이미지 좌표로 복원할 수 있다.",
      summary: "PIL 이미지가 [1,3,H,W] Tensor로 바뀌고, DETR의 고정 개수 object query가 class logits와 정규화된 박스를 출력한 뒤 confidence 필터와 좌표 복원을 거칩니다.",
      notebook_goal: "DETR의 전처리, 클래스·박스 후처리, object query 필터링, encoder·decoder attention 추출 과정을 코드로 구현한다.",
      key_points: [
        { title:"입력 전처리", purpose:"ResNet-50 backbone의 사전학습 분포에 맞춰 이미지 크기와 채널 분포를 맞춥니다.", code:"T.Resize(800)\nT.ToTensor()\nT.Normalize(ImageNet mean, std)", flow:"PIL → [3,H,W] → [1,3,H,W]", watch:"모델 호출 전 unsqueeze(0)으로 배치 축을 추가합니다." },
        { title:"박스 좌표 복원", purpose:"정규화된 중심 좌표 박스를 원본 이미지 픽셀의 꼭짓점 좌표로 바꿉니다.", code:"(cx,cy,w,h) → (xmin,ymin,xmax,ymax)\n× [W,H,W,H]", flow:"[N,4] normalized → [N,4] pixels", watch:"PIL size 순서는 (width, height)입니다." },
        { title:"Object query 필터", purpose:"no-object 클래스를 제외하고 실제 객체일 확률이 높은 query만 남깁니다.", code:"softmax(-1)[0,:,:-1]\nmax(-1).values > 0.9", flow:"[1,Q,C+1] → [Q,C] → [Q] bool", watch:"마지막 클래스가 no-object이므로 :-1로 제외합니다." },
        { title:"Attention hook", purpose:"forward 중 backbone feature와 encoder·decoder attention weight를 저장합니다.", code:"register_forward_hook(... output[1])\nhook.remove()", flow:"module output → list → tensor", watch:"사용 후 hook을 제거해야 다음 forward에서 중복 저장되지 않습니다." },
      ],
      theory_guide: [
        { title:"1. DETR 출력 구조", concept:"DETR은 고정 개수의 object query마다 클래스와 박스를 동시에 예측하며 객체가 없는 query는 no-object로 분류합니다.", flow:"image → backbone → encoder → decoder queries → class/box heads", code_signal:"pred_logits와 pred_boxes가 같은 query 축을 공유합니다.", exam_clue:"클래스 확률 계산에서 마지막 no-object 슬롯을 제외합니다." },
        { title:"2. 좌표계 변환", concept:"모델의 박스는 중심점과 크기를 0~1로 표현하므로 시각화 전에 꼭짓점 좌표와 픽셀 단위로 바꿔야 합니다.", flow:"cxcywh → xyxy → pixel scale", code_signal:"unbind로 네 성분을 나눈 뒤 stack으로 다시 [N,4]를 만듭니다.", exam_clue:"xmin에는 cx-w/2, xmax에는 cx+w/2가 들어갑니다." },
        { title:"3. Boolean indexing", concept:"keep은 각 query를 유지할지 나타내는 bool Tensor이며 클래스 확률과 박스에 같은 마스크를 적용해야 대응이 보존됩니다.", flow:"[Q] keep → probas[keep], boxes[0,keep]", code_signal:"threshold 결과와 두 출력의 indexing을 함께 확인합니다.", exam_clue:"확률과 박스에 서로 다른 마스크를 쓰면 탐지 결과가 어긋납니다." },
        { title:"4. Encoder와 Decoder Attention", concept:"Encoder self-attention은 이미지 위치끼리, decoder cross-attention은 object query와 이미지 위치 사이의 관계를 나타냅니다.", flow:"encoder [HW,HW], decoder [Q,HW] → 2D map", code_signal:"reshape(shape+shape)와 view(h,w)가 각각 다른 attention을 복원합니다.", exam_clue:"encoder와 decoder hook 대상을 바꾸지 않도록 모듈 경로를 구분합니다." },
      ],
      full_code_cells: [
        cell(1, detrTransformProblem, detrTransformAnswer, [1,2,3,7,9]),
        cell(2, detrRescaleProblem, detrRescaleAnswer, [2,4]),
        cell(3, detrInferenceProblem, detrInferenceAnswer, [1,2,4,6,7]),
        cell(4, detrHooksProblem, detrHooksAnswer, [2,5,7,11]),
        cell(5, detrAttentionProblem, detrAttentionAnswer, [1,3,6]),
      ],
      subjective: [
        {id:"detr-q1",sourceId:"detr-01",occurrence:0,answer:"Resize",accepted_answers:["Resize","T.Resize"],topic:"전처리",prompt:"공식 DETR 데모에서 짧은 변을 800으로 맞추는 transform을 채우세요.",isSourceBlank:false},
        {id:"detr-q2",sourceId:"detr-02",occurrence:0,answer:"Normalize",accepted_answers:["Normalize","T.Normalize"],topic:"전처리",prompt:"ImageNet mean/std를 적용하는 transform을 채우세요.",isSourceBlank:false},
        {id:"detr-q3",sourceId:"detr-03",occurrence:0,answer:"unbind",accepted_answers:["unbind"],topic:"박스 변환",prompt:"[N,4] 박스 Tensor를 네 좌표 성분으로 분리하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q4",sourceId:"detr-04",occurrence:0,answer:"stack",accepted_answers:["stack","torch.stack"],topic:"박스 변환",prompt:"계산한 네 꼭짓점 좌표를 [N,4]로 결합하는 함수를 채우세요.",isSourceBlank:false},
        {id:"detr-q5",sourceId:"detr-05",occurrence:0,answer:"box_cxcywh_to_xyxy",accepted_answers:["box_cxcywh_to_xyxy"],topic:"좌표 복원",prompt:"픽셀 스케일을 곱하기 전에 박스를 xyxy로 바꾸는 함수를 채우세요.",isSourceBlank:false},
        {id:"detr-q6",sourceId:"detr-06",occurrence:0,answer:"unsqueeze",accepted_answers:["unsqueeze"],topic:"배치 축",prompt:"한 장의 [C,H,W] 입력에 배치 축을 추가하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q7",sourceId:"detr-07",occurrence:0,answer:"softmax",accepted_answers:["softmax"],topic:"클래스 확률",prompt:"pred_logits를 query별 클래스 확률로 바꾸는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q8",sourceId:"detr-08",occurrence:0,answer:"max",accepted_answers:["max"],topic:"신뢰도 필터",prompt:"각 query의 최고 클래스 확률을 구하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q9",sourceId:"detr-09",occurrence:0,answer:"keep",accepted_answers:["keep"],topic:"Boolean indexing",prompt:"확률 기준을 통과한 박스만 고르는 bool 마스크를 채우세요.",isSourceBlank:false},
        {id:"detr-q10",sourceId:"detr-10",occurrence:0,answer:"register_forward_hook",accepted_answers:["register_forward_hook"],topic:"Hook",prompt:"모듈의 forward 출력을 캡처하도록 hook을 등록하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q11",sourceId:"detr-11",occurrence:0,answer:"1",accepted_answers:["1"],topic:"Attention weight",prompt:"MultiheadAttention 출력 tuple에서 attention weight의 index를 채우세요.",isSourceBlank:false},
        {id:"detr-q12",sourceId:"detr-12",occurrence:0,answer:"remove",accepted_answers:["remove"],topic:"Hook 해제",prompt:"사용이 끝난 forward hook을 해제하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q13",sourceId:"detr-13",occurrence:0,answer:"reshape",accepted_answers:["reshape"],topic:"Encoder attention",prompt:"[HW,HW] self-attention을 [H,W,H,W]로 복원하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"detr-q14",sourceId:"detr-14",occurrence:0,answer:"view",accepted_answers:["view"],topic:"Decoder attention",prompt:"object query의 [HW] cross-attention을 [H,W]로 보는 메서드를 채우세요.",isSourceBlank:false},
      ],
      mcq: [
        {id:"detr-m1",source_question_id:"detr-q7",topic:"no-object 제외",prompt:"pred_logits에서 실제 COCO 클래스 확률만 얻는 올바른 흐름은?",answer_index:2,explanation:"클래스 축에 softmax를 적용한 뒤 마지막 no-object 슬롯을 제외합니다.",choices:[{text:"sigmoid 후 첫 클래스 제외",why:"공식 데모 흐름과 다르고 no-object는 마지막입니다."},{text:"argmax 후 softmax",why:"argmax를 먼저 하면 클래스별 확률이 사라집니다."},{text:"softmax(-1) 후 [..., :-1]",why:"정답입니다."},{text:"softmax(0) 후 배치 제거",why:"배치 축에 정규화하면 query별 클래스 확률이 아닙니다."},{text:"pred_boxes에 softmax",why:"박스 좌표는 클래스 logits가 아닙니다."}]},
        {id:"detr-m2",source_question_id:"detr-q5",topic:"박스 좌표",prompt:"(cx,cy,w,h)에서 xmin을 구하는 식은?",answer_index:1,explanation:"중심 x에서 폭의 절반을 빼면 왼쪽 꼭짓점입니다.",choices:[{text:"cx-w",why:"폭 전체를 빼면 너무 멀리 이동합니다."},{text:"cx-0.5*w",why:"정답입니다."},{text:"cx+0.5*w",why:"xmax입니다."},{text:"w-0.5*cx",why:"중심과 폭의 역할이 뒤바뀌었습니다."},{text:"cx/w",why:"좌표 변환식이 아닙니다."}]},
        {id:"detr-m3",source_question_id:"detr-q11",topic:"Attention 종류",prompt:"object query가 이미지의 어느 위치를 참고했는지 볼 대상은?",answer_index:3,explanation:"Decoder cross-attention이 query와 encoder 이미지 위치 사이의 관계를 나타냅니다.",choices:[{text:"backbone convolution weight",why:"필터 자체이지 특정 query의 관심 위치가 아닙니다."},{text:"encoder self-attention만",why:"이미지 위치끼리의 관계이며 object query 축이 없습니다."},{text:"class_embed bias",why:"분류 head의 편향입니다."},{text:"decoder multihead cross-attention",why:"정답입니다."},{text:"optimizer state",why:"학습 상태이며 attention이 아닙니다."}]},
      ],
    }, {
      id: "vision-04",
      number: "04",
      title: "U-Net Segmentation",
      file: "04_Unet.ipynb",
      capability: "입력과 같은 해상도의 binary mask를 출력하도록 U-Net의 encoder, skip connection, decoder와 손실 계산을 구현할 수 있다.",
      summary: "[B,1,H,W] 이미지가 encoder에서 축소되고 decoder에서 복원되며, 같은 해상도의 skip feature를 채널 축으로 결합해 [B,1,H,W] mask logits를 만듭니다.",
      notebook_goal: "합성 원 데이터와 U-Net을 구성하고 픽셀별 binary segmentation을 학습·평가하는 전체 코드를 구현한다.",
      key_points: [
        { title:"입력·마스크 데이터", purpose:"이미지와 정답 mask를 같은 [C,H,W] float Tensor로 구성합니다.", code:"np.expand_dims(..., axis=0)\ntorch.from_numpy(...)", flow:"[H,W] → [1,H,W]", watch:"img와 mask에 모두 채널 축을 추가해야 합니다." },
        { title:"Encoder", purpose:"MaxPool로 해상도를 절반으로 줄이고 DoubleConv로 채널과 특징을 확장합니다.", code:"MaxPool2d(2)\nDoubleConv(in,out)", flow:"[B,C,H,W] → [B,2C,H/2,W/2]", watch:"padding=1인 3×3 Conv는 H,W를 유지합니다." },
        { title:"Decoder와 Skip", purpose:"decoder feature를 업샘플하고 같은 해상도의 encoder feature를 채널 축으로 연결합니다.", code:"F.pad(...)\ntorch.cat([x2,x1], dim=1)", flow:"up [B,C1,H,W] + skip [B,C2,H,W] → [B,C1+C2,H,W]", watch:"cat의 dim=1은 채널 축입니다." },
        { title:"Binary mask 학습", purpose:"픽셀별 logits와 0/1 mask로 BCE 손실을 계산한 뒤 예측할 때 sigmoid와 threshold를 적용합니다.", code:"BCEWithLogitsLoss\nsigmoid(logits)\nprobs > 0.5", flow:"logits → loss 또는 probability → binary mask", watch:"학습 손실 전에 sigmoid를 중복 적용하지 않습니다." },
      ],
      theory_guide: [
        { title:"1. Segmentation Tensor", concept:"분할은 이미지 하나당 클래스 하나가 아니라 모든 픽셀의 label을 예측하므로 출력에도 H,W 축이 남습니다.", flow:"input [B,1,H,W] → logits [B,1,H,W]", code_signal:"OutConv의 1×1 Conv가 채널만 n_classes로 바꿉니다.", exam_clue:"binary segmentation의 출력 채널은 1입니다." },
        { title:"2. Contracting·Expanding Path", concept:"Encoder는 넓은 문맥을 얻도록 해상도를 줄이고 Decoder는 픽셀 위치를 예측하도록 해상도를 복원합니다.", flow:"H→H/2→...→H/16→...→H", code_signal:"down1~4의 출력을 저장한 뒤 up1~4에서 역순으로 사용합니다.", exam_clue:"up1에는 가장 깊은 x5와 대응 skip x4가 들어갑니다." },
        { title:"3. Skip Connection", concept:"Skip connection은 downsampling 과정에서 잃기 쉬운 경계와 위치 정보를 decoder에 직접 전달합니다.", flow:"encoder feature x2 + upsampled decoder x1 → channel concat", code_signal:"torch.cat([x2,x1], dim=1)", exam_clue:"더하기가 아니라 채널 연결이므로 다음 Conv의 입력 채널 수가 합이 됩니다." },
        { title:"4. Logits와 확률", concept:"BCEWithLogitsLoss는 sigmoid와 binary cross entropy를 안정적으로 합친 손실이며 실제 mask를 만들 때만 sigmoid를 적용합니다.", flow:"train: logits+mask→loss / predict: logits→sigmoid→threshold", code_signal:"criterion에는 raw logits가, 시각화에는 sigmoid(logits)가 들어갑니다.", exam_clue:"BCEWithLogitsLoss 앞에 sigmoid를 넣지 않습니다." },
      ],
      full_code_cells: [
        cell(1, unetDatasetProblem, unetDatasetAnswer, [1,3,6,7,9]),
        cell(2, unetBlocksProblem, unetBlocksAnswer, [1,2,7,8]),
        cell(3, unetUpProblem, unetUpAnswer, [1,4,7]),
        cell(4, unetForwardProblem, unetForwardAnswer, [1,6,7,8,9,10]),
        cell(5, unetTrainProblem, unetTrainAnswer, [0,2,5,6,9,10]),
      ],
      subjective: [
        {id:"unet-q1",sourceId:"unet-01",occurrence:0,answer:"zeros",accepted_answers:["zeros","np.zeros"],topic:"데이터 생성",prompt:"float32 빈 이미지를 만드는 NumPy 함수를 채우세요.",isSourceBlank:false},
        {id:"unet-q2",sourceId:"unet-02",occurrence:0,answer:"ogrid",accepted_answers:["ogrid","np.ogrid"],topic:"좌표 격자",prompt:"원의 중심까지 거리를 계산할 열린 좌표 격자를 만드는 대상을 채우세요.",isSourceBlank:false},
        {id:"unet-q3",sourceId:"unet-03",occurrence:0,answer:"expand_dims",accepted_answers:["expand_dims","np.expand_dims"],topic:"채널 축",prompt:"[H,W] 이미지에 채널 축을 추가하는 NumPy 함수를 채우세요.",isSourceBlank:false},
        {id:"unet-q4",sourceId:"unet-04",occurrence:0,answer:"from_numpy",accepted_answers:["from_numpy","torch.from_numpy"],topic:"Tensor 변환",prompt:"NumPy 배열을 복사 없이 PyTorch Tensor로 변환하는 함수를 채우세요.",isSourceBlank:false},
        {id:"unet-q5",sourceId:"unet-05",occurrence:0,answer:"Conv2d",accepted_answers:["Conv2d","nn.Conv2d"],topic:"DoubleConv",prompt:"3×3 kernel과 padding=1로 H,W를 유지하는 layer를 채우세요.",isSourceBlank:false},
        {id:"unet-q6",sourceId:"unet-06",occurrence:0,answer:"MaxPool2d",accepted_answers:["MaxPool2d","nn.MaxPool2d"],topic:"Downsampling",prompt:"해상도를 절반으로 줄이는 pooling layer를 채우세요.",isSourceBlank:false},
        {id:"unet-q7",sourceId:"unet-07",occurrence:0,answer:"pad",accepted_answers:["pad","F.pad"],topic:"크기 정렬",prompt:"upsampled feature의 H,W를 skip feature에 맞추는 함수를 채우세요.",isSourceBlank:false},
        {id:"unet-q8",sourceId:"unet-08",occurrence:0,answer:"cat, 1",accepted_answers:["cat,1","cat, 1","torch.cat,1","torch.cat, 1"],topic:"Skip concat",prompt:"skip과 decoder feature를 연결하는 함수와 채널 축 번호를 순서대로 채우세요.",isSourceBlank:false},
        {id:"unet-q9",sourceId:"unet-09",occurrence:0,answer:"x4",accepted_answers:["x4"],topic:"Decoder",prompt:"가장 깊은 x5와 함께 up1에 전달할 encoder skip을 채우세요.",isSourceBlank:false},
        {id:"unet-q10",sourceId:"unet-10",occurrence:0,answer:"outc",accepted_answers:["outc","self.outc"],topic:"Output head",prompt:"decoder 출력을 n_classes logits로 바꾸는 모듈을 채우세요.",isSourceBlank:false},
        {id:"unet-q11",sourceId:"unet-11",occurrence:0,answer:"BCEWithLogitsLoss",accepted_answers:["BCEWithLogitsLoss","nn.BCEWithLogitsLoss"],topic:"손실",prompt:"binary mask logits와 0/1 mask를 비교하는 손실을 채우세요.",isSourceBlank:false},
        {id:"unet-q12",sourceId:"unet-12",occurrence:0,answer:"backward",accepted_answers:["backward"],topic:"역전파",prompt:"segmentation loss로 gradient를 계산하는 메서드를 채우세요.",isSourceBlank:false},
        {id:"unet-q13",sourceId:"unet-13",occurrence:0,answer:"sigmoid",accepted_answers:["sigmoid","torch.sigmoid"],topic:"확률",prompt:"binary logits를 0~1 확률로 바꾸는 함수를 채우세요.",isSourceBlank:false},
        {id:"unet-q14",sourceId:"unet-14",occurrence:0,answer:"float",accepted_answers:["float"],topic:"Binary mask",prompt:"threshold 비교 결과를 0.0/1.0 mask Tensor로 바꾸는 메서드를 채우세요.",isSourceBlank:false},
      ],
      mcq: [
        {id:"unet-m1",source_question_id:"unet-q8",topic:"Skip 연결",prompt:"[B,64,H,W] 두 feature를 U-Net skip으로 결합한 직후 shape은?",answer_index:3,explanation:"채널 축 dim=1로 concat하므로 채널 수가 더해집니다.",choices:[{text:"[2B,64,H,W]",why:"배치 축 연결 결과입니다."},{text:"[B,64,2H,W]",why:"높이 축 연결 결과입니다."},{text:"[B,64,H,2W]",why:"너비 축 연결 결과입니다."},{text:"[B,128,H,W]",why:"정답입니다."},{text:"[B,64,H,W]",why:"덧셈이라면 가능하지만 U-Net은 concat을 사용합니다."}]},
        {id:"unet-m2",source_question_id:"unet-q11",topic:"Binary loss",prompt:"BCEWithLogitsLoss에 전달할 모델 출력은?",answer_index:1,explanation:"이 손실은 sigmoid를 내부에 포함하므로 raw logits를 전달합니다.",choices:[{text:"argmax class index",why:"픽셀별 이진 손실을 계산할 연속값이 사라집니다."},{text:"raw logits",why:"정답입니다."},{text:"sigmoid를 두 번 적용한 확률",why:"sigmoid 중복으로 학습이 불안정해집니다."},{text:"0.5로 자른 binary mask",why:"threshold는 미분 불가능해 학습 신호가 끊깁니다."},{text:"입력 이미지",why:"예측 출력이 아닙니다."}]},
        {id:"unet-m3",source_question_id:"unet-q9",topic:"Skip 순서",prompt:"decoder의 첫 up block에서 함께 사용하는 올바른 조합은?",answer_index:2,explanation:"가장 깊은 x5를 한 단계 올린 뒤 같은 해상도의 x4와 결합합니다.",choices:[{text:"x1과 x2",why:"얕은 encoder 단계 조합입니다."},{text:"x5와 x1",why:"해상도 차이가 너무 큽니다."},{text:"x5와 x4",why:"정답입니다."},{text:"x4와 x3",why:"bottleneck x5가 빠졌습니다."},{text:"x5만 사용",why:"skip connection이 사라집니다."}]},
      ],
    }, {
      id: "vision-05",
      number: "05",
      title: "DDPM Diffusion",
      file: "05_DDPM.ipynb",
      capability: "임의의 timestep에서 원본에 노이즈를 추가하고, U-Net의 노이즈 예측을 학습한 뒤 역확산으로 이미지를 생성할 수 있다.",
      summary: "원본 x0와 Gaussian noise로 xt를 직접 만들고, timestep-conditioned U-Net이 noise를 예측하도록 학습합니다. 생성 시 xT에서 시작해 t를 역순으로 줄이며 x0를 복원합니다.",
      notebook_goal: "DDPM의 beta schedule, forward diffusion, 노이즈 예측 손실, reverse sampling을 수식과 PyTorch 코드로 연결한다.",
      key_points: [
        { title:"Timestep embedding", purpose:"정수 timestep을 U-Net의 각 ResNet block에서 사용할 연속 벡터로 바꿉니다.", code:"sin/cos frequency\ntime[:,None] × freq[None,:]", flow:"[B] → [B,time_dim]", watch:"sin과 cos를 붙이므로 half_dim을 사용합니다." },
        { title:"Forward diffusion", purpose:"누적 alpha 계수를 이용해 x0에서 원하는 xt를 한 번에 샘플링합니다.", code:"xt=√ᾱt·x0+√(1-ᾱt)·ε", flow:"x0 + t + ε → xt", watch:"두 계수는 이미지에 broadcast되도록 [B,1,1,1]이어야 합니다." },
        { title:"Noise prediction loss", purpose:"실제로 섞은 noise와 U-Net이 예측한 noise를 비교해 denoiser를 학습합니다.", code:"predicted_noise=model(x_noisy,t)\nMSE(noise,predicted_noise)", flow:"xt,t → εθ → loss", watch:"정답은 원본 이미지가 아니라 주입한 noise입니다." },
        { title:"Reverse sampling", purpose:"완전한 Gaussian noise에서 시작해 t=T-1부터 0까지 모델이 예측한 noise를 제거합니다.", code:"model_mean\n+ sqrt(posterior_variance) * noise", flow:"xT → xT-1 → ... → x0", watch:"t=0에서는 추가 noise 없이 model_mean을 반환합니다." },
      ],
      theory_guide: [
        { title:"1. Beta·Alpha Schedule", concept:"beta는 단계별 노이즈 양이고 alpha=1-beta, alpha_cumprod는 원본 신호가 t까지 남는 누적 비율입니다.", flow:"βt → αt=1-βt → ᾱt=∏α", code_signal:"torch.cumprod가 alpha_bar를 만듭니다.", exam_clue:"누적합 cumsum이 아니라 누적곱 cumprod입니다." },
        { title:"2. Coefficient extraction", concept:"배치마다 다른 t를 뽑으므로 1차원 schedule에서 각 샘플의 값을 gather하고 이미지 차원으로 reshape해야 합니다.", flow:"schedule [T] + t [B] → [B,1,1,1]", code_signal:"gather(-1,t.cpu()) 뒤 reshape와 to(t.device)가 이어집니다.", exam_clue:"broadcast를 위해 C,H,W 자리에 1을 붙입니다." },
        { title:"3. Forward와 학습 목표", concept:"Forward 과정은 학습 가능한 모델이 아니라 고정 수식이며 U-Net은 xt와 t에서 epsilon을 맞히도록 학습됩니다.", flow:"known ε → q_sample → xt → model → predicted ε", code_signal:"p_losses 안에서 같은 noise를 q_sample과 loss 양쪽에 사용합니다.", exam_clue:"새 noise를 두 번 생성하면 정답이 달라져 학습이 깨집니다." },
        { title:"4. Reverse process", concept:"역과정은 모델 평균과 posterior variance를 사용한 확률적 샘플링이며 마지막 t=0에서는 무작위 항을 제거합니다.", flow:"mean prediction + stochastic noise except t=0", code_signal:"if t_index==0 return model_mean", exam_clue:"반복 순서는 range를 reversed하여 큰 t부터 0까지입니다." },
      ],
      full_code_cells: [
        cell(1, ddpmTimeProblem, ddpmTimeAnswer, [1,3,4,5]),
        cell(2, ddpmScheduleProblem, ddpmScheduleAnswer, [2,3,4]),
        cell(3, ddpmForwardProblem, ddpmForwardAnswer, [2,3,6,9]),
        cell(4, ddpmLossProblem, ddpmLossAnswer, [2,3,4,6]),
        cell(5, ddpmReverseProblem, ddpmReverseAnswer, [6,8,10,11]),
        cell(6, ddpmLoopProblem, ddpmLoopAnswer, [4,7,8,9]),
      ],
      subjective: [
        {id:"ddpm-q1",sourceId:"ddpm-01",occurrence:0,answer:"//",accepted_answers:["//"],topic:"Time embedding",prompt:"sin과 cos에 절반씩 차원을 배정하는 정수 나눗셈 연산자를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q2",sourceId:"ddpm-02",occurrence:0,answer:"exp",accepted_answers:["exp","torch.exp"],topic:"Frequency",prompt:"로그 간격 주파수를 지수값으로 바꾸는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q3",sourceId:"ddpm-03",occurrence:0,answer:"cat",accepted_answers:["cat","torch.cat"],topic:"Time embedding",prompt:"sin과 cos embedding을 마지막 차원으로 결합하는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q4",sourceId:"ddpm-04",occurrence:0,answer:"-",accepted_answers:["-"],topic:"Alpha",prompt:"alpha_t=1 beta_t 사이에 들어갈 연산자를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q5",sourceId:"ddpm-05",occurrence:0,answer:"cumprod",accepted_answers:["cumprod","torch.cumprod"],topic:"Alpha bar",prompt:"alpha의 누적곱 alpha_bar를 만드는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q6",sourceId:"ddpm-06",occurrence:0,answer:"pad",accepted_answers:["pad","F.pad"],topic:"Previous alpha bar",prompt:"alpha_bar 이전 값 배열 맨 앞에 1.0을 붙이는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q7",sourceId:"ddpm-07",occurrence:0,answer:"gather",accepted_answers:["gather"],topic:"계수 추출",prompt:"배치별 timestep에 해당하는 schedule 값을 모으는 메서드를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q8",sourceId:"ddpm-08",occurrence:0,answer:"randn_like",accepted_answers:["randn_like","torch.randn_like"],topic:"Gaussian noise",prompt:"x_start와 같은 shape의 Gaussian noise를 만드는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q9",sourceId:"ddpm-09",occurrence:0,answer:"q_sample",accepted_answers:["q_sample"],topic:"Forward diffusion",prompt:"x0와 noise로 xt를 만드는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q10",sourceId:"ddpm-10",occurrence:0,answer:"x_noisy, t",accepted_answers:["x_noisy,t","x_noisy, t"],topic:"Denoiser 입력",prompt:"노이즈 예측 U-Net에 전달할 두 입력을 순서대로 채우세요.",isSourceBlank:false},
        {id:"ddpm-q11",sourceId:"ddpm-11",occurrence:0,answer:"mse_loss",accepted_answers:["mse_loss","F.mse_loss"],topic:"Noise loss",prompt:"실제 noise와 predicted_noise의 제곱 오차를 계산하는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q12",sourceId:"ddpm-12",occurrence:0,answer:"model",accepted_answers:["model"],topic:"Reverse mean",prompt:"역확산 평균에서 현재 x와 t로 noise를 예측하는 호출 대상을 채우세요.",isSourceBlank:false},
        {id:"ddpm-q13",sourceId:"ddpm-13",occurrence:0,answer:"sqrt",accepted_answers:["sqrt","torch.sqrt"],topic:"Reverse variance",prompt:"posterior variance를 표준편차로 바꾸는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q14",sourceId:"ddpm-14",occurrence:0,answer:"full",accepted_answers:["full","torch.full"],topic:"Timestep batch",prompt:"배치 전체에 같은 현재 timestep을 넣은 Tensor를 만드는 함수를 채우세요.",isSourceBlank:false},
        {id:"ddpm-q15",sourceId:"ddpm-15",occurrence:0,answer:"p_sample",accepted_answers:["p_sample"],topic:"Reverse loop",prompt:"역순 loop에서 한 단계 x_t→x_t-1을 수행하는 함수를 채우세요.",isSourceBlank:false},
      ],
      mcq: [
        {id:"ddpm-m1",source_question_id:"ddpm-q11",topic:"학습 정답",prompt:"DDPM의 기본 noise-prediction U-Net이 직접 맞히는 target은?",answer_index:2,explanation:"q_sample에서 실제로 주입한 Gaussian noise epsilon이 학습 정답입니다.",choices:[{text:"원본 class label",why:"Diffusion은 이 실습에서 label 없이 학습합니다."},{text:"x0 원본 픽셀만",why:"이 구현의 직접 target은 noise입니다."},{text:"주입한 Gaussian noise",why:"정답입니다."},{text:"beta schedule",why:"고정 하이퍼파라미터입니다."},{text:"timestep index",why:"조건 입력이지 예측 target이 아닙니다."}]},
        {id:"ddpm-m2",source_question_id:"ddpm-q5",topic:"Alpha bar",prompt:"alpha_bar_t를 만드는 올바른 연산은?",answer_index:1,explanation:"0부터 t까지 alpha를 곱한 누적곱입니다.",choices:[{text:"torch.cumsum",why:"누적합입니다."},{text:"torch.cumprod",why:"정답입니다."},{text:"torch.mean",why:"평균은 단계별 신호 보존 비율이 아닙니다."},{text:"torch.diff",why:"인접 차이입니다."},{text:"torch.max",why:"최댓값만 남깁니다."}]},
        {id:"ddpm-m3",source_question_id:"ddpm-q13",topic:"t=0 처리",prompt:"reverse sampling의 마지막 t=0에서 반환할 값은?",answer_index:0,explanation:"마지막 단계에서는 새로운 noise를 더하지 않고 예측 평균을 최종 이미지로 사용합니다.",choices:[{text:"model_mean",why:"정답입니다."},{text:"새 Gaussian noise",why:"최종 이미지를 다시 오염시킵니다."},{text:"posterior_variance",why:"분산은 이미지가 아닙니다."},{text:"betas_t",why:"스케줄 계수입니다."},{text:"x를 그대로",why:"denoising 한 단계가 수행되지 않습니다."}]},
        {id:"ddpm-m4",source_question_id:"ddpm-q14",topic:"Reverse 순서",prompt:"생성 과정의 timestep 진행 방향은?",answer_index:3,explanation:"완전한 noise xT에서 시작해 T-1부터 0까지 역순으로 진행합니다.",choices:[{text:"0에서 T까지 정순",why:"forward diffusion 방향입니다."},{text:"무작위 순서",why:"Markov 역과정 순서를 지켜야 합니다."},{text:"항상 t=0",why:"여러 denoising 단계가 사라집니다."},{text:"T-1에서 0까지 역순",why:"정답입니다."},{text:"짝수 timestep만",why:"이 코드에는 step skipping이 없습니다."}]},
      ],
    }, {
      id: "vision-06",
      number: "06",
      title: "Stable Diffusion v1.4",
      file: "06_Stable_Diffusion_v1_4.ipynb",
      capability: "StableDiffusionPipeline을 불러와 prompt, guidance, seed, negative prompt, step, 해상도를 통제하며 재현 가능한 이미지를 생성할 수 있다.",
      summary: "텍스트 prompt가 tokenizer·text encoder를 거쳐 조건이 되고, latent noise를 U-Net이 반복적으로 제거한 뒤 VAE decoder가 최종 PIL 이미지를 만듭니다.",
      notebook_goal: "Stable Diffusion 파이프라인을 구성하고 주요 생성 인자를 바꿔 결과의 의미와 재현성을 비교한다.",
      key_points: [
        { title:"Pipeline 로드", purpose:"모델 저장소의 tokenizer, text encoder, U-Net, scheduler, VAE를 한 번에 구성합니다.", code:"StableDiffusionPipeline.from_pretrained(...)\n.to('cuda')", flow:"model_id → pipeline components → GPU", watch:"float16은 GPU 메모리를 줄이지만 CPU 실행에는 적합하지 않을 수 있습니다." },
        { title:"Prompt와 guidance", purpose:"prompt 조건을 반영해 이미지를 생성하고 guidance_scale로 텍스트 조건의 강도를 조절합니다.", code:"pipe(prompt, guidance_scale=7.5).images[0]", flow:"text + latent noise → denoising → PIL image", watch:"너무 높은 guidance는 품질과 자연스러움을 해칠 수 있습니다." },
        { title:"재현 가능한 비교", purpose:"비교할 인자 외의 초기 noise를 동일하게 유지하기 위해 매 실행 전 같은 seed의 generator를 만듭니다.", code:"torch.manual_seed(seed)\npipe(..., generator=generator)", flow:"same seed + changed one variable → comparable images", watch:"generator를 한 번만 만들고 연속 호출하면 내부 상태가 진행되어 noise가 달라집니다." },
        { title:"생성 제어와 메모리", purpose:"negative prompt, inference steps, width·height를 조절하고 사용 후 CUDA cache를 정리합니다.", code:"negative_prompt\nnum_inference_steps\nwidth,height\nempty_cache()", flow:"generation options → images / cache cleanup", watch:"높은 step과 큰 해상도는 시간과 VRAM 사용량을 늘립니다." },
      ],
      theory_guide: [
        { title:"1. Latent Diffusion Pipeline", concept:"Stable Diffusion은 픽셀 전체가 아니라 VAE가 압축한 latent 공간에서 확산을 수행해 계산량을 줄입니다.", flow:"prompt→text embedding / noise latent→U-Net denoise→VAE decode→image", code_signal:"pipeline components에 tokenizer, text_encoder, unet, scheduler, vae가 포함됩니다.", exam_clue:"최종 반환값은 pipeline result의 images 리스트입니다." },
        { title:"2. Classifier-Free Guidance", concept:"guidance_scale은 무조건 생성과 prompt 조건 생성의 차이를 확대해 텍스트 일치도를 조절합니다.", flow:"low scale=자유로움 / moderate=균형 / excessive=왜곡 가능", code_signal:"pipe 호출의 guidance_scale 인자입니다.", exam_clue:"동일 prompt에서 scale만 비교하려면 seed를 고정합니다." },
        { title:"3. Seed와 Generator", concept:"seed는 초기 latent noise를 재현하게 하며 같은 조건과 seed는 결과 비교의 기준을 고정합니다.", flow:"seed→generator→same initial noise", code_signal:"manual_seed 결과를 generator 인자로 전달합니다.", exam_clue:"스타일·guidance 비교에서는 loop 안에서 같은 seed로 generator를 다시 만듭니다." },
        { title:"4. Negative Prompt·Steps·Size", concept:"negative prompt는 피할 조건, steps는 denoising 반복 수, width와 height는 출력 해상도를 지정합니다.", flow:"constraints + compute budget → generated image", code_signal:"모두 pipe의 keyword argument입니다.", exam_clue:"가로 w는 width, 세로 h는 height에 전달합니다." },
      ],
      full_code_cells: [
        cell(1, sdLoadProblem, sdLoadAnswer, [0,2,4,5,6]),
        cell(2, sdGenerateProblem, sdGenerateAnswer, [2,3]),
        cell(3, sdCompareProblem, sdCompareAnswer, [4,5,6]),
        cell(4, sdNegativeProblem, sdNegativeAnswer, [0,3,5,7]),
        cell(5, sdSizeProblem, sdSizeAnswer, [4,8,9]),
      ],
      subjective: [
        {id:"sd-q1",sourceId:"sd-01",occurrence:0,answer:"StableDiffusionPipeline",accepted_answers:["StableDiffusionPipeline"],topic:"Pipeline",prompt:"diffusers에서 불러올 Stable Diffusion 통합 파이프라인 클래스를 채우세요.",isSourceBlank:false},
        {id:"sd-q2",sourceId:"sd-02",occurrence:0,answer:"from_pretrained",accepted_answers:["from_pretrained"],topic:"모델 로드",prompt:"model_id의 사전학습 구성과 가중치를 불러오는 클래스 메서드를 채우세요.",isSourceBlank:false},
        {id:"sd-q3",sourceId:"sd-03",occurrence:0,answer:"float16",accepted_answers:["float16","torch.float16"],topic:"정밀도",prompt:"GPU 메모리를 줄이기 위해 지정한 dtype을 채우세요.",isSourceBlank:false},
        {id:"sd-q4",sourceId:"sd-04",occurrence:0,answer:"cuda",accepted_answers:["cuda","\"cuda\"","'cuda'"],topic:"Device",prompt:"pipeline을 GPU로 이동할 장치 문자열을 채우세요.",isSourceBlank:false},
        {id:"sd-q5",sourceId:"sd-05",occurrence:0,answer:"components",accepted_answers:["components","pipe.components"],topic:"구성 요소",prompt:"pipeline 내부 모듈 딕셔너리에 접근하는 속성을 채우세요.",isSourceBlank:false},
        {id:"sd-q6",sourceId:"sd-06",occurrence:0,answer:"images, 0",accepted_answers:["images,0","images, 0"],topic:"생성 결과",prompt:"pipeline 반환값에서 첫 번째 PIL 이미지를 꺼낼 속성과 index를 채우세요.",isSourceBlank:false},
        {id:"sd-q7",sourceId:"sd-07",occurrence:0,answer:"manual_seed",accepted_answers:["manual_seed","torch.manual_seed"],topic:"재현성",prompt:"동일한 초기 noise를 재현하도록 seed를 고정하는 함수를 채우세요.",isSourceBlank:false},
        {id:"sd-q8",sourceId:"sd-08",occurrence:0,answer:"scale",accepted_answers:["scale"],topic:"Guidance 비교",prompt:"loop에서 현재 guidance 값을 pipeline에 전달할 변수를 채우세요.",isSourceBlank:false},
        {id:"sd-q9",sourceId:"sd-09",occurrence:0,answer:"neg_prompt",accepted_answers:["neg_prompt"],topic:"Negative prompt",prompt:"생성에서 피할 조건을 전달하는 loop 변수를 채우세요.",isSourceBlank:false},
        {id:"sd-q10",sourceId:"sd-10",occurrence:0,answer:"30",accepted_answers:["30"],topic:"Inference steps",prompt:"네거티브 프롬프트 비교에서 사용한 denoising step 수를 채우세요.",isSourceBlank:false},
        {id:"sd-q11",sourceId:"sd-11",occurrence:0,answer:"w, h",accepted_answers:["w,h","w, h"],topic:"출력 크기",prompt:"width와 height에 전달할 loop 변수를 순서대로 채우세요.",isSourceBlank:false},
        {id:"sd-q12",sourceId:"sd-12",occurrence:0,answer:"empty_cache",accepted_answers:["empty_cache","torch.cuda.empty_cache"],topic:"VRAM 정리",prompt:"PyTorch가 예약한 사용 가능 CUDA cache를 비우는 함수를 채우세요.",isSourceBlank:false},
      ],
      mcq: [
        {id:"sd-m1",source_question_id:"sd-q6",topic:"Pipeline 결과",prompt:"StableDiffusionPipeline 호출 결과에서 최종 이미지 한 장을 얻는 표현은?",answer_index:1,explanation:"pipeline 결과의 images 리스트에서 첫 항목을 선택합니다.",choices:[{text:".latents[0]",why:"latent는 최종 PIL 이미지 반환 속성이 아닙니다."},{text:".images[0]",why:"정답입니다."},{text:".logits.argmax()",why:"분류 모델 방식입니다."},{text:".pred_boxes[0]",why:"DETR 출력 방식입니다."},{text:".sample()",why:"이 pipeline 결과 접근법이 아닙니다."}]},
        {id:"sd-m2",source_question_id:"sd-q7",topic:"공정한 비교",prompt:"guidance_scale만 비교할 때 반드시 같게 유지할 항목은?",answer_index:3,explanation:"같은 seed로 초기 latent noise를 고정해야 scale 차이만 관찰할 수 있습니다.",choices:[{text:"출력 파일명만",why:"생성 내용에 영향이 없습니다."},{text:"subplot 위치만",why:"표시 위치일 뿐입니다."},{text:"VRAM 사용량만",why:"초기 noise를 고정하지 못합니다."},{text:"prompt와 seed",why:"정답입니다."},{text:"이미지 title만",why:"시각화 문구입니다."}]},
        {id:"sd-m3",source_question_id:"sd-q9",topic:"생성 제어",prompt:"원하지 않는 사람과 빨간색 요소를 억제할 때 사용할 인자는?",answer_index:2,explanation:"피하고 싶은 내용을 negative_prompt로 전달합니다.",choices:[{text:"width",why:"가로 해상도입니다."},{text:"num_inference_steps",why:"반복 횟수입니다."},{text:"negative_prompt",why:"정답입니다."},{text:"torch_dtype",why:"수치 정밀도입니다."},{text:"model_id",why:"모델 선택입니다."}]},
        {id:"sd-m4",source_question_id:"sd-q11",topic:"비용",prompt:"대체로 생성 시간과 VRAM을 가장 직접 늘리는 조합은?",answer_index:4,explanation:"큰 공간 해상도는 latent와 attention 계산량을, 많은 steps는 U-Net 반복 횟수를 늘립니다.",choices:[{text:"짧은 prompt와 낮은 seed",why:"seed 숫자 크기는 비용과 무관합니다."},{text:"negative prompt 제거",why:"큰 비용 감소의 직접 요인이 아닙니다."},{text:"components 출력",why:"모듈 이름 출력입니다."},{text:"같은 seed 재사용",why:"재현성 설정입니다."},{text:"큰 width·height와 많은 steps",why:"정답입니다."}]},
      ],
    }],
  };
})();
