/* 1. Llama_index.ipynb의 설명 셀을 시험 흐름 중심으로 한국어화한 학습용 번역입니다. */
window.INLINE_MARKDOWN_KO = {
  "1. Llama_index.ipynb": {
    1: "# LlamaIndex 실습\n\n간단한 LlamaIndex 앱을 만들며 LLM 응답을 기록·확인하고, 목적에 맞게 Query Engine을 수정하는 방법을 학습합니다.\n\n구성: I. Query Engine 만들기 → II. Index 문서 관리 → III. Custom Query Engine 만들기",
    2: "## I. Query Engine 만들기\n\n사용자 질문을 받아 관련 문서를 검색하고 최종 요약·답변을 반환하는 Query Engine을 구현합니다.\n\n순서: 1) 라이브러리 설치·import → 2) 데이터 준비 → 3) Index에서 Query Engine 생성 → 4) 질문 실행",
    3: "### 1. 라이브러리 설치와 import",
    6: "### 2. 데이터 준비\n\nQuery Engine의 입력은 **사용자 질문**과 **검색용 문서 저장소(Vector Store)**이고, 출력은 검색된 근거를 바탕으로 만든 답변입니다. 이 실습에서는 외부 DB 대신 로컬 메모리에 Vector Store를 구성하고 txt 파일을 문서로 사용합니다.",
    8: "다운로드가 끝나면 `paul_graham_essay.txt`가 `data` 폴더에 있어야 합니다. 이후 이 파일의 앞부분을 출력해 어떤 문서인지 확인합니다.",
    11: "### 3. Index에서 Query Engine 바로 만들기\n\nLlamaIndex는 원본 텍스트 파일을 그대로 검색하지 않습니다. 먼저 파일을 `Document`로 읽고, 이를 Node와 embedding으로 변환해 Index를 만듭니다.\n\n`SimpleDirectoryReader(\"data\").load_data()`는 폴더 안 파일을 `Document` 목록으로 읽습니다.",
    12: "`documents`의 각 원소에는 원문 텍스트가 들어 있습니다. 반복문에서 `documents[i].text`를 출력하면 읽어 온 내용을 확인할 수 있습니다.",
    15: "Document를 읽었으면 검색 가능한 Index를 만듭니다. `VectorStoreIndex.from_documents(documents)`는 Document를 Node로 나누고 embedding을 저장합니다. 외부 Vector DB를 연결하지 않으면 로컬 메모리 Vector Store를 사용합니다.",
    17: "이제 Index 내부 구조를 확인합니다. Index는 Document를 그대로 저장하기보다 검색 단위인 여러 Node로 나눠 저장합니다.",
    19: "`nodes_dict`를 보면 첫 Node의 ID와 전체 Node 수를 확인할 수 있습니다. 다음 단계에서는 이 Node가 어떤 embedding 벡터로 변환됐는지 확인합니다.",
    21: "Index를 만들면 각 Node는 자동으로 embedding 벡터가 됩니다. Node 분할 규칙은 `SentenceSplitter`로 확인할 수 있으며, `chunk_size`와 `chunk_overlap`을 설정할 수 있습니다.",
    23: "각 Node는 `.text` 속성으로 원문을 확인할 수 있습니다. 이웃 Node는 `chunk_overlap`만큼 일부 문맥을 공유합니다. `SentenceSplitter`는 문자 수가 아니라 token 단위로 나누므로 Node마다 문자 길이는 다를 수 있습니다.",
    25: "`SentenceSplitter`가 기본으로 사용하는 토크나이저로 Node의 token 수를 직접 확인합니다. Node 크기는 metadata까지 고려해 계산되므로, 단순 텍스트 token 수와 설정한 `chunk_size`가 완전히 같지 않을 수 있습니다.",
    27: "Index를 만들 때 기본 분할 규칙 대신 원하는 `chunk_size`, `chunk_overlap`을 쓰려면 `VectorStoreIndex.from_documents`의 `transformations` 인자에 splitter 목록을 넣습니다.",
    30: "이후 실습에서는 기본 `SentenceSplitter`를 사용합니다.",
    32: "Index가 완성되면 `index.as_query_engine()`으로 검색과 답변 생성을 묶은 Query Engine을 바로 만들 수 있습니다.",
    34: "### 4. Query Engine 실행\n\n실제 질문을 넣어 Query Engine의 답변을 확인합니다. 데이터에 직접 답이 있는 질문, 관련 없는 질문, 간접 추론이 필요한 질문을 차례로 비교합니다.",
    35: "### 4-1. 데이터가 직접 답할 수 있는 질문\n\n원문에 답이 명시된 질문을 실행합니다. 이 경우 Query Engine은 관련 passage를 찾아 근거 기반 답변을 만드는 것이 기대됩니다.",
    38: "예상대로 원문 근거에 맞는 답을 반환합니다.",
    39: "### 4-2. 데이터와 무관한 질문\n\nQuery Engine은 외부 문서에 질문할 수 있는 인터페이스입니다. 따라서 문서에 근거가 없는 질문에는 신뢰할 수 있는 답을 만들면 안 됩니다. 문서 밖의 파라미터 지식이 섞이면 최신성·정확성을 보장할 수 없습니다.",
    41: "문서와 무관한 질문에는 정확한 근거 기반 답을 만들지 못합니다. 이 실습의 Query Engine 응답 합성에는 기본 LLM이 사용된다는 점을 확인합니다.",
    44: "기본 LLM은 해당 일반 지식을 이미 알고 있을 수 있습니다. 하지만 txt 파일 안에는 그 근거가 없으므로, RAG 답변이 원문 근거만 사용했는지와 LLM 사전지식이 섞였는지를 구분해야 합니다.",
    45: "### 4-3. 복합 추론이 필요한 질문\n\n문서와 관련은 있지만 답이 직접 한 문장에 적혀 있지 않은 질문을 넣어 봅니다. 검색 결과와 모델의 추론이 어떤 관계인지 확인하는 단계입니다.",
    47: "원문에서 Paul Graham을 직접 언급한 문장을 확인합니다. 이 문장만으로 저자가 누구인지 충분히 판단할 수 있는지 먼저 생각해 봅니다.",
    49: "Query Engine이 생각보다 자연스러운 답을 냈다면, 실제로 어떤 passage를 근거로 사용했는지 Retriever 결과를 확인해야 합니다.",
    51: "검색된 passage가 흩어져 있으면 답변 근거를 확인하기 어렵습니다. Retriever 결과에 질문을 뒷받침하는 문장이 있는지 직접 검사합니다.",
    53: "Retriever가 직접 단서를 찾지 못할 수도 있습니다. 이때 Query Engine의 답에 LLM의 사전지식이나 간접 추론이 섞였을 가능성을 의심해야 합니다.",
    55: "Query Engine은 직접 근거뿐 아니라 간접 내용과 LLM 사전지식을 활용해 답할 수 있습니다. 시험에서는 `retriever.retrieve()`의 근거 목록과 `query_engine.query()`의 최종 답변을 구분하는 것이 핵심입니다.",
    56: "## II. Index 문서 관리\n\n새 데이터를 반영할 때마다 Document·Index·Query Engine을 전부 다시 만들면 비효율적입니다. LlamaIndex는 기존 Index에 문서를 추가·수정·삭제하는 API를 제공합니다.",
    57: "### 1. Insert\n\n기존 Index에 새 Document를 추가합니다. 추가 전에는 답할 근거가 없던 질문을 실행하고, Document를 넣은 뒤 Query Engine의 답이 어떻게 달라지는지 확인합니다.",
    59: "문서 추가 전에도 LLM이 일반 지식으로 답을 만들 수 있습니다. 하지만 새 Document에 들어 있는 구체적 수치까지 답하려면 Index에 근거가 추가되어야 합니다.",
    62: "새 `Document`를 Insert한 뒤 새 Query Engine으로 질문하면, 추가한 문서의 상세 정보를 반영한 답변을 기대할 수 있습니다. 다음은 문서 내용을 수정하는 단계입니다.",
    63: "### 2. Update\n\n같은 `doc_id`를 가진 Document의 내용을 바꾼 뒤 `update_ref_doc`으로 한 문서를 갱신합니다. 여러 문서를 한꺼번에 반영할 때는 `refresh_ref_docs([docu])`를 사용합니다. 갱신 대상 문서가 실제로 바뀌지 않았다면 결과 목록에 `False`가 나올 수 있습니다.",
    66: "`index.ref_doc_info.keys()`로 Index에 들어 있는 `doc_id` 목록을 확인할 수 있습니다. Insert가 제대로 됐는지 점검할 때 사용합니다.",
    68: "### 3. Delete\n\n추가한 Document는 `doc_id`로 식별합니다. 이 ID를 이용해 Index에서 특정 참조 문서를 삭제할 수 있습니다.",
    70: "`index.delete_ref_doc(id, delete_from_docstore=True)`로 문서를 삭제합니다. `delete_from_docstore`는 Index에서만 제거할지, 문서 저장소에서도 함께 제거할지를 결정합니다.",
    72: "삭제 뒤에도 답변에 이전 데이터의 상세 내용이 나온다면 `index.ref_doc_info.keys()`에서 해당 `doc_id`가 정말 사라졌는지 확인합니다.",
    74: "## III. Custom Query Engine 만들기\n\n기존 Query Engine 내부의 Retriever와 Response Synthesizer를 명시적으로 조합해, 원하는 검색·답변 방식을 가진 Custom Query Engine을 만듭니다.",
    75: "### 1. Query Engine 내부 구성\n\n`retriever`는 관련 Node를 찾고, `response_synthesizer`는 질문과 Node를 받아 답변을 합성합니다. 이 두 부품을 직접 연결한 클래스를 만듭니다.",
    77: "Retriever와 Response Synthesizer를 초기화한 뒤, 직접 만든 Query Engine 클래스가 정상적으로 동작하는지 확인합니다.",
    79: "### 2. Prompt를 사용하는 Custom Query Engine\n\n검색 결과를 LLM에 전달할 때 PromptTemplate으로 답변 정책을 직접 정할 수 있습니다. 여기서는 검색 Node의 내용을 context로 합치고, 원문 근거만 사용하도록 prompt를 구성합니다.",
    82: "마지막으로 만든 Custom Query Engine에 질문을 넣어, 설정한 prompt 정책대로 동작하는지 확인합니다."
  }
};
