/* RAG Chapter 1: 시험 범위(흐름 + llama-index 활용)에 맞춘 인라인 빈칸 확장 */
window.INLINE_EXAM_OVERRIDES = {
  "1. Llama_index.ipynb": {
    replacements: [
      {cell: 18, id: "rag-nodes-dict", from: "node_id = index.index_struct.nodes_dict"},
      {cell: 22, id: "rag-chunk-nodes", from: "nodes = parser.get_nodes_from_documents(documents)"},
      {cell: 28, id: "rag-index-transform", from: "index = VectorStoreIndex.from_documents(documents=documents, transformations=[text_splitter])"},
      {cell: 37, id: "rag-query-run", from: "response = query_engine.query(\"What is the first programs the author tried writing?\")"},
      {cell: 50, id: "rag-as-retriever", from: "retriever = index.as_retriever()"},
      {cell: 50, id: "rag-retriever-run", from: "ret_passages = retriever.retrieve(\"Who is the author?\")"},
      {cell: 54, id: "rag-context-var", from: "{ret_context}"},
      {cell: 60, id: "rag-document-id-key", from: "id_"},
      {cell: 60, id: "rag-index-insert", from: "index.insert(docu)"},
      {cell: 64, id: "rag-set-content", from: "docu.set_content"},
      {cell: 64, id: "rag-index-update", from: "index.update_ref_doc"},
      {cell: 69, id: "rag-document-id", from: "docu.doc_id"},
      {cell: 71, id: "rag-index-delete", from: "index.delete_ref_doc"},
      {cell: 76, id: "rag-standard-retrieve", from: "nodes = self.retriever.retrieve(query_str)"},
      {cell: 76, id: "rag-synthesize", from: "response_obj = self.response_synthesizer.synthesize(query_str, nodes)"},
      {cell: 78, id: "rag-standard-components", from: "retriever=retriever, response_synthesizer=synthesizer"},
      {cell: 81, id: "rag-custom-retrieve", from: "nodes = self.retriever.retrieve(query_str)"},
      {cell: 81, id: "rag-node-content", from: "n.node.get_content()"},
      {cell: 81, id: "rag-llm-complete", from: "self.llm.complete"},
      {cell: 81, id: "rag-prompt-format", from: "self.qa_prompt.format(context_str=context_str, query_str=query_str)"},
      {cell: 83, id: "rag-custom-retriever-arg", from: "retriever=retriever"},
      {cell: 83, id: "rag-custom-synthesizer-arg", from: "response_synthesizer=synthesizer"},
      {cell: 83, id: "rag-custom-llm-arg", from: "llm=llm"},
      {cell: 83, id: "rag-custom-prompt-arg", from: "qa_prompt=simple_qa_prompt"},
    ],
    blanks: [
      {id: "rag-nodes-dict", label: "Index의 Node ID 사전 확인", answer: "node_id = index.index_struct.nodes_dict"},
      {id: "rag-chunk-nodes", label: "Document → Node 청킹", answer: "nodes = parser.get_nodes_from_documents(documents)"},
      {id: "rag-index-transform", label: "Splitter를 적용한 Index 생성", answer: "index = VectorStoreIndex.from_documents(documents=documents, transformations=[text_splitter])"},
      {id: "rag-query-run", label: "Query Engine 실행", answer: "response = query_engine.query(\"What is the first programs the author tried writing?\")"},
      {id: "rag-as-retriever", label: "Index에서 Retriever 생성", answer: "retriever = index.as_retriever()"},
      {id: "rag-retriever-run", label: "Retriever로 근거 passage 검색", answer: "ret_passages = retriever.retrieve(\"Who is the author?\")"},
      {id: "rag-context-var", label: "Prompt에 넣을 검색 문맥 변수", answer: "ret_context"},
      {id: "rag-document-id-key", label: "Document 생성자의 ID keyword", answer: "id_"},
      {id: "rag-index-insert", label: "새 Document를 Index에 추가", answer: "index.insert(docu)"},
      {id: "rag-set-content", label: "Document 본문 변경 메서드", answer: "docu.set_content"},
      {id: "rag-index-update", label: "참조 문서 갱신 API", answer: "index.update_ref_doc"},
      {id: "rag-document-id", label: "Document의 삭제용 ID", answer: "docu.doc_id"},
      {id: "rag-index-delete", label: "참조 문서 삭제 API", answer: "index.delete_ref_doc"},
      {id: "rag-standard-retrieve", label: "StandardQueryEngine 내부 검색", answer: "nodes = self.retriever.retrieve(query_str)"},
      {id: "rag-synthesize", label: "검색 Node로 답변 합성", answer: "response_obj = self.response_synthesizer.synthesize(query_str, nodes)"},
      {id: "rag-standard-components", label: "StandardQueryEngine 부품 주입", answer: "retriever=retriever, response_synthesizer=synthesizer"},
      {id: "rag-custom-retrieve", label: "Custom Query Engine 내부 검색", answer: "nodes = self.retriever.retrieve(query_str)"},
      {id: "rag-node-content", label: "검색 Node의 본문 추출", answer: "n.node.get_content()"},
      {id: "rag-llm-complete", label: "LLM completion 실행", answer: "self.llm.complete"},
      {id: "rag-prompt-format", label: "context와 질문을 PromptTemplate에 주입", answer: "self.qa_prompt.format(context_str=context_str, query_str=query_str)"},
      {id: "rag-custom-retriever-arg", label: "Custom Engine Retriever 주입", answer: "retriever=retriever"},
      {id: "rag-custom-synthesizer-arg", label: "Custom Engine Synthesizer 주입", answer: "response_synthesizer=synthesizer"},
      {id: "rag-custom-llm-arg", label: "Custom Engine LLM 주입", answer: "llm=llm"},
      {id: "rag-custom-prompt-arg", label: "Custom Engine Prompt 주입", answer: "qa_prompt=simple_qa_prompt"},
    ],
  },
};
